castorini/anserini

- pom.xml
- src/main/java/io/anserini/document/ClueWeb09WarcRecord.java
- src/main/java/io/anserini/index/IndexArgs.java
- src/main/java/io/anserini/index/IndexClueWeb09b.java
- src/main/java/io/anserini/search/SearchClueWeb09b.java
I reformatted three java files, plus pom.xml. Didn't touch other files.
> issue #16: make indent 2 spaces, and remove unused dependency

- pom.xml
- src/main/java/io/anserini/nrts/TweetSearcher.java
- src/main/java/io/anserini/nrts/TweetServlet.java
Refactor with Issue#13 Jetty servlet
> Refactor TweetSearcherServer

- src/main/java/io/anserini/index/IndexArgs.java
- src/main/java/io/anserini/index/IndexWebCollection.java
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchWebCollection.java
It is convenient to add this to the CLI argument
> Add keep stop words CLI support

- README.md
- pom.xml
- src/main/java/io/anserini/document/twitter/Status.java
- src/main/java/io/anserini/rts/Indexer.java
- src/main/java/io/anserini/rts/InterestProfile.java
- src/main/java/io/anserini/rts/NewTopicsPeriodicalRunnable.java
- src/main/java/io/anserini/rts/README.md
- src/main/java/io/anserini/rts/Registrar.java
- src/main/java/io/anserini/rts/ScoreDocTimestamp.java
- src/main/java/io/anserini/rts/TRECAnalyzer.java
- src/main/java/io/anserini/rts/TRECIndexerRunnable.java
- src/main/java/io/anserini/rts/TRECScenarioRunnable.java
- src/main/java/io/anserini/rts/TRECSearcher.java
- src/main/java/io/anserini/rts/TRECTopic.java
- src/main/java/io/anserini/rts/TRECTwokenizer.java
- src/main/java/io/anserini/rts/TitleCoordSimilarity.java
- src/main/java/io/anserini/rts/TitleExpansionSimilarity.java
- src/main/java/io/anserini/rts/TopicPoller.java
- src/test/java/io/anserini/document/twitter/JsonTweetsBlockTest.java
Merge YoGosling baseline (RTS 2016) to Anserini. Would need to collaborate with the RTS broker to test.
> New rebase branch

- pom.xml
- src/main/java/io/anserini/index/DumpIndex.java
- src/main/java/io/anserini/index/DumpIndexArgs.java
- src/main/java/io/anserini/index/README.md
> refactor of DumpIndex -- move to index package

- README.md
- docs/topics-and-qrels.md
- eval/gdeval.pl
+  Moved topics and qrels document into docs/; other minor tweaks.
+  Added gdeval script from https://github.com/trec-web/trec-web-2013/blob/master/src/eval/gdeval.pl
> Eval update

- docs/topics-and-qrels.md
- topics and qrels info for WT2G and WT10G
> add wt collections info

- README.md
- docs/experiments-clueweb09b.md
- docs/experiments-clueweb12-b13.md
- docs/experiments-clueweb12.md
- docs/experiments-gov2.md
+ Updated results from regression of gov2 experiments.
+ Added trec_eval and gdeval examples.
> Updated gov2 experiments

- src/main/java/io/anserini/collection/CW09Collection.java
- src/main/java/io/anserini/collection/CW12Collection.java
- src/main/java/io/anserini/collection/Collection.java
- src/main/java/io/anserini/collection/DiscoverFiles.java
- src/main/java/io/anserini/collection/Gov2Collection.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TrecwebCollection.java
- src/main/java/io/anserini/collection/WarcCollection.java
- src/main/java/io/anserini/collection/WtCollection.java
Just a bunch of minor changes as I'm going through and re-examining the Collection API.
> Light refactoring of collection code

- pom.xml
- src/main/java/io/anserini/index/IndexUtils.java
Integrated sentence splitter into Lucene  with Stanford CoreNLP.
> integrating sentence splitter (#132)

- src/main/js/index.html
- src/main/js/recorder.js
- src/main/js/speech.js
- src/main/python/api.py
- src/main/python/jaccard.py
Update Flask API to return top k passages and display them along with the Jaccard similarity between the passage and the query. Resolves #151 
@salman1993
> QA System: Show Top k Passages

- .gitignore
- docs/flask-api.md
- src/main/js/recorder.js
- src/main/python/api.py
- src/main/python/config.cfg.example
Addresses #154. Can place the key in `config.cfg` as a one-time change.
> Read secrets from config file

- src/main/java/io/anserini/py4j/PyseriniEntryPoint.java
- src/main/python/api.py
- fixed the QA bug by adding query to sentences list 
- fixed another API bug while reading from config file - port must be int, not str
> fixed #150: QA system bug: what is the capital of canada

- pom.xml
- src/main/java/io/anserini/collection/Collection.java
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/main/java/io/anserini/document/WikipediaArticle.java
- src/main/java/io/anserini/index/IndexCollection.java
So that we can index Wikipedia, see #149
> Collection API for Wikipedia

- docs/setup_qa_pipeline.md
- requirements.txt
- run_ui.sh
- src/main/python/api.py
- Pipeline for running end2end QA system
- Managed model dependencies through python packaging
- Added documentation and shared the additional required files.
> end2end qa pipeline (#167)

- docs/setup_qa_pipeline.md
- requirements.txt
- add Py4j, Flask, and nltk to the requirement file.
- updated docs
> updated docs and requirement files

- src/main/python/api.py
- simplified the demo to be compatible with the new bridge
- option to choose to output from the `PassageScorer` or `sm_cnn`
> updated demo

- docs/end2end-TrecQA-eval.md
- requirements.txt
- src/main/python/run_trecqa.py
as part of the sourcing-IDF-from-index and e2e experiments.
> we can now specify a particular model file for e2e

- docs/add-collection-class.md
- docs/dumpindex.md
- docs/embeddings.md
- docs/experiments-clueweb09b.md
- docs/experiments-clueweb12-b13.md
- docs/experiments-clueweb12.md
- docs/experiments-disk12.md
- docs/experiments-gov2.md
- docs/experiments-robust04.md
- docs/experiments-robust05.md
- docs/experiments-tweets2011.md
- docs/experiments-wt.md
- docs/index-collection.md
- docs/twitter-nrts.md
- docs/yogosling.md
- updated existing docs
- line wrapping for better readability
> updated docs (#171)

- src/main/java/io/anserini/kg/freebase/Freebase.java
- src/main/java/io/anserini/kg/freebase/FreebaseNode.java
- src/main/java/io/anserini/kg/freebase/IndexNodes.java
- src/main/java/io/anserini/kg/freebase/IndexTopics.java
- src/main/java/io/anserini/kg/freebase/LookupNode.java
- src/test/java/io/anserini/kg/freebase/FreebaseNodeTest.java
More Freebase refactoring:
+ better normalization of object values: 
1. removes quote around string literals
2. undos MQL key escaping
+ simplified code of LookupNode
> Freebase refactoring: object value normalization + LookupNode

- src/main/java/io/anserini/kg/freebase/FreebaseNode.java
- src/test/java/io/anserini/kg/freebase/FreebaseNodeTest.java
- src/test/java/io/anserini/kg/freebase/FreebaseTest.java
Example:
```
$ sh target/appassembler/bin/LookupFreebaseNode -index lucene-index.freebase.nodes -mid fb:m.02mjmr | grep people.person
fb:people.person.children = fb:m.0gh6dh1
fb:people.person.children = fb:m.02nqgyw
fb:people.person.date_of_birth = "1961-08-04"^^<http://www.w3.org/2001/XMLSchema#date>
fb:people.person.education = fb:m.02nqgmw
fb:people.person.education = fb:m.0nbyhqc
fb:people.person.education = fb:m.012m9zwm
fb:people.person.education = fb:m.02nqgn2
fb:people.person.education = fb:m.02nqgp6
...
```
> Shortens Freebase URI

- docs/experiments-microblog.md
- src/main/java/io/anserini/collection/TwitterCollection.java
- src/main/java/io/anserini/document/TwitterDocument.java
- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/rerank/twitter/RemoveRetweetsTemporalTiebreakReranker.java
- src/main/java/io/anserini/search/SearchTweets.java
- Integrated tweet indexing of into our existing framework
- Updated docs
@lintool @snapbug could you please have a look?
> Index microblog collection (#190)

- pom.xml
> modified pom.xml; added shade plugin

- src/main/java/io/anserini/collection/TrecCollection.java
- fixed robust04 file discovery issue by making the RegEx case insensitive
> Robust04 file discovery issue

- docs/experiments-clueweb09b.md
- docs/experiments-clueweb12-b13.md
- docs/experiments-disk12.md
Following the documentation conventions of the other collections.
> Update docs for ClueWeb09b and ClueWeb12-B13

- pom.xml
I went through and removed all the dependencies that weren't needed to clean up the repo.
> pom cleanup

- pom.xml
- src/main/java/io/anserini/collection/CW09Collection.java
- src/main/java/io/anserini/collection/Collection.java
- src/main/java/io/anserini/collection/Gov2Collection.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TrecwebCollection.java
- src/main/java/io/anserini/collection/TweetCollection.java
- src/main/java/io/anserini/collection/WtCollection.java
- src/main/java/io/anserini/eval/QueryJudgments.java
- src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java
- src/main/java/io/anserini/index/generator/TweetGenerator.java
+ Added javadoc hooks
+ Cleaned up imports
> Light code cleanup

- pom.xml
- src/main/java/io/anserini/document/nyt/NYTCorpusDocument.java
- src/main/java/io/anserini/document/nyt/NYTCorpusDocumentParser.java
- src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java
- src/main/java/io/anserini/ltr/TwitterFeatureReranker.java
- src/main/java/io/anserini/rerank/IdentityReranker.java
- src/main/java/io/anserini/rerank/RankLibReranker.java
- src/main/java/io/anserini/rerank/Reranker.java
- src/main/java/io/anserini/rerank/RerankerCascade.java
- src/main/java/io/anserini/rerank/RerankerContext.java
- src/main/java/io/anserini/rerank/Result.java
- src/main/java/io/anserini/rerank/ScoredDocuments.java
+ Fixed invalid HTML entities in javadoc (actual javadoc errors)
+ Started fixing javadoc warnings
+ Added license headers
+ Exclude building javadoc on packages that aren't ready to be used yet
> Minor javadoc fixes

- docs/experiments-microblog.md
- src/main/python/run_regression_tweets2011.py
- src/main/python/run_regression_tweets2013.py
To make index names consistent with all other collections.
> Minor tweaks to tweet index names in regression scripts and documentation

- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java
- src/main/java/io/anserini/index/generator/TweetGenerator.java
+ Tweaked logging output during indexing to make less noisy.
+ Documentation and clarification of what each counter means.
+ Better logging of final counter states.
> Index logging and counter cleanup

- src/test/java/io/anserini/end2end/README.md
- src/test/java/io/anserini/integration/EndToEndTest.java
- src/test/java/io/anserini/integration/IndexerTest.java
- src/test/java/io/anserini/integration/TrecEndToEndTest.java
- src/test/java/io/anserini/integration/TweetEndToEndTest.java
+ io.anserini.end2end -> io.anserini.integration
+ moved io.anserini.index test case into io.anserini.integration
> Renamed test cases

- docs/experiments-core17.md
- src/main/python/run_regression_core17.py
Brings CORE17 regression script and documentation up to date with all other collections.
> Update CORE17 regression script and documentation

- src/main/java/io/anserini/analysis/TweetLowerCaseEntityPreservingFilter.java
- src/main/java/io/anserini/collection/Collection.java
- src/main/java/io/anserini/document/ClueWeb09WarcRecord.java
- src/main/java/io/anserini/document/ClueWeb12WarcRecord.java
Cleaned up a bunch of Javadoc warnings, per #296
> Cleanup of javadoc warnings

- .travis.yml
- src/test/python/python_interface.py
Travis will fail if the python interface is corrupted.
> add python interface integration test to travis

- src/main/java/io/anserini/rerank/lib/AxiomReranker.java
- src/main/java/io/anserini/search/SearchArgs.java
Renaming parameters in axiom reranking model so that they name after whatever are in the paper
> Renaming parameters in axiom reranking model

- src/main/java/io/anserini/collection/WashingtonPostCollection.java
- src/test/java/io/anserini/document/WashingtonPostDocumentTest.java
> Refactor variable names in WashingtonPostCollection

- docs/experiments-core17.md
- src/main/java/io/anserini/collection/NewYorkTimesCollection.java
- src/main/python/run_regression_core17.py
I rewrite some NYT API to make it read files from `BufferedReader` because `TarArchiveInputStream` is already a stream.
> Index NYT Collection for tgz files (#321)

- src/main/java/io/anserini/collection/AbstractFileSegment.java
- src/main/java/io/anserini/collection/CarCollection.java
- src/main/java/io/anserini/collection/ClueWeb09Collection.java
- src/main/java/io/anserini/collection/ClueWeb12Collection.java
- src/main/java/io/anserini/collection/HtmlCollection.java
- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/collection/NewYorkTimesCollection.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TrecwebCollection.java
- src/main/java/io/anserini/collection/TweetCollection.java
- src/main/java/io/anserini/collection/WashingtonPostCollection.java
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/main/java/io/anserini/index/IndexCollection.java
Fixed exception handling when parsing each document and counter update
> Fix exception handling and counter update

- src/main/python/run_regression.py
- src/main/resources/regression/core17.yaml
- src/main/resources/regression/cw09b.yaml
- src/main/resources/regression/cw12.yaml
- src/main/resources/regression/cw12b13.yaml
- src/main/resources/regression/disk12.yaml
- src/main/resources/regression/gov2.yaml
- src/main/resources/regression/mb11.yaml
- src/main/resources/regression/mb13.yaml
- src/main/resources/regression/robust04.yaml
- src/main/resources/regression/robust05.yaml
- src/main/resources/regression/wt10g.yaml
#388 added -storeRawDocs, this patch changes the name of the index to reflect it.
> Added +rawdocs to name of regression indexes

- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/similarity/AxiomaticSimilarity.java
I just found `f2exp.s` and `f2log.s` were 0.25 where they should be 0.5
> Change axiomatic ranking model's to 0.5

- docs/regression-tuna.md
Added CAR17, few other minor tweaks.
> Cleaned up top-level regression docs

- docs/experiments-car17.md
- docs/experiments-core17.md
- docs/experiments-cw09b.md
- docs/experiments-cw12.md
- docs/experiments-cw12b13.md
- docs/experiments-disk12.md
- docs/experiments-gov2.md
- docs/experiments-mb11.md
- docs/experiments-mb13.md
- docs/experiments-robust04.md
- docs/experiments-robust05.md
- docs/experiments-wt10g.md
- src/test/java/io/anserini/doc/DataModel.java
> Fix experiments docs generation error #402

- docs/experiments-mb13.md
With PR #415 - the auto-generated docs have changed. This is just to check in the changed docs.
> mb13 doc tweaks

- src/main/python/run_regression.py
- src/main/resources/regression/cacm.yaml
- src/main/resources/regression/car17.yaml
- src/main/resources/regression/core17.yaml
- src/main/resources/regression/cw09b.yaml
- src/main/resources/regression/cw12.yaml
- src/main/resources/regression/cw12b13.yaml
- src/main/resources/regression/disk12.yaml
- src/main/resources/regression/gov2.yaml
- src/main/resources/regression/mb11.yaml
- src/main/resources/regression/mb13.yaml
- src/main/resources/regression/robust04.yaml
- src/main/resources/regression/robust05.yaml
- src/main/resources/regression/wt10g.yaml
- src/test/java/io/anserini/doc/DataModel.java
Making regression input as array so that we can support regressions on different servers.
Related to #421
> Changing regression input as array

- README.md
- docs/release-notes/release-notes-v0.2.0.md
@Peilin-Yang are there any major changes I forgot to mention?
> v0.2.0 release notes

- README.md
- docs/regressions-log.md
- docs/regressions.md
Changed organization of documentation pages. Minimal changes to actual content.
> Updated regression docs

- src/main/java/io/anserini/analysis/TweetLowerCaseEntityPreservingFilterFactory.java
> Reformat file to follow style guidelines.

- src/main/java/io/anserini/rerank/lib/AxiomReranker.java
@lintool I suspect the same issue with the tests as the Rm3 change (`cw09b` is failing) - I'll re-run the failed regressions once they've finished with more logging and update the regression results if that's the issue.
> Manually construct query instead of using QueryParser.

- README.md
- docs/experiments-jdiq2018.md
- src/main/resources/jdiq2018/doc.template
JDIQ article published. Updating documentation accordingly.
> Updates to documentation for JDIQ article

- README.md
> Update README.md re: issues w/ Java 10 and 11

- docs/common-indexing-options.md
> Add Solr highlighting note

- docs/experiments-jdiq2018.md
> Update experiments-jdiq2018.md per #482

- README.md
> Update README.md per #482

- docs/freebase.md
- src/main/java/io/anserini/kg/LookupFreebaseNodes.java
- src/main/java/io/anserini/kg/LookupFreebaseTriples.java
Matches by any combination of subject, predicate, object.
> Added program to lookup "triples as document" indexes

- pom.xml
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/main/java/io/anserini/util/ExtractWikipediaPassages.java
Run as:
```
mvn exec:java -Dexec.mainClass="io.anserini.util.ExtractWikipediaPassages" -Dexec.args="-input zhwiki-20181201-pages-articles.xml.bz2 -output tmp.txt -lang zh"
```
Sample output:
```
数学.0000	数学 数学是利用符号语言研究數量、结构、变化以及空间等概念的一門学科，从某种角度看屬於形式科學的一種。
数学.0001	数学 數學透過抽象化和邏輯推理的使用，由計數、計算、量度和對物體形狀及運動的觀察而產生。
数学.0002	数学 數學家們拓展這些概念，為了公式化新的猜想以及從選定的公理及定義中建立起嚴謹推導出的定理。
数学.0003	数学 基礎數學的知識與運用總是個人與團體生活中不可或缺的一環。
数学.0004	数学 對數學基本概念的完善，早在古埃及、美索不達米亞及古印度內的古代數學文本便可觀見，而在古希臘那裡有更為嚴謹的處理。
数学.0005	数学 從那時開始，數學的發展便持續不斷地小幅進展，至16世紀的文藝復興時期，因为新的科學發現和數學革新兩者的交互，致使數學的加速发展，直至今日。
数学.0006	数学 数学并成为許多國家及地區的教育範疇中的一部分。
数学.0007	数学 今日，數學使用在不同的領域中，包括科學、工程、醫學和經濟學等。
数学.0008	数学 數學對這些領域的應用通常被稱為應用數學，有時亦會激起新的數學發現，並導致全新學科的發展，例如物理学的实质性发展中建立的某些理论激发数学家对于某些问题的不同角度的思考。
数学.0009	数学 數學家也研究純數學，就是數學本身的实质性內容，而不以任何實際應用為目標。
...
```
> Simple util to segment Chinese Wikipedia

- docs/experiments-trec2018.md
Adding the results for: 
1. CENTRE track results of our runs (note that TREC released the new judgements)
2. Core track results of our runs
Still waiting for News track background linking judgements.
> TREC 2018 Runbook/Results Consolidation

- docs/runbook-trec2018-h2oloo.md
- src/main/python/trec2018/h2oloo-core/submission.py
I was able to reproduce the runs.
> Tweaks to h2oloo TREC 2018 runbook

- docs/runbook-trec2018-h2oloo.md
Elaborated on conda env; fixed a wrong parameter; added comparisons between submitted runs and current runs.
> More tweaks to TREC 2018 h2oloo runbook

- README.md
- docs/release-notes/release-notes-v0.1.0.md
- docs/release-notes/release-notes-v0.2.0.md
- docs/release-notes/release-notes-v0.3.0.md
Thanks to @Peilin-Yang, @r-clancy, @lukuang, @Impavidity, @Kytabyte, @Chriskamphuis, @catenamatteo, @tteofili, @Victor0118 for your contributions!
Onward!
> Release notes for v0.3.0

- src/main/python/ccrf/build_test.py
- src/main/python/ccrf/build_train.py
- src/main/python/ccrf/submission.py
- src/main/python/ccrf/train.py
- src/main/python/ccrf/utils.py
Per #524 - we're going to take our code from TREC 2018 as a starting point and start refactoring to clean up, working our way to building regressions for ECIR 2019.
This initial PR is just @Kytabyte's origin code, with minimal cleanup so that it doesn't rely on a weird directory structure per the runbook.
> Initial ccrf (cross-collection relevance feedback) code for ECIR 2019

- src/main/python/ccrf/build_test.py
- src/main/python/ccrf/build_train.py
- src/main/python/ccrf/submission.py
- src/main/python/ccrf/train.py
- src/main/python/ccrf/utils.py
Per PEP8. No other changes. We're doing this so future changes have clean diffs and it'll be easy to tell what's actually changed.
Ref: #524
> Changed ccrf code to 4-space indentation

- docs/experiments-core18.md
- docs/experiments-robust04.md
- src/main/resources/docgen/templates/core18.template
- src/main/resources/docgen/templates/robust04.template
Added link to user and actual commit.
> Added more details to replication logs

- src/main/java/io/anserini/ltr/DumpTweetsLtrData.java
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/test/java/io/anserini/integration/EndToEndTest.java
Change the topics argument of SearchCollection to a list of strings -- the change will make multiple topic files input possible and this makes the retrieval more flexible
> Change the topics argument of SearchCollection to a list of strings

- src/main/java/io/anserini/search/SimpleSearcher.java
Add a field for tweet search to make sure it works with RM3. 
See: https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/rerank/lib/Rm3Reranker.java#L109
@lintool @Peilin-Yang Could you take a look at this PR?
> Refactor simplesearcher to make RM3 work on MB corpus and results of simplesearcher consistent with searchCollection

- docs/runbook-ecir2019-axiomatic.md
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/python/ecir2019_axiomatic/README.md
- src/main/python/ecir2019_axiomatic/coverage.py
- src/main/python/ecir2019_axiomatic/effectiveness.py
- src/main/python/ecir2019_axiomatic/evaluation.py
- src/main/python/ecir2019_axiomatic/plots.py
- src/main/python/ecir2019_axiomatic/run_batch.py
- src/main/python/ecir2019_axiomatic/search.py
- Adding the judgements coverage 
- Adding the results of using random seeds
- Adding the results of per topic analysis
- Updating the runbook
> Update the ECIR2019 runbook

- docs/runbook-ecir2019-axiomatic.md
Tweaked headings, minor copyediting changes.
> Copyediting on documentation for ECIR 2019 axiomatic runbook

- docs/runbook-ecir2019-ccrf.md
- src/main/python/ccrf/configs/ccrf.0405_core17_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.0405_core17_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.0405_core17_BM25.json
- src/main/python/ccrf/configs/ccrf.0417_robust05_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.0417_robust05_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.0417_robust05_BM25.json
- src/main/python/ccrf/configs/ccrf.04_core17_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.04_core17_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.04_robust05_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.04_robust05_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.0517_robust04_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.0517_robust04_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.0517_robust04_BM25.json
- src/main/python/ccrf/configs/ccrf.05_core17_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.05_core17_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.05_robust04_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.05_robust04_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.17_robust04_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.17_robust04_BM25+RM3.json
- src/main/python/ccrf/configs/ccrf.17_robust05_BM25+AX.json
- src/main/python/ccrf/configs/ccrf.17_robust05_BM25+RM3.json
I think this solved issue #524.
Basically, it included all the experiments we did for the paper and added the runbook.
> Create ecir2019 ccrf runbook and configs

- README.md
- docs/runbook-ecir2019-ccrf.md
Copyediting, reorganized; linebreaking.
> Tweaks to ECIR 2019 ccrf runbook

- src/main/python/compare_runs.py
> Minor tweak to compare_runs script

- src/main/python/compare_runs.py
@lintool @Peilin-Yang 
Could you take a look at this PR?
> update compare script to make it work with NDCG

- src/main/python/compare_runs.py
@lintool Could you review this PR? #566
> update compare script to add per topic analysis function

- src/main/resources/docgen/templates/core17.template
I've updated replication log for TREC 17, I got the very same results described at:
https://github.com/castorini/Anserini/blob/master/docs/experiments-core17.md
> updated replication log for TREC 17

- src/main/java/io/anserini/search/SearchArgs.java
Defaults for BM25 capture a recent email thread w/ Andrew and Shane.
> Clarification of parameter settings for qld and also BM25

- src/main/python/compare_runs.py
> add ggplot style

- src/main/python/rerank/scripts/build_microblog_dataset_castor_style.py
- src/main/python/rerank/scripts/export_microblog_dataset_to_castor.py
- src/main/python/rerank/scripts/utils.py
@lintool Could you take a look at this PR? This is a starting point of my thesis scripts.
> Add scripts to generate microblog data for reranking in the castor style

- src/main/python/rerank/scripts/export_microblog_dataset_to_castor.py
- src/main/python/rerank/scripts/export_robust04_dataset.py
- src/main/python/rerank/scripts/utils.py
@lintool Could you take a look at this PR?
> Add robust04 data generation code for reranking

- docs/document-matchzoo.md
@lintool Could you take a look at this PR? The document is not complete but the skeleton is done.
> add the document for integration with MatchZoo

- docs/experiments-cw12b13.md
- src/main/resources/docgen/templates/cw12b13.template
We should trace down the inconsistencies...
cc/ @matthew-z
> Added cw12b footnote

- docs/document-matchzoo.md
- src/main/python/rerank/scripts/interpolate.py
@lintool Could you review this code?
> add interpolation code

- README.md
- docs/experiments-cw12b13.md
- docs/regressions.md
- src/main/resources/docgen/templates/cw12b13.template
hi @matthew-z please take a look also!
> Added note about Oracle vs. OpenJDK replication issues

- docs/experiments-msmarco.md
- src/main/python/msmarco/retrieve.py
Replicated @rodrigonogueira4 's results. Some documentation tweaks along the way...
> Updated docs for MS MARCO

- src/main/python/msmarco/retrieve.py
- src/main/python/msmarco/tune_bm25.py
- changed to argparse
- update to PEP8
@rodrigonogueira4
> Refactoring of MS MACRO retrieve script

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/TrecTopicReader.java
- src/main/java/io/anserini/search/topicreader/WebTopicReader.java
- src/main/java/io/anserini/search/topicreader/WebxmlTopicReader.java
- src/test/java/io/anserini/search/topicreader/TrecTopicReaderTest.java
- src/test/java/io/anserini/search/topicreader/WebTopicReaderTest.java
+ Updated documentation
+ Added test cases
> Added support for efficiency topics from the TREC 2005 Terabyte Track

- src/main/python/msmarco/tune_bm25.py
This makes it easier to tun on different examples, on different indexes, etc.
> Refactoring BM25 tuning script: parameterized various options

- docs/experiments-msmarco.md
- src/main/python/msmarco/retrieve.py
This PR adds the RM3 tuning script (python) on the MSMARCO reranking dataset. @lintool Could you take a look at this PR?
> add rm3 support

- src/main/python/msmarco/convert_collection_to_jsonl.py
- src/main/python/msmarco/filter_queries.py
+ converted scripts to PEP8 formatting
+ change use to argparse
> MS MARCO scripts reformatting

- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/collection/MultifieldSourceDocument.java
- src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/collection/JsonDocumentArrayTest.java
- src/test/java/io/anserini/collection/JsonDocumentObjectTest.java
- src/test/java/io/anserini/collection/JsonLineObjectTest.java
This was implemented for MS MARCO doc2query experiments. Doesn't appear to help, but this code should be useful for other applications as well, so good to commit to repo.
> Added multifield indexing with JSON collection

- src/main/python/msmarco/augment_collection_with_predictions.py
This is the script I got directly from @rodrigonogueira4 to add the predictions to the collection.
> Script to augment collection with doc2query predictions

- src/main/python/msmarco/augment_collection_with_predictions.py
+ changed to PEP 8 formatting
+ added `--original_copies` - this allows us to script weighted expansion experiments
> Refactor script to augment original collection with query predictions

- src/main/python/msmarco/convert_msmarco_to_trec_qrels.py
- src/main/python/msmarco/convert_msmarco_to_trec_run.py
This allows us to use TREC eval tool and therefore compute other metrics than MRR@10.
> Scripts to convert MSMARCO run and qrels files to TREC format

- src/main/python/msmarco/tune_bm25.py
+ added hooks into trec_eval
+ tunes based on recall
> MS MARCO bm25 tuning script - change to tuning for recall

- docs/regressions-log.md
- docs/regressions.md
Updated documentation, fixed broken links.
> Updated regression log

- docs/regressions-log.md
> Document regression fix of Core18

- src/main/python/openresearch/convert_openresearch_to_whoosh_index.py
Fix the argument naming problems
> Fix small argument problems

- README.md
- docs/release-notes/release-notes-v0.5.1.md
- src/main/python/io/anserini/collection/pyjnius_utils.py
- src/main/python/msmarco/retrieve.py
- src/main/python/openresearch/retrieve.py
- src/main/python/openresearch/retrieve_with_key_terms.py
- src/main/python/rerank/scripts/utils.py
> v0.5.1 documentation update

- .travis.yml
- README.md
- src/main/python/io/anserini/collection/pyjnius_utils.py
- src/main/python/msmarco/retrieve.py
- src/main/python/openresearch/retrieve.py
- src/main/python/openresearch/retrieve_with_key_terms.py
- src/main/python/pyjnius_setup.py
- src/main/python/rerank/scripts/utils.py
- src/test/python/python_interface.py
- Added setup script `src/main/python/pyjnius_setup.py` that searches for the latest matching jar in target
- Replaced existing instances of the following code to call `pyjnius_setup.py` so that version is not hardcoded 
```
import jnius_config
jnius_config.set_classpath("target/anserini-0.6.0-SNAPSHOT-fatjar.jar")
```
- Closes #678.
> Added Pyjnius configuration helper to add jar to classpath

- README.md
- docs/experiments-jdiq2018.md
- docs/regressions-log.md
Fixes various outdated parts of the documentation.
> Lucene8 doc update

- docs/solrini.md
- src/main/resources/solr/anserini-twitter/conf/solrconfig.xml
- src/main/resources/solr/anserini/conf/solrconfig.xml
Fixes https://github.com/castorini/anserini/issues/714
> Update Solr to 8.0.0

- docs/experiments-msmarco-passage.md
- docs/regressions-msmarco-passage.md
- src/main/java/io/anserini/search/SearchMsmarco.java
- src/main/python/msmarco/retrieve.py
- src/main/python/msmarco/tune_bm25.py
- src/main/resources/jdiq2018/doc.template
- src/main/resources/regression/msmarco-passage.yaml
+ Updated docs, retuned BM25
+ Tiny difference in results = noise
+ JDIQ 2018 commit forgotten from last time
> Updating documentation for MS MARCO Passage Task

- README.md
- docs/experiments-msmarco-passage.md
- docs/regressions-msmarco-passage-doc2query.md
- src/main/resources/docgen/templates/msmarco-passage-doc2query.template
- src/main/resources/regression/msmarco-passage-doc2query.yaml
We supply the predict queries: added documentation and regression on replicating https://arxiv.org/abs/1904.08375
> Added document and regressions for doc2query

- docs/regressions-log.md
+ BM25 tuned parameters for MS MARCO doc
+ Doc2query on MS MARCO passage
>  Updated regressions log

- README.md
- docs/additional.md
- docs/elastirini.md
- docs/pyserini.md
- docs/solrini.md
Reorganized "integration" section.
> Refactoring documentation: Pyserini, Solrini, Elastirini

- README.md
> Update README.md: adds request for records of replications

- docs/elastirini.md
- src/main/java/io/anserini/index/IndexCollection.java
Fixes #732
- Index multi-valued fields properly
- Streamline documentation for easier index creation
> Fix issues with indexing multi-valued fields in ES

- src/main/java/io/anserini/index/IndexCollection.java
Looks like JDK 11 might have enabled some new warnings by default?
Fixes https://github.com/castorini/anserini/issues/752
(Quick fix while waiting in the airport... vacation time now)
> Fix a few warnings

- src/main/java/io/anserini/collection/FileSegment.java
> Fix FileSegment to implement closable interface

- docs/experiments-doc2query.md
Minor tweaks, fixed broken path.
> tweaks to TREC CAR doc2query documentation

- docs/regressions-msmarco-doc.md
- src/main/resources/regression/msmarco-doc.yaml
> Added msmarco doc regressions for Ax and PRF

- docs/regressions-log.md
Updated for MS MARCO document regressions added in PR #762. Resolves #761.
> Updated regressions log

- README.md
- docs/regressions-car17v1.5.md
- docs/regressions-car17v2.0-doc2query.md
- docs/regressions-car17v2.0.md
- src/main/resources/docgen/templates/car17v1.5.template
- src/main/resources/docgen/templates/car17v2.0-doc2query.template
- src/main/resources/docgen/templates/car17v2.0.template
- src/main/resources/regression/car17v2.0-doc2query.yaml
Full e2e regression of https://github.com/castorini/anserini/blob/master/docs/experiments-doc2query.md
> Add TREC CAR doc2query regression

- docs/regressions-log.md
Updated for MS MARCO passage regressions added in PR #769.
> Updated regressions log for msmarco passage

- docs/experiments-msmarco-passage.md
added Replication Log
Successfully replicated on:
OS: Ubuntu 18.04.3 LTS 
JAVA: openjdk 11.0.4 2019-07-16
Python: 3.5.2
> BM25 on MS MARCO (Passage) replication

- docs/experiments-msmarco-passage.md
Successfully replicated on:
OS: macOS High Sierra 10.13.3
JAVA: java version "11.0.1" 2018-10-16 LTS
Python: 3.6.4
> Add Replication Log for BM25 on MS MARCO (Passage)

- docs/elastirini.md
- docs/solrini.md
- pom.xml
- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/rerank/ScoredDocuments.java
- src/main/java/io/anserini/search/SearchESCollection.java
- src/main/java/io/anserini/search/SearchElastic.java
- src/main/java/io/anserini/search/SearchSolr.java
Will circle back later to fix Twitter experiments as per https://github.com/castorini/anserini/issues/758
> Replicate search experiments with ES

- src/main/resources/regression/msmarco-doc.yaml
> Updated regression numbers for MS MARCO doc condition

- README.md
- docs/release-notes/release-notes-v0.6.0.md
@r-clancy @emmileaf did I miss anything?
> Release notes for v0.6.0

- docs/regressions-robust04.md
- src/main/resources/docgen/templates/robust04.template
Replicated on:
OS: macOS Mojave 10.14.6
Java: openjdk 12.0.2 2019-07-16
Python: 3.7.4
> Added replication log for Robust04

- pom.xml
- src/main/java/io/anserini/collection/CarCollection.java
- src/main/java/io/anserini/collection/HtmlCollection.java
- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/collection/NewYorkTimesCollection.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TrecwebCollection.java
- src/main/java/io/anserini/collection/TweetCollection.java
- src/main/java/io/anserini/collection/WashingtonPostCollection.java
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/test/java/io/anserini/collection/TrecDocumentTest.java
Documents of the form
```
<DOC id="doc1">
<TEXT>
...
</TEXT>
</DOC>
```
> Handle TREC collection variant from NTCIR-8 ACLIA

- src/main/python/pyserini/pyclass.py
> Update classname for IndexArgs

- docs/regressions-car17v1.5.md
- docs/regressions-car17v2.0.md
> Minor documentation tweak, forgot to check in as part of #837

- docs/experiments-msmarco-passage.md
> Improve description of BM25 tuning for MS MARCO data

- README.md
This PR incorporates and supersedes #782
> Update README.md to Anserini and Pyserini colab demos

- src/main/resources/solr/anserini/conf/managed-schema
> Make "contents" be searchable and stored

- src/main/resources/solr/anserini/conf/managed-schema
> Update comments in config file

- pom.xml
- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Also cleaned up resource inclusion in jar; skips CACM collection.
> Added ability to read topics directly from jar

- pom.xml
- src/main/java/io/anserini/collection/CoreCollection.java
- src/test/java/io/anserini/collection/CoreDocumentTest.java
> Add Indexing file for CORE corpus

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/test/java/io/anserini/search/topicreader/MicroblogTopicReaderTest.java
- src/test/java/io/anserini/search/topicreader/NtcirTopicReaderTest.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
- src/test/java/io/anserini/search/topicreader/TsvStringTopicReaderTest.java
Also added bindings for specific collections.
> Added more test cases for TopicReaders

- src/test/java/io/anserini/integration/IndexerTest.java
Helping @cmacdonald on this...
> Added test case demonstrating how to get term positions out of the index

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/IndexerTestBase.java
- src/test/java/io/anserini/index/BasicIndexOperationsTest.java
- src/test/java/io/anserini/index/CloneIndexTest.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
Breaks mega-testcases into separate files.
> Refactored IndexUtil and related test cases

- src/main/java/io/anserini/index/IndexUtils.java
This piece of code is changed for pyserini.
> Port IndexUtil in Pyserini

- pom.xml
- src/main/java/io/anserini/util/ExtractDocumentLengths.java
- src/main/java/io/anserini/util/ExtractNorms.java
- src/test/java/io/anserini/index/BasicIndexOperationsTest.java
- src/test/java/io/anserini/util/ExtractDocumentLengthsTest.java
- src/test/java/io/anserini/util/ExtractNormsTest.java
+ Fixed issues w/ code to extract doc lengths from doc vectors
+ Added code to extract norms directly from index
> Refactored code to extract doc lengths and norms

- docs/regressions-trec02-ar.md
- src/test/java/io/anserini/util/ExtractDocumentLengthsTest.java
- src/test/java/io/anserini/util/ExtractNormsTest.java
> Closes issue #903

- docs/elastirini.md
- src/main/resources/elasticsearch/index-config.msmarco-passage.json
- src/main/resources/elasticsearch/index-config.robust04.json
Tweaked schema mappings and placed configs in their own files.
Verified Robust04 and MS MARCO passage results.
> Refactoring of the Elastirini documentation

- docs/elastirini.md
- src/main/python/es_integration_test.py
- src/main/python/run_es_regression.py
hey @r-clancy can you give this a whirl? Should be pretty straightforward. Subcommands:
```bash
python src/main/python/run_es_regression.py --ping
python src/main/python/run_es_regression.py --check-index-exists robust04
python src/main/python/run_es_regression.py --delete-index robust04
python src/main/python/run_es_regression.py --create-index robust04
python src/main/python/run_es_regression.py --insert-docs robust04 --input /tuna1/collections/newswire/disk45/
python src/main/python/run_es_regression.py --evaluate robust04
```
This strings everything together:
```bash
python src/main/python/run_es_regression.py --regression robust04 --input /tuna1/collections/newswire/disk45/
```
And for MS MARCO passage:
```bash
python src/main/python/run_es_regression.py --ping
python …
```
> Elasticsearch end-to-end regression tests

- src/main/python/fine_tuning/reconstruct_robus04_tuned_run.py
- src/main/resources/fine_tuning/collections.yaml
Topic file has been renamed.
@daltonj quick sign off, please.
> Fixed path to robust04 topics in tuning scripts

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
+ Added getTopicsWithStringIds in TopicReader - for calling from Pyjnius
+ Exposed standard eval topics
> TopicReader refactorings

- README.md
- docs/approximate-nearestneighbor.md
- src/main/java/io/anserini/analysis/vectors/ApproximateNearestNeighborEval.java
- src/main/java/io/anserini/analysis/vectors/ApproximateNearestNeighborSearch.java
- src/main/java/io/anserini/analysis/vectors/FeatureVectorsTokenizer.java
- src/main/java/io/anserini/analysis/vectors/IndexVectors.java
Improved output, reproduces, @tteofili 's results.
Closes #909
> Refactoring of ANN feature

- docs/experiments-msmarco-passage.md
> Update repro log

- docs/experiments-doc2query.md
- docs/experiments-msmarco-passage.md
> Update replication log for MS MARCO Passage and doc2query

- docs/experiments-msmarco-doc.md
@edwinzhng wasn't able to replicate, and I confirmed that the documentation is incorrect.
@edwinzhng can you match your numbers with these? give me a +1 if they match - thanks!
> Updated guide for MS MARCO doc retrieval

- docs/experiments-msmarco-passage.md
Result replicated by Edward Li on 2020-01-15
> Update repro log for MS MARCO passage

- docs/experiments-msmarco-doc.md
> added replication log for msmarco doc

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/util/DumpAnalyzedQueries.java
- src/main/java/io/anserini/util/ExtractDocumentLengths.java
- src/main/java/io/anserini/util/ExtractNorms.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Improved docs, other cleanup. @JMMackenzie please sign off?
> Minor cleanup of DumpAnalyzeQueries (tweaked docs, etc.)

- src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java
while @edwinzhng was catching me up on the CORE stuff, we found this dead code
> Remove some dead code in LuceneDocumentGenerator

- docs/solrini.md
@edwinzhng @nikhilro take a look also?
> Update solrini.md following Mavis' latest patch

- src/test/java/io/anserini/collection/CollectionTest.java
- src/test/java/io/anserini/collection/JsonCollectionTest.java
- src/test/java/io/anserini/collection/JsonDocumentArrayTest.java
- src/test/java/io/anserini/collection/JsonDocumentObjectTest.java
- src/test/java/io/anserini/collection/JsonLineObjectTest.java
- src/test/resources/sample_docs/json/collection1/doc1.json
- src/test/resources/sample_docs/json/collection1/doc2.json
- src/test/resources/sample_docs/json/collection2/segment1.json
- src/test/resources/sample_docs/json/collection3/segment1.json
Refactored testing of `JsonCollection`. I think it's a lot cleaner now with appropriate abstractions.
> Refactored JsonCollection tests

- src/main/java/io/anserini/search/SearchMsmarco.java
- src/main/java/io/anserini/search/SimpleSearcher.java
> Added batchSearch method variant in SimpleSearcher

- docs/elastirini.md
- src/main/python/run_es_regression.py
> Add core18 collection to Elasticsearch

- README.md
- docs/release-notes/release-notes-v0.8.0.md
@edwinzhng @nikhilro Quick clarification:
> + Added basic Solrini support for CORE collections, bibtex collections, and the ACL Anthology.
Is this actually true?
> Release notes for v0.8.0

- pom.xml
- src/main/java/io/anserini/util/ExtractAverageDocumentLength.java
- src/main/java/io/anserini/util/ExtractDocumentLengths.java
- src/main/java/io/anserini/util/ExtractNorms.java
- src/main/java/io/anserini/util/ExtractTopDfTerms.java
- src/test/java/io/anserini/IndexerWithEmptyDocumentTestBase.java
- src/test/java/io/anserini/util/ExtractAverageDocumentLengthTest.java
- src/test/java/io/anserini/util/ExtractDocumentLengthsTest.java
- src/test/java/io/anserini/util/ExtractTopDfTermsTest.java
Improved testing of `ExtractAverageDocumentLength`, `ExtractDocumentLengths`, `ExtractNorms`, and `ExtractTopDfTerms`.
> Improved testing of various utils

- docs/experiments-covid.md
- pom.xml
- src/main/java/io/anserini/collection/CovidCollection.java
- src/main/java/io/anserini/index/generator/CovidGenerator.java
CovidCollection and CovidGenerator to index [COVID-19 Open Research Dataset](https://pages.semanticscholar.org/coronavirus-research)
> COVID Collection and Generator for Sematic Scholar Corpus

- docs/experiments-covid.md
- src/main/java/io/anserini/collection/CovidCollection.java
- src/main/java/io/anserini/collection/CovidCollectionDocument.java
- src/main/java/io/anserini/collection/CovidFullTextCollection.java
- src/main/java/io/anserini/collection/CovidParagraphCollection.java
- src/main/java/io/anserini/index/generator/CovidGenerator.java
Added a CovidCollectionDocument base class so that we can parameterize `CovidGenerator` properly for all 3 `CovidCollection` classes.
> Refactor CovidCollectionDocument base class for CovidGenerator

- src/main/java/io/anserini/index/generator/CovidGenerator.java
- src/main/resources/solr/setup/covid-collection.sh
Fixed an issue with parsing the year from the COVID dataset and added a script containing the Solr config to set up Blacklight.
> Update year parsing and add Solr config for COVID

- docs/experiments-covid.md
- src/main/resources/solr/schemas/covid.json
@tteofili can you try out these instructions?
> Instructions for indexing COVID collection into Solr

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Successfully replicated on:
OS: macOS Mojave Version 10.14.4
JAVA: openjdk 11.0.5 2019-10-15
Python: 3.6.4
> added Replication Log

- src/main/resources/fine_tuning/collections.yaml
Fixed broken path as a result of #1059
> Fine tuning script: fixed index name/location

- docs/experiments-covid.md
Sanity checked and ready to go.
> Updated indexes for CORD-19 2020/04/10 release

- src/main/java/io/anserini/search/topicreader/CovidTopicReader.java
- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/main/resources/topics-and-qrels/topics.covid-round1.xml
- src/test/java/io/anserini/search/topicreader/CovidTopicReaderTest.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
> Added TopicReader for COVID topics

- src/main/java/io/anserini/search/query/Covid19QueryGenerator.java
- src/test/java/io/anserini/search/query/Covid19QueryGeneratorTest.java
Should yield better queries...
> Remove boilerplate from natural language questions in CovidQueryGenerator

- docs/experiments-msmarco-passage.md
OS: macOS Mojave
version 10.14.1
Java version: 13.0.2
Maven version: 3.6.3_1
Issues: see pr
> Replicate experiments

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment: macOS Catalina Version 10.15.3
No issues encountered.
> new replication log for MSMARCO passage & doc

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
macOS Mojave 10.14.6
java version "11.0.7"
No issues encountered
> replication log for msmarco doc and passage

- docs/experiments-covid.md
Wrapping up #1129 - updating documentation.
> Added CORD-19 blacklisted articles to documentation

- docs/experiments-covid.md
- src/main/java/io/anserini/index/generator/Cord19Generator.java
Excludes two more articles with crazy long abstracts.
> Updates for CORD-19 data drop of 2020/05/01

- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/java/io/anserini/search/query/PhraseQueryGenerator.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
- src/test/java/io/anserini/search/query/PhraseQueryGeneratorTest.java
Created a PhraseQueryGenerator to build phrase queries, and added a support function in the SimpleSearcher to find the document frequency of a phrase. Also added tests for this.
> PhraseQueryGenerator + Phrase df

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/main/resources/topics-and-qrels/topics.covid-round2.xml
- src/test/java/io/anserini/search/topicreader/CovidTopicReaderTest.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
> Added TREC-COVID round 2 topics

- README.md
- docs/experiments-cord19.md
- docs/experiments-covid.md
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/topicreader/CovidTopicReader.java
- src/test/java/io/anserini/search/topicreader/CovidTopicReaderTest.java
Bunch of baselines on different indexes and different topic fields, with fusion.
> TREC-COVID round 1 baselines

- docs/experiments-covid.md
Added additional explanation as well.
> Added R@1000 to TREC-COVID baselines

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
To provide convenient access. Will expose in Pyserini in a separate RP.
> Exposes TREC-COVID topics from UDel

- README.md
- docs/release-notes/release-notes-v0.9.1.md
> Release notes for 0.9.1

- src/main/python/trec-covid/remove_judged_docids.py
resolve https://github.com/castorini/anserini/issues/1157
> remove judged documents in a run file according to a qrel file while preserving k results per-topic

- eval/fusion.py
- eval/measure_judged.py
- [Issue 1161](https://github.com/castorini/anserini/issues/1161)
- Supports RRF & combos sum for now.
> Write a clean script that performs fusion

- docs/experiments-covid.md
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/topicreader/BackgroundLinkingTopicReader.java
This enables experiments with `Covid19QueryGenerator` for TREC-COVID round 1.
Close #1168.
> Exposes option to use custom QueryGenerator in SearchCollection

- docs/experiments-msmarco-passage.md
Environment:
- MacOS Catalina (v10.15.4)
- Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
- Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
- Apache Maven 3.6.1
- Python 3.7.5
No issues were encountered
> Logs successful MS MARCO passage retrieval

- docs/experiments-msmarco-passage.md
Replicated on student linux server
Ubuntu 18.04.4 LTS
Java version: 11.0.7
Maven 3.6.3
> Add replication log entry

- src/main/java/io/anserini/search/SimpleSearcher.java
> SimpleSearcher bug fix

- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/python/verify_simplesearcher.py
- src/test/java/io/anserini/search/SimpleSearcherTest.java
Added more code paths to test in `verify_simplesearcher.py`.
> Code to exercise more code paths in SimpleSearcher

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
**Environment:** 
macOS Catalina 10.15.4
**Issues:**
No issues were encountered.
**Replication results:**
> Add replication log for MS MARCO passage & doc

- .gitignore
- bin/build.sh
- bin/qbuild.sh
- collections/.gitkeep
- docs/experiments-cord19.md
- indexes/.gitkeep
- src/main/java/io/anserini/scratch/.gitkeep
+ More repo organization so that everything isn't just dumped at top level.
+ Checked in simple convenience scripts that I use in `bin/`
> Repo reorganization

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchMsmarco.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/java/io/anserini/search/SimpleTweetSearcher.java
+ Renamed some of the methods to be more consistent with other parts of Anserini, will need to propagate to Pyserini.
+ Added javadoc to all methods.
> SimpleSearcher refactoring

- docs/regressions-core17.md
- docs/regressions-core18.md
- docs/regressions-robust04.md
- src/main/resources/docgen/templates/core17.template
- src/main/resources/docgen/templates/core18.template
- src/main/resources/docgen/templates/robust04.template
Environment:
macOS Catalina/ Ubuntu Virtual Machine
Java 11.0.7
Python 3.8
> replicaion on core17/18/robust04

- docs/regressions-core17.md
- docs/regressions-core18.md
- docs/regressions-robust04.md
- src/main/resources/docgen/templates/core17.template
- src/main/resources/docgen/templates/core18.template
- src/main/resources/docgen/templates/robust04.template
- macOS Mojave Version 10.14.6
- Python 3.7.2
- Java OpenJDK 11.0.2 2019-01-15
> Replication of robust04, core17 & core18

- docs/experiments-cord19.md
Prebuilt indexes, instructions, etc.
> Update for CORD-19 data drop of 5/19

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Replication Status:
Success (No issues)
Environment:
OS: Ubuntu-18.04.1
Java: 11.0.7
Maven: 3.6.0
Results:
MARCO-passage:
MARCO-doc:
> Update MS MARCO doc and passage experiment docs for repo reorganization

- pom.xml
I shouldn't hog all the credit...
> Credit to... Anserini Gaggle

- src/main/java/io/anserini/search/SearchArgs.java
> Remove SPL from the forbids list for SPL

- docs/experiments-cord19.md
> Index for TREC-COVID Round 4

- src/main/python/trec-covid/download_indexes.py
I'm using this as a building block for round 4 baseline runs.
> Add script to download pre-built CORD-19 indexes given a date

- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
+ Added more MD5 checksums
+ Switched over to using fusion modules in pyserini instead of trectools
I think I'm done futzing with the regressions for now. The seem pretty clean to me...
> Refactor TREC-COVID round 3 and round 4 baselines

- docs/experiments-covid.md
- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/download_indexes.py
- src/main/python/trec-covid/generate_round5_baselines.py
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Also added Java bindings.
Can someone take a look and actually run the commands? Thanks!
> Add TREC COVID round 5 baselines

- docs/experiments-cord19-extras.md
OS:
macOS Catalina Version 10.15.5
Java:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
Python:
Python 3.7.4
Ruby:
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c)
Rails:
Rails 6.0.2.2
No issues encountered.
> Replicated cord19 Solr and Elastic Search results.

- README.md
- docs/experiments-cord19-extras.md
- docs/experiments-covid-doc2query.md
- src/main/python/trec-covid/download_doc2query_indexes.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
Run links need to be updated but the rest should be fine for now!
> doc2query baselines for round4/round5

- docs/experiments-covid.md
https://github.com/castorini/anserini/pull/1336
> Fixed docs: TREC-COVID Round 5 baselines, used wrong qrels

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment
OS:
Ubuntu 20.04 LTS
Java:
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
Python:
Python 3.7.6
I encountered a minor issue while running the experimentation. I described it in #1359 
Other than that, everything was smooth. I was able to produce identical results as described in the document :100: 
msmarco-passage
msmarco-doc
Default parameter
Tuned parameter
I'm interested in the data engineering/system building aspect of your research. I'll continue to work on the replication of Solrini and Elastirini before signing up for a task.
> Appends on MSMarco Replication Log by @tangsaidi

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Replication is successful.
Environment:
OS: Ubuntu-18.04.4 LTS
Java: 11.0.8
Maven: 3.6.3
results are shown below:
- MS MARCO Passage
- MS MARCO Doc
> Replication for MS MARCO Passage and Doc

- src/main/java/io/anserini/search/SearchCollection.java
- src/main/python/epidemic-qa/print_run.py
- src/main/resources/topics-and-qrels/topics.epidemic-qa.consumer.primary.json
- src/main/resources/topics-and-qrels/topics.epidemic-qa.expert.primary.json
Also fixes a nit in SearchCollection where Exceptions thrown by QueryGenerator::BuildQuery were logged as being thrown due to inability to load the query generator.
Output: https://gist.github.com/justinborromeo/000bf8b2bcd37f9454c5abc4c3d5fe9e
> Add pretty-printer script for Epidemic QA

- docs/experiments-doc2query.md
I've rerun all experiments from scratch and confirmed that everything's working.
> Add to replication log: experiments-doc2query.md

- docs/experiments-covid.md
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
- src/main/python/trec-covid/index_cord19.py
- src/test/java/io/anserini/integration/TrecEndToEndPassageTest.java
> Renamed -selectMaxSegment to -selectMaxPassage

- src/test/java/io/anserini/ltr/BigramFeaturesTest.java
fix issue #1410 by explicitly adding Integer Type
> add type to fix raw member warning

- docs/regressions-cw09b.md
- docs/regressions-cw12.md
- docs/regressions-cw12b13.md
see #1416 - changes to path need to be propagated to rest of documentation.
> Tweak path to gdeval

- src/main/python/trec-covid/download_indexes.py
I reorganized files in my Dropbox. Fixing links.
> Fix Dropbox link

- src/main/resources/fine_tuning/collections.yaml
Haven't run these regressions in a while... fixed path to eval tools.
> Fixed paths to eval tools for fine-tuning experiments

- src/main/python/fever/generate_queries_and_qrels.py
Also removed the labels file param because it ended up not being needed.
> Fixed bug in fever/generate_queries_and_qrels.py

- src/main/java/io/anserini/search/SearchCollection.java
> Added comment about tie-breaking rules for documents with the same score

- docs/experiments-msmarco-doc-leaderboard.md
get exactly same result to the document
> add replicate log to experiments-msmarco-doc-leaderboard

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
I realized that we hadn't updated this documentation since the doc leaderboard became available. Updating accordingly.
> Updated documentation about MS MARCO doc

- docs/experiments-msmarco-doc-leaderboard.md
> Add MS MARCO doc per-passage condition

- docs/experiments-msmarco-doc-leaderboard.md
> replicate experiments-msmarco-doc-leaderboard

- docs/regressions-log.md
Documentation of regression change - fixes bug in reading of multi-line topics.
> Update regressions-log.md: documents #1482

- docs/regressions-dl20-passage-docTTTTTquery.md
- docs/regressions-dl20-passage.md
- src/main/java/io/anserini/eval/Qrels.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/main/resources/docgen/templates/dl20-passage-docTTTTTquery.template
- src/main/resources/docgen/templates/dl20-passage.template
- src/test/java/io/anserini/eval/RelevanceJudgmentsTest.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Also fixed typo on DL20 passage documentation.
> Added Qrels and Topics bindings for DL 20

- README.md
- docs/regressions-log.md
- docs/regressions.md
> Updated regression log for TREC 2020 News Track background linking task

- src/test/java/io/anserini/collection/DocumentCollectionTest.java
Closes #1504 - related to #1199
> Fixes non-deterministic bug in C4CollectionTest related to Locale

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Ran both experiments on MacOS. No problem occurred.
> MS MARCO doc/passage replication

- docs/regressions-dl19-doc.md
- docs/regressions-dl19-passage.md
- docs/regressions-dl20-doc-docTTTTTquery-per-doc.md
- docs/regressions-dl20-doc.md
- docs/regressions-dl20-passage-docTTTTTquery.md
- docs/regressions-dl20-passage.md
- src/main/resources/docgen/templates/dl19-doc.template
- src/main/resources/docgen/templates/dl19-passage.template
- src/main/resources/regression/dl19-doc.yaml
- src/main/resources/regression/dl19-passage.yaml
- src/test/java/io/anserini/doc/GenerateRegressionDocsTest.java
Closes https://github.com/castorini/anserini/issues/1525
@thibault-formal can you take a look?
> Fixed TREC DL 2019 regression issues

- src/test/java/io/anserini/integration/EndToEndTest.java
Test seems to fail sometimes... checking to see if this is a possible fix.
> Possible fix for flaky C4EndToEndTest

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment: Ubuntu 20.04 on Google Compute Engine (150GB SSD, 4 vCPUs, 16 GB memory)
No issues encountered and result as depicted in the given READMEs.
> MS MARCO experiment replication

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment: GCP e2-standard-2, Ubuntu 20.04, 2 vCPUs, 8GB memory, 150GB SSD.
All results match the given READMEs.
> MS MARCO doc and passage experiment replication

- docs/experiments-fever.md
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/python/fever/evaluate_doc_retrieval.py
- src/main/python/fever/generate_queries_and_qrels.py
- src/main/python/fever/tune_bm25.py
Updated FEVER experiment documentation to use `SearchCollection` accordingly.
> Changed SearchCollection output writer to UTF-8 encoding and updated FEVER experiments

- docs/experiments-fever.md
> Added reproduction log: experiments-fever.md

- docs/regressions-log.md
- docs/regressions.md
- src/main/java/io/anserini/collection/JsonCollection.java
- src/test/java/io/anserini/integration/EndToEndTest.java
- src/test/java/io/anserini/integration/JsonVectorEndToEndTest.java
+ Updated regression docs to record overhaul of regressions for MS MARCO {passage, doc} and DL {19, 20}.
+ Turned back on assert in e2e unit test that was previously commented out accidentally.
> Updated regression log, fixed unit tests

- docs/experiments-msmarco-passage-deepimpact.md
MRR @10: 0.3252764133351524
get exactly same number as the document
> reproduce deepimpact

- docs/experiments-msmarco-passage-deepimpact.md
Replicated successfully:
MRR @10: 0.3252764133351524
> Update DeepImpact reproducibility

- src/main/python/fusion.py
max_docs parameter in perform_fusion() was set as 10000, fixed it to use the correct variable
> Update max_docs in perform_fusion()

- docs/experiments-msmarco-passage-deepimpact.md
- docs/experiments-msmarco-passage-unicoil.md
+  added links to Pyserini
+ changed DI paper link to published SIGIR version
> Minor tweaks to DeepImpact and uniCOIL docs

- README.md
- docs/experiments-msmarco-passage-unicoil-tilde-expansion.md
Hi, 
I've created the anserini unicoil-tilde-expansion instruction.
just need to add the MD5 checksum for the pre-processed query file.
Cheers
> Add unicoil-tilde-expansion readme

- docs/approximate-nearestneighbor.md
Environment: GCP e2-standard-4, Ubuntu 20.04, 4 vCPUs, 16GB memory, 150GB SSD.
All results match the document.
> Reproduced results for approximated-nearest-neighbor.

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Results matched replication document. 
Python version: Python 3.9.2
OS: Ubuntu 20.04.3 LTS
> Update replication log for MS MARCO passage/doc ranking

- docs/regressions-robust04.md
- src/main/resources/docgen/templates/robust04.template
This fixes a dead link to the Robus04 TREC disks
> [Minor Fix] Fix dead link to data disks 4 and 5

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
This is the same PR from Lingwei.
Sorry for starting a new PR; I spent some time to fix git issues.
Here's the environment:
MacOS BigSur version 11.6 (20G165)
MacBook Pro (16-inch, 2019)
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 16 GB 2667 MHz DDR4
> Reproduction/Lingwei revised PR

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
@lintool Please review. I have reproduced the experiments.
> Append to MS MARCO reproduction logs

- docs/elastirini.md
I succeeded, although it wasn’t much that I did. I only deleted the schema `(curl -X DELETE 'http://localhost:9200/msmarco-doc'`), restarted Elastic Search, and started from the very beginning.
> Append to Elastirini reproduction log

- docs/experiments-msmarco-doc.md
Reproduced on Ubuntu 20.04 using WSL2 on windows 10, no problems
> Reproduction of MS-MARCO document ranking experiments

- docs/elk-hydrosheds.md
Updated with more detail and included Grand River example.
> Added Geosearch docs

- docs/regressions-log.md
More uniCOIL regressions for MS MARCO V1
> Update regression log

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
System information: Apple M1 Silicon chip, 16GB RAM, JDK-17 (compatible with M1) / Java 17.0.2
Notes: No issues in build, and able to replicate all results with reference times same as given in the experiment description.
> MS MARCO reproduction tasks

- docs/regressions-dl19-doc-segmented-unicoil.md
- docs/regressions-dl19-passage-unicoil.md
- src/main/resources/docgen/templates/dl19-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/dl19-passage-unicoil.template
System information: Apple M1 Silicon Chip, 16GB RAM, Java 17.0.2
No issues encountered, able to reproduce all values given in the instructions.
Reference issues: #1762
> uniCOIL regressions replication on DL 19

- docs/regressions-msmarco-passage-distill-splade-max.md
- src/main/resources/docgen/templates/msmarco-passage-distill-splade-max.template
reproduction of distilsplade-max on MS MARCO passage ranking task
> msmarco-distilsplade-max repro

- docs/regressions-msmarco-doc-docTTTTTquery.md
- docs/regressions-msmarco-doc-segmented-docTTTTTquery.md
- docs/regressions-msmarco-doc-segmented-unicoil-noexp.md
- docs/regressions-msmarco-doc-segmented-unicoil.md
- docs/regressions-msmarco-doc-segmented.md
- docs/regressions-msmarco-doc.md
- docs/regressions-msmarco-passage-deepimpact.md
- docs/regressions-msmarco-passage-distill-splade-max.md
- docs/regressions-msmarco-passage-doc2query.md
- docs/regressions-msmarco-passage-docTTTTTquery.md
- docs/regressions-msmarco-passage-unicoil-noexp.md
- docs/regressions-msmarco-passage-unicoil-tilde-expansion.md
- docs/regressions-msmarco-passage-unicoil.md
- docs/regressions-msmarco-passage.md
- src/main/resources/regression/msmarco-doc-docTTTTTquery.yaml
- src/main/resources/regression/msmarco-doc-segmented-docTTTTTquery.yaml
- src/main/resources/regression/msmarco-doc-segmented-unicoil-noexp.yaml
- src/main/resources/regression/msmarco-doc-segmented-unicoil.yaml
- src/main/resources/regression/msmarco-doc-segmented.yaml
- src/main/resources/regression/msmarco-doc.yaml
- src/main/resources/regression/msmarco-passage-deepimpact.yaml
- src/main/resources/regression/msmarco-passage-distill-splade-max.yaml
- src/main/resources/regression/msmarco-passage-doc2query.yaml
- src/main/resources/regression/msmarco-passage-docTTTTTquery.yaml
- src/main/resources/regression/msmarco-passage-unicoil-noexp.yaml
- src/main/resources/regression/msmarco-passage-unicoil-tilde-expansion.yaml
- src/main/resources/regression/msmarco-passage-unicoil.yaml
- src/main/resources/regression/msmarco-passage.yaml
Closes #1790 
Per @MXueguang 's suggestion - for MS MARCO V1, I refactored all regression to use the same metrics, and added appropriate cutoffs for MRR.
> Add correct cutoffs when computing MRR for MS MARCO V1

- pom.xml
> Upgrade jar for CAR

- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/download_doc2query_indexes.py
- src/main/python/trec-covid/download_indexes.py
- src/main/python/trec-covid/generate_round1_baselines.py
- src/main/python/trec-covid/generate_round2_baselines.py
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
+ Change URLs from dropbox to gitlab
+ Organize imports
+ Minor changes in scores
> Refactor TREC-COVID tests

- docs/elastirini.md
- docs/experiments-cord19-extras.md
- docs/solrini.md
- src/main/python/run_es_regression.py
- src/main/python/run_solr_regression.py
Fix minor issues the broke since last update.
> Refactor Solr and Elasticsearch integration and tests

- README.md
- docs/regressions-msmarco-passage-splade-distil-cocodenser-medium.md
- src/main/resources/docgen/templates/msmarco-passage-splade-distil-cocodenser-medium.template
- src/main/resources/regression/msmarco-passage-splade-distil-cocodenser-medium.yaml
Add MS Marco V1 passage ranking regression documents for #1815
> Add splade-distil-cocodenser-medium marco regression documents

- docs/regressions-disk45.md
- src/main/java/io/anserini/rerank/lib/Rm3Reranker.java
- src/main/java/io/anserini/rerank/lib/RocchioReranker.java
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/resources/regression/disk45.yaml
+ Simplify creation of original query vector
+ Add more detailed comments
+ Add heuristics for terms to include in doc vector, taken directly from RM3
> Refactor Rocchio implementation

- docs/regressions-beir-v1.0.0-arguana-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-climate-fever-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-dbpedia-entity-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-fever-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-fiqa-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-hotpotqa-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-nfcorpus-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-nq-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-quora-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-scidocs-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-scifact-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-trec-covid-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-webis-touche2020-splade-distil-cocodenser-medium.md
- src/main/resources/docgen/templates/beir-v1.0.0-arguana-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-climate-fever-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-dbpedia-entity-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-fever-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-fiqa-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-hotpotqa-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-nfcorpus-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-nq-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-quora-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-scidocs-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-scifact-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-trec-covid-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-webis-touche2020-splade-distil-cocodenser-medium.template
I renamed the base directories of the corpora, so the MD5 checksums changed.
> Upload BEIR corpora for splade-distil-cocodenser-medium

- README.md
- docs/regressions-beir-v1.0.0-arguana-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-climate-fever-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-dbpedia-entity-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-fever-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-fiqa-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-hotpotqa-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-nfcorpus-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-nq-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-quora-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-scidocs-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-scifact-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-trec-covid-splade-distil-cocodenser-medium.md
- docs/regressions-beir-v1.0.0-webis-touche2020-splade-distil-cocodenser-medium.md
- docs/regressions-msmarco-passage-splade-distil-cocodenser-medium.md
- src/main/resources/docgen/templates/beir-v1.0.0-arguana-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-climate-fever-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-dbpedia-entity-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-fever-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-fiqa-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-hotpotqa-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-nfcorpus-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-nq-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-quora-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-scidocs-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-scifact-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-trec-covid-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/beir-v1.0.0-webis-touche2020-splade-distil-cocodenser-medium.template
- src/main/resources/docgen/templates/msmarco-passage-splade-distil-cocodenser-medium.template
- src/main/resources/regression/msmarco-passage-splade-distil-cocodenser-medium.yaml
Minor tweaks on BEIR documentation.
> Refactor MS MARCO regression for splade-distil-cocodenser-medium

- docs/building-in_intelij.md
- docs/usage-intelij.md
These are basic instructions how to use InteliJ as the development environment
> Add instructions how to use InteliJ IDE to build and debug.

- README.md
- docs/regressions-beir-v1.0.0-fiqa-multifield.md
- src/main/resources/docgen/templates/beir-v1.0.0-fiqa-multifield.template
- src/main/resources/regression/beir-v1.0.0-fiqa-multifield.yaml
I added fiqa-multifield regression. Please check and let me know if it is good to merge!
Kind Regards,
Nandan Thakur
> add: fiqa multifield regressions from beir benchmark

- README.md
- docs/regressions-dl21-doc-segmented-unicoil-0shot-v2.md
- docs/regressions-dl21-doc-segmented-unicoil-0shot.md
- docs/regressions-dl21-doc-segmented-unicoil-noexp-0shot-v2.md
- docs/regressions-dl21-doc-segmented-unicoil-noexp-0shot.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-0shot-v2.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-0shot.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-noexp-0shot-v2.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-noexp-0shot.md
- src/main/resources/docgen/templates/dl21-doc-segmented-unicoil-0shot-v2.template
- src/main/resources/docgen/templates/dl21-doc-segmented-unicoil-0shot.template
- src/main/resources/docgen/templates/dl21-doc-segmented-unicoil-noexp-0shot-v2.template
- src/main/resources/docgen/templates/dl21-doc-segmented-unicoil-noexp-0shot.template
- src/main/resources/docgen/templates/msmarco-v2-doc-segmented-unicoil-0shot-v2.template
- src/main/resources/docgen/templates/msmarco-v2-doc-segmented-unicoil-0shot.template
- src/main/resources/docgen/templates/msmarco-v2-doc-segmented-unicoil-noexp-0shot-v2.template
- src/main/resources/docgen/templates/msmarco-v2-doc-segmented-unicoil-noexp-0shot.template
- src/main/resources/regression/dl21-doc-segmented-unicoil-0shot-v2.yaml
- src/main/resources/regression/dl21-doc-segmented-unicoil-noexp-0shot-v2.yaml
- src/main/resources/regression/msmarco-v2-doc-segmented-unicoil-0shot-v2.yaml
- src/main/resources/regression/msmarco-v2-doc-segmented-unicoil-noexp-0shot-v2.yaml
Encoding title/body this time.
> Add regressions for MS MARCO v2 doc segmented uniCOIL

- README.md
> Add note/link about Windows build errors

- pom.xml
- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleSearcher.java
Looking forward to using this with pyserini! 🤩
> Support Ukrainian and Polish analysers using lucene-analyzers-morfologik

- README.md
- docs/regressions-hc4-v1.0-fa.md
- docs/regressions-hc4-v1.0-ru.md
- docs/regressions-hc4-v1.0-zh.md
- src/main/resources/docgen/templates/hc4-v1.0-fa.template
- src/main/resources/docgen/templates/hc4-v1.0-ru.template
- src/main/resources/docgen/templates/hc4-v1.0-zh.template
Add corpus download section to documentation
> Update HC4 Regressions documentation

- README.md
- docs/regressions-log.md
- docs/regressions.md
- src/main/python/beir/gather_beir_results.py
```
% python src/main/python/beir/gather_beir_results.py 
nDCG@10                  flat    multi   UCx     SPLADE
------  ------  ------  ------
trec-covid               0.5947  0.6559  0.6403  0.7109
bioasq                   0.5225  0.4646  0.4771  0.5035
nfcorpus                 0.3218  0.3254  0.3325  0.3454
nq                       0.3055  0.3285  0.4249  0.5442
hotpotqa                 0.6330  0.6027  0.6671  0.6860
fiqa                     0.2361  0.2361  0.2888  0.3514
signal1m                 0.3304  0.3304  0.2750  0.2957
trec-news                0.3952  0.3977  0.3743  0.3936
robust04                 0.4070  0.4070  0.4030  0.4581
arguana                  0.3970  0.4142  0.3959  0.5210
webis-touche2020         0.4422  0.3673  0.2976  0.2435
cqadupstack-android      0.3801 …
```
> Update docs to add notes about BEIR uniCOIL and HC4 regressions

- src/main/python/mrtydi/gather_mrtydi_results.py
```
% python src/main/python/mrtydi/gather_mrtydi_results.py                
Train       MRR@100  R@100
----------- ------- ------
arabic       0.3356 0.7944
bengali      0.3566 0.8336
english      0.1592 0.5785
finnish      0.4101 0.8198
indonesian   0.2972 0.7948
japanese     0.2236 0.7282
korean       0.2596 0.6178
russian      0.2205 0.5706
swahili      0.2610 0.5903
telugu       0.2847 0.7049
thai         0.3543 0.8349
Dev         MRR@100  R@100
----------- ------- ------
arabic       0.3462 0.7872
bengali      0.3385 0.8432
english      0.1685 0.6196
finnish      0.4133 0.8285
indonesian   0.2937 0.7827
japanese     0.2241 0.7274
korean       0.2888 0.6733
russian      0.2152 0.5673
swahili      0.2693 0.5789
telugu       0.2737 0.7040
thai         0.3586 0.8536
Test        MRR@100 …
```
> Add simple script to gather Mr.TyDi regression results

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- Fresh WSL Ubuntu 20.04.4 on Windows 10
- Python 3.8.13
- Java 11.0.13
- Apache Maven 3.8.6
Able to reproduce results that appear on guide.
> Reproducing Results for Anserini

- src/main/java/io/anserini/search/SimpleSearcher.java
A fix to pr #1868 
@ToluClassics could you check if this fixes the issue?
> add farsi analyzer to simple seacher

- README.md
- docs/regressions-wikipedia-dpr-100w-bm25.md
- docs/regressions.md
- src/main/python/run_regression.py
- src/main/resources/docgen/templates/wikipedia-dpr-100w-bm25.template
- src/main/resources/regression/wikipedia-dpr-100w-bm25.yaml
- src/test/java/io/anserini/doc/DataModel.java
Deals with every point in https://github.com/castorini/anserini/issues/1928
> Improve wikipedia-dpr-100w regressions

- README.md
- docs/regressions-hc4-neuclir22-fa-en.md
- docs/regressions-hc4-neuclir22-fa.md
- docs/regressions-hc4-neuclir22-ru-en.md
- docs/regressions-hc4-neuclir22-ru.md
- docs/regressions-hc4-neuclir22-zh-en.md
- docs/regressions-hc4-neuclir22-zh.md
- docs/regressions-hc4-v1.0-fa.md
- docs/regressions-hc4-v1.0-ru.md
- docs/regressions-hc4-v1.0-zh.md
- src/main/resources/docgen/templates/hc4-neuclir22-fa-en.template
- src/main/resources/docgen/templates/hc4-neuclir22-fa.template
- src/main/resources/docgen/templates/hc4-neuclir22-ru-en.template
- src/main/resources/docgen/templates/hc4-neuclir22-ru.template
- src/main/resources/docgen/templates/hc4-neuclir22-zh-en.template
- src/main/resources/docgen/templates/hc4-v1.0-fa.template
- src/main/resources/docgen/templates/hc4-v1.0-ru.template
- src/main/resources/docgen/templates/hc4-v1.0-zh.template
- src/main/resources/regression/hc4-neuclir22-fa-en.yaml
- src/main/resources/regression/hc4-neuclir22-ru-en.yaml
- src/main/resources/regression/hc4-neuclir22-zh-en.yaml
minor clarification to doc of other HC4 regressions
> Add HC4 NeuCLIR22 doc translation baselines

- docs/regressions-log.md
- docs/regressions.md
Both query and doc translation directions.
> Add regressions for HC4 test topics on NeuCLIR22 corpora

- docs/experiments-msmarco-passage.md
everything looks good and easy to follow
> result reproduced (p40 server)

- docs/experiments-msmarco-passage.md
URA initial screening.
Environment: Linux (UWaterloo cs student remote environment)
> update reproduction log

- docs/regressions-msmarco-v2-doc-segmented-unicoil-0shot-v2.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-0shot.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-noexp-0shot-v2.md
- docs/regressions-msmarco-v2-doc-segmented-unicoil-noexp-0shot.md
- docs/regressions-msmarco-v2-passage-unicoil-0shot.md
- docs/regressions-msmarco-v2-passage-unicoil-noexp-0shot.md
- src/main/resources/regression/msmarco-v2-doc-segmented-unicoil-0shot-v2.yaml
- src/main/resources/regression/msmarco-v2-doc-segmented-unicoil-0shot.yaml
- src/main/resources/regression/msmarco-v2-doc-segmented-unicoil-noexp-0shot-v2.yaml
- src/main/resources/regression/msmarco-v2-doc-segmented-unicoil-noexp-0shot.yaml
- src/main/resources/regression/msmarco-v2-passage-unicoil-0shot.yaml
- src/main/resources/regression/msmarco-v2-passage-unicoil-noexp-0shot.yaml
> Increase parallelism for slow regressions

- pom.xml
> Upgrade Jackson to address security vulnerability

- src/main/python/beir/build_beir_indexes.py
For generating Lucene 9 pre-built indexes.
> Tweak script to generate pre-built BEIR indexes

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Everything went on well and the experiments were reproduced.
Environment: MacBook Pro (2019), 32GB RAM and 500G SSD, MacOS 12.0.1, JAVA 11.0.9.1, Maven 3.8.6, Python 3.8.15.
> Update reproduction log.

- pom.xml
- src/main/java/io/anserini/index/IndexDenseVectors.java
Update Anserini to Lucene 9.4.2
> switch to Lucene 9.4.2

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Hardware:
M1 14inch macbook pro
Dev Environment:
JAVA 11.0.2, Maven 3.8.4, Python 3.8.
I was able to make, pass tests and reproduce the results.
> replication of results on m1 mac

- src/main/python/regressions-batch04.txt
- src/main/python/run_regression.py
+ Minor tweaks to order in which we're running regressions
+ Make use of tjena
> Tweak regression settings

- src/main/python/run_regression.py
+ reorder precedence of collection paths
+ better handling when path is not found
> Minor tweaks to regression framework

- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/index/SimpleIndexer.java
- src/test/java/io/anserini/index/SimpleIndexerAppendTest.java
- src/test/java/io/anserini/index/SimpleIndexerTest.java
+ Reuse ObjectMapper in JsonCollection.Document (substantially increases speed)
+ Add different methods for adding documents to index in SimpleIndexer
> Improve batch indexing implementation

- docs/regressions-wiki-all-6-3-tamber-bm25.md
- src/main/resources/docgen/templates/wiki-all-6-3-tamber-bm25.template
- src/main/resources/regression/wiki-all-6-3-tamber-bm25.yaml
Add QA regression experiments on the wiki-all-6-3-tamber corpus
> Add wiki-all-6-3 BM25 regressions

- docs/regressions-dl19-passage-splade-pp-ed.md
- docs/regressions-dl19-passage-splade-pp-sd.md
- docs/regressions-dl20-passage-splade-pp-ed.md
- docs/regressions-dl20-passage-splade-pp-sd.md
- docs/regressions-msmarco-passage-splade-pp-ed.md
- docs/regressions-msmarco-passage-splade-pp-sd.md
- src/main/resources/docgen/templates/dl19-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-sd.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-sd.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-sd.template
Add reproduction log for SPLADE++ (msm, dl19, dl20; passage retrieval tasks)
Results reproduced on NLE servers
> MS MARCO SPLADE++ regression reproduction

- src/main/java/io/anserini/collection/Cord19FullTextCollection.java
> Fix parsing error with Cord19FullTextCollection when encountering doc with no full text

- pom.xml
- src/main/python/run_regression.py
- src/main/resources/regression/msmarco-passage-cos-dpr-distil.yaml
This works:
```
python src/main/python/run_regression.py --index --verify --search --regression msmarco-passage-cos-dpr-distil
```
> Added regression for HNSW in Lucene using cos DPR distil

- docs/experiments-msmarco-passage.md
MacBook Pro M1 Chip, 16GB RAM, Monterey 12.4
Apache Maven 3.9.2, Java version: 20.0.1
Python 3.9.16 set up using PyEnv and virtualenv
No hiccups, easy to follow
> Reproduce Passage MS MARCO Passage Ranking

- docs/experiments-msmarco-doc.md
Macbook Pro M1 pro, 14 inch
OS name: "mac os x", version: "13.2.1", arch: "aarch64", family: "mac"
Java version: 17.0.7, vendor: Azul Systems, Inc.
Maven: apache-maven-3.9.2
Python: Python 3.10.9
> Reproduce success for Anserini: BM25

- docs/experiments-msmarco-passage.md
MacBook Pro Intel Chip, 16GB RAM, Monterey 12.6.3
Apache Maven 3.9.1, Java version: 20.0.1
Python 3.9.13
Problem: VSCode may bring unexpected changes to files, use vim
> Passage Reproduce

- docs/experiments-msmarco-doc.md
MacBook Pro M1 Chip, 16GB RAM, Ventura 13.3.1
Apache Maven 3.9.2, Java version: 20.0.1
Python 3.9.16 set up using PyEnv and virtualenv
> reproduce experiments-msmarco-doc

- src/main/resources/docgen/templates/dl19-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-sd.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-sd.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-sd.template
Environment:
- Server: ORCA
- System: Ubuntu 18.04.2 LTS
- Java: openjdk 11.0.13
- Python: 3.9.15
Results matched
> reproduce SPLADE++ with ONNX Runtime

- docs/regressions-dl19-passage-splade-pp-ed-onnx.md
- docs/regressions-dl19-passage-splade-pp-ed.md
- docs/regressions-dl19-passage-splade-pp-sd-onnx.md
- docs/regressions-dl19-passage-splade-pp-sd.md
- docs/regressions-dl20-passage-splade-pp-ed-onnx.md
- docs/regressions-dl20-passage-splade-pp-ed.md
- docs/regressions-dl20-passage-splade-pp-sd-onnx.md
- docs/regressions-dl20-passage-splade-pp-sd.md
- docs/regressions-msmarco-passage-splade-pp-ed-onnx.md
- docs/regressions-msmarco-passage-splade-pp-ed.md
- docs/regressions-msmarco-passage-splade-pp-sd-onnx.md
- docs/regressions-msmarco-passage-splade-pp-sd.md
> run bin/build to generate new MD files

- docs/regressions-dl19-passage-splade-pp-ed-onnx.md
- docs/regressions-dl19-passage-splade-pp-ed.md
- docs/regressions-dl19-passage-splade-pp-sd-onnx.md
- docs/regressions-dl19-passage-splade-pp-sd.md
- docs/regressions-dl20-passage-splade-pp-ed-onnx.md
- docs/regressions-dl20-passage-splade-pp-ed.md
- docs/regressions-dl20-passage-splade-pp-sd-onnx.md
- docs/regressions-dl20-passage-splade-pp-sd.md
- docs/regressions-msmarco-passage-splade-pp-ed-onnx.md
- docs/regressions-msmarco-passage-splade-pp-ed.md
- docs/regressions-msmarco-passage-splade-pp-sd-onnx.md
- docs/regressions-msmarco-passage-splade-pp-sd.md
- src/main/resources/docgen/templates/dl19-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-sd.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-sd.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-ed.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-sd.template
> fix readme dates

- docs/onnx-conversion.md
Add MD file for converting and optimizing SPLADE++ from HuggingFace to ONNX
Related to issue #2127
> Add ONNX model conversion docs

- docs/start-here.md
This cl:
- Adds instructions for cloning the repo if needed.
- Adds the command for `md5sum`
> Update start-here.md with clone and checksum instructions

- docs/experiments-msmarco-passage.md
- docs/start-here.md
This cl:
- Adds a build command for building Anserini
- Adds commands for extraction and building of trec_tool
- Adds Repro log for sahel-sh
> Update experiments-msmarco-passage.md with building commands

- docs/start-here.md
This cl removes the checksum command as requested in https://github.com/castorini/pyserini/pull/1577#discussion_r1271428678
> Update start-here.md by removing the checksum command

- docs/start-here.md
**OS**: Ubuntu 18.04 (WSL)
**Hardware**:
- Processor: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz
-  RAM: 32.0 GB
- System type: 64-bit operating system, x64-based processor
**Python**: Python 3.6.9
**Result**: I was able to replicate the MS MARCO Tour (i.e. download & extra the data, data munging and analyze qrels files) on my machine with the above settings. Outputs are the same as listed in the "start-here" document.
> Add an entry in the "Reproduction Log" for ugrad onboarding

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Environment:
ASUS X515
ubuntu 22.04
Successfully reproduced results on both Windows 11 using the prompted bug fixes (with cygwin etc.), as well as ubuntu 22.04 on a VM
> Reproducing "Start Here - Anserini"

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- docs/start-here.md
Environment:
Apple M1
JAVA version: 11.0.13 2021-10-19
Python version: 3.8.17
Maven version: 3.9.4
Everything worked fine and results were reproduced.
> Adds reproduction logs for onboarding docs

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- docs/reproducibility.md
- docs/reproduction-details.md
System environment: RAM 16, Ubuntu 22.04
Everything worked as expected in the start-here and other sections well except for when I tried to run this command "mvn clean package appassembler:assemble" it got stuck at a certain point.
And about the documentations, everything was great and clear, however as a suggestion the section about reproduction log is a little bit confusing compared to the other parts; if there were more details about what has been asked, it would be wonderful.
Best regards,
Erfan Parifard
> Added reproduction log entry

- docs/experiments-msmarco-passage.md
- docs/start-here.md
**Environment:**
OS: MacOS Ventura 13.5.1
Hardware: Apple M1 Pro
Java version: 17.0.2
Python version: 3.9.10
Maven version: 3.8.4
**Results:**
- Successfully reproduced [Tour of MS MACRO](https://github.com/castorini/anserini/blob/master/docs/start-here.md#a-tour-of-ms-marco)
- Successfully reproduced [Anserini: BM25 Baselines for MS MARCO Passage Ranking](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md)
> Add to reproduction logs for onboarding docs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
- start-here.md
- experiments-msmarco-passage.md
Environment:
Machine:  Google Colab (Ubuntu 22.04.2 LTS)
Processor:  x86_64
RAM: 12 GB
Python: 3.11.4
Python in Conda env: 3.8.18
Java: 11.0.20.1
Apache Maven: 3.6.3
Every result has been successfully reproducible and you can see them in this [notebook](https://github.com/MojTabaa4/castorini-onboarding-notebook).
> Add to onboarding reproduction logs

- src/main/resources/fine_tuning/collections.yaml
- src/main/resources/fine_tuning/models.yaml
These are from the "Neural Hype" paper all the way back from 2019.
> Fix broken paths and results in old fine-tuning experiments

- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
> update tools with dl19/20 queries encoded by cos-dpr

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Adding reproduction logs:
```
- start-here.md
- experiments-msmarco-passage.md
```
Environment:
```
Machine: Ubuntu 22.04.3 LTS (Memory: 12 GB DDR3, Processor: Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz)
Apache Maven: 3.9.4
Java version: 11.0.2
Python: 3.10.6
```
Everything worked properly and results has been successfully reproducible.
> Add record to onboarding reproduction logs by Melvin Mokhtari

- src/main/java/io/anserini/ltr/DocumentFieldContext.java
- src/main/java/io/anserini/rerank/ScoredDocuments.java
- src/main/java/io/anserini/rerank/lib/AxiomReranker.java
- src/main/java/io/anserini/rerank/lib/NewsBackgroundLinkingReranker.java
- src/main/java/io/anserini/rerank/lib/RocchioReranker.java
- src/main/java/io/anserini/search/EvaluateInvertedDenseVectors.java
- src/main/java/io/anserini/search/SearchInvertedDenseVectors.java
- src/main/java/io/anserini/search/SimpleNearestNeighborSearcher.java
- src/main/java/io/anserini/util/ExtractDocumentLengths.java
- src/test/java/io/anserini/index/BasicIndexOperationsTest.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
> Factor storedFields() and termVectors() out of loops where possible

- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
https://github.com/castorini/pyserini/pull/1696
> Add dense AToMiC 2CR topics

- docs/experiments-msmarco-passage.md
- docs/start-here.md
- Operating System: Linux
- OS Release: 5.15.120+
- Python Version: 3.10.12
- Apache Maven 3.6.3
- Openjdk version 11.0.20.1
Everything worked just fine, the results were the same as in the guides.
> Add Reproducibility logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Setup Details:
Operating System: [macOS 14 Sonoma]
Environment and Configuration: [Python 3.7, Git version: 2.24.3 Java 16.0.2]
Outcome: [Success, everything worked.]
> Update start-here.md and experiments-msmarco-passage.md

- docs/experiments-msmarco-passage.md
- docs/start-here.md
- Andy Lee (U of Waterloo CS Student) completed the Foundation of Retrieval onboarding tasks.
- Replication runs can be found here: [https://drive.google.com/drive/folders/145bQBxGUKtPqVrS0LObBsRlugtvpGe5A?usp=drive_link](https://drive.google.com/drive/folders/145bQBxGUKtPqVrS0LObBsRlugtvpGe5A?usp=drive_link)
- I did not run into any issues for Anserini.
**OS and Versions:**
- WSL2 Ubuntu on Windows 10.
- Java: openjdk version "11.0.20.1"
- Maven: Apache Maven 3.6.3
> Completed Onboarding Tasks - Andy Lee

- README.md
I updated the Windows Anserini build-related notes and formatted the new lines accordingly (currently formatting my answers for Pyserini as well).
> Andy Lee - Updated Anserini Windows Notes

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Run it on google colab and everything worked!
But I encountered an error while attempting to extract the .tar file on my Linux (Ubuntu) system. The error message displayed was as 
```
.tar.gz -C collections/msmarco-passage
collection.tsv
follows: gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
> add entries in the reproduction logs

- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Adding bindings and tests for CIRAL's monolingual dev topics.
> Add bindings and test for CIRAL's dev topics

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Everything worked accordingly.
- Operating System:
- WSL 2 on Windows 11
- Development Environment:
- Python 3.10.12
- Java 11.0.20.1 2023-08-24
- Hardware:
- Processor:  Intel Core i7-13650HX, 2.60 GHz
- RAM: 32 GB
- Storage: SSD Drive - NVMe Micron 2400
- GPU: NVIDIA GeForce RTX 4060
> Add reproduction logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
**Operating System**
macOS Ventura version 13.5
**Development Environment**
Python: Version 3.11.5
Java: Version 21.0.1
Apache Maven: Version 3.9.5
 
**Hardware**
RAM: 24 GB
Storage: 512GB SSD
Processor: Apple M2
**Execution result**
Everything worked, didn't experience too much trouble when reproducing the results. Some evaluation results are:
The documentation is straightforward to follow. I like the flow of the document and how the key points are explained.
> Add entry to reproduction log - Yifei

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Adding to reproduction logs after completing Anserini [start here](https://github.com/castorini/anserini/blob/master/docs/start-here.md) and [BM25 Baselines for MS MARCO Passage Ranking](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md).
Everything worked flawlessly. The only bump in the road was that the following command from  the [anserini-tools README.md](https://github.com/castorini/anserini-tools/tree/77b8e58afc461d56f951c77cd9d3650378e121dd) to make the trec_eval tool did not "make" properly.
```bash
cd eval && tar xvfz trec_eval.9.0.4.tar.gz && cd trec_eval.9.0.4 && make && cd ../..
```
I found the solution was to break the entire command into multiple smaller commands that I ran individually. (Not sure why that changes anything but just …
> Add to reproduction log for Areel Khan

- docs/experiments-msmarco-passage.md
- docs/start-here.md
> In the description of your pull request, please provide some details on your setup (e.g., operating system, environment and configuration, etc.).
- Model Name: MacBook Pro
- Model Identifier: Mac14,10
- Chip: Apple M2 Pro
- Total Number of Cores: 12 (8 performance and 4 efficiency)
- Memory: 16 GB
- System Firmware Version: 10151.1.1
- OS Loader Version: 10151.1.1
- openjdk 20.0.1 2023-04-18, OpenJDK Runtime Environment (build 20.0.1+9-29), OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
> In addition, also provide some indication of success (e.g., everything worked) or document issues you encountered.
- Didn't build because of test failure (https://github.com/castorini/anserini/issues/2282).
- After skipping tests, the results were all reproducible.
> If you think …
> append reproduction log

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Reproduced on Apple M2
8 GB RAM
macOS Sonoma 14.2.1
Python 3.9.6
maven 3.9.6
Java 21.0.1
> Add to Reproduction Logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Ryzen 5600X
32GB RAM
Arch with Kernel 5.15 (running on WSL2)
OpenJDK 11.0.22
Apache Maven 3.8.7
Had to use the ```-Dmaven.test.skip=true``` flag when building anserini.
> Added reproduction logs

- src/main/java/io/anserini/index/AbstractIndexer.java
- src/main/java/io/anserini/index/IndexInfo.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SearchHnswDenseVectors.java
- src/test/java/io/anserini/index/PrebuiltIndexTest.java
- src/test/java/io/anserini/search/SearchCollectionTest.java
- src/test/java/io/anserini/search/SearchHnswDenseVectorsTest.java
+ Update cos-DPR HNSW indexes (+quantized index)
+ Add BGE HNSW indexes (+quantized index)
+ Add ability to specify topic enum
> Update prebuilt dense indexes + add ability to specify topic enum

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Python 3.10.13
Java 11.0.22
Maven 14.2.1
MacOS Sonoma
M2
No issues
> Add to reproduction log

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Python 3.10.6, Java 11.0.21, Maven 3.9.6, wsl ubuntu, Windows11, Encountered issue using make command for compiling, and issue downloading ubuntu and mvn. Solved through reading discussion board and google
> Add Reproduction Log

- src/main/java/io/anserini/encoder/OnnxEncoder.java
- src/main/java/io/anserini/encoder/sparse/SpladePlusPlusEnsembleDistilEncoder.java
Thank you @cadurosar for pointing out the issue.
It turned out to be a max_len issue.
#2354
> Fix splade-pp-ed onnx regression test on arguana

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Used Hardware:
(Used Waterloo Student Teaching Host ubuntu2204-002.student.cs.uwaterloo.ca)
CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
RAM: 384GB
Environment:
Ubuntu 22.04.3 LTS
Python 3.10.12
Java 11.0.21
Apache Maven 3.6.3
Had many issues on my personal laptop, but non on student teaching host for anserini
> Updated onboarding documents

- src/main/python/analyze_regression_logs.py
- src/main/python/run_regression.py
Respond with "OK" if within 0.005; respond with "OK-ish" if within 0.01 (means, take a closer look to verify).
> Tweak tolerance for regression tests (again)

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Specs
- OS: Linux 8c65d670328a 3.10.0-1160.66.1.el7.x86_64
- Processor: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
- Graphics: NVIDIA UNIX x86_64 Kernel Module  515.48.07
- RAM: 64 GB
- CUDA: Version: 11.7
- Python Version: Python 3.10.14
- Java Version: openjdk 11.0.22
- Apache Maven 3.6.3
The doc was super-easy to follow and was verbose enough.
Was able to reproduced everything successfully!
> Add to onboarding reroduction logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
I completed the modules on macOS Monterey using Visual Studio Code. No issues were encountered during development.
> Completed Onboarding Path

- docs/reproduce/msmarco-v1-passage.html
- src/main/java/io/anserini/reproduce/RunMsMarco.java
- src/main/java/io/anserini/reproduce/msmarco-v1-passage.yaml
> Refactor regressions with prebuilt indexes following removal of appassembler-maven-plugin

- src/main/frontend/package.json
- src/main/frontend/yarn.lock
`postcss` to `8.4.31` or later
`zod` to `3.22.3` or later
`next` to `13.5.1` or later
> Upgrade postcss and zod to avoid security vulnerabilities

- docs/reproduce/msmarco-v1-passage.html
- src/main/java/io/anserini/reproduce/RunMsMarco.java
- src/main/resources/reproduce/msmarco-v1-passage.yaml
for issue #2427 
For `RunMsMarco.java`, rather than depending on `bin/run.sh` and `bin/trec_eval`, directly locate and run fatjar with Java
> Locate and run fatjar in RunMSMarco

- src/main/resources/reproduce/beir.yaml
Fixed the typo in bge-base-en-v1.5 Dp yaml, as mentioned in #2480.
> Fixed BEIR regression typo

- README.md
- docs/fatjar-regressions/fatjar-regressions-v0.36.1.md
- docs/fatjar-regressions/fatjar-regressions-v0.36.2-SNAPSHOT.md
- docs/release-notes/release-notes-v0.36.1.md
> Release notes for v0.36.1

- docs/experiments-msmarco-passage.md
- docs/start-here.md
OS: Ubuntu 20.04 on WSL2
Java: JDK 21
Maven: Maven 3.9.7
Python: Python 3.10
Status:
I successfully followed the guide and reproduced the results easily. The concepts were familiar to me due to my background in information retrieval. Although I hadn't worked with Pyserini before, it was a great experience.
> Completed Foundations of Retrieval Onboarding Path

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Yiran Sun June 15th, 2024
Environment:
MacBook Pro, M2, 8GB RAM
Python 3.10.12
Java22
Everything works :)
> Add Reproduction Logs - Yiran Sun

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Reproduced the instructions from "start-here" doc.
- macOS Sonoma 14.5 (M2)
- Everything worked as expected
> Add Reproduction Log in start-here

- src/main/python/run_regression.py
> Tweak score tolerance for regressions

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Successfully reproduced start-here and experiments-msmarco-passage.
Setup details:
Model: MacBook Pro 
macOS: Sonoma 14.4.1
Chip: Apple M1
Memory: 8GB
> Add to onboarding logs

- docs/onnx-conversion.md
- src/main/python/onnx/convert_hf_model_to_onnx.py
- src/main/python/onnx/optimize_onnx_model.py
- updated documentation to include vocab.txt generation
- fixed naming scheme for optimized onnx models.
> update onnx docs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
setup
Computer: M1 MacBook Pro 14 inch
OS: Mac OS 13.0
Config: VSCode
status
Success: Everything worked
> recreated results in start here and experiment-msmarco-passage in doc

- README.md
- docs/fatjar-regressions/fatjar-regressions-v0.37.0.md
- docs/release-notes/release-notes-v0.37.0.md
- docs/rest-api.md
> Release notes for v0.37.0

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Software: Ubuntu 22.04, Conda, JDK 21, Maven 3.9.9
Hardware: Dell g5 5587, core i7 8th gen, 16 GB RAM, 1050ti 4GB VRAM
It all worked but I had two errors on the first run:
1. `Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes` 
I had to remove the signature from `target/anserini-0.38.1-SNAPSHOT-fatjar.jar` file
2. The maximum memory allocation pool parameter `Xmx` was set to 64GB though it was mentioned in the docs that >8 GB is needed. Therefore, I had to set it to 8GB.
> Add Onboarding Logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Operating System: Windows 10 21H2
Python version: 24.2
Shell: PowerShell
The process has been successful, and all steps completed without any errors.
> Excuted Successfully

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Was able to get it working on MacOS (Sequoia 15.1.1), Java 21.0.5, and Maven 3.9.9. Thanks!
> Add to onboarding repro logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
I was able to successfully reproduce the results:
OS: Mac OS 14.2.1
Java version: openjdk 21.0.5 
Maven 3.9.9
All tests for Anserini passed when buiding, and no issues so far! Thanks!
> Onboarding: Successful Reproduction of Anserini: BM25 Baselines for MS MARCO Passage Ranking

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Hi! Thank you for your patience! It's my first time to use github for collaboration... so i have made some mistakes. I hope this won’t cause any inconvenience. And i will show the details below, if there are any other peoblems, plz let me know. Thanks again!
Begin my journey:
ECEUbnuntu (limitted storage)
Operating System: Ubuntu 20.04.6 LTS
Python Version : 3.8.10
Maven Version : 3.8.1
Memory: 125 GiB(only 8GB for ECE students)
Outcome: All steps completed successfully
Second project:
My window computer
Operating System: Windows 10 Home Chinese Version
Java Version: 21.0.4 2024-07-16 LTS
Apache Maven Version: 3.9.9
Python Version : 3.8.10
Outcome: All steps completed successfully
Issues Encountered:
2 problems - mvn clean package
1. Windows Virtual Memory Allocation Issue:
High memory …
> Onboarding: Successful Anserini Reproduction

- docs/experiments-msmarco-passage.md
- docs/start-here.md
System: Apple M1 Pro Macbook Pro
OS: MacOS 14.6.1
Python: 3.10
Java: OpenJDK 21.0.5
Maven: 3.9.9
Everything worked well.
> [Onboarding] Added to reproduction logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
System: Apple M1 Max Macbook Pro (16inch, 2021) 
OS: MacOS Monterey Version 12.2.1
Python: 3.10.16
Java: openjdk 21.0.5
Maven: 3.9.9
Everything worked great!
> Onboarding path: Anserini

- docs/experiments-msmarco-passage.md
- docs/start-here.md
System: Apple M2 Macbook Air
OS: MacOS Sequoia 15.1.1
Python: 3.12.0
Maven: 3.9.9
Java: openjdk 21.0.5
Everything went well.
> Onboarding add to reproduction logs

- README.md
- docs/experiments-msmarco-passage.md
- docs/start-here.md
- Device: Apple MacBook Pro (M1 Pro)
- OS: macOS Sequoia 15.0
- Python Version: 3.11.5
- Maven Version: 3.9.9
- Java Version: OpenJDK 21.0.5
- Everything worked smoothly without any issues or errors. All required steps were completed successfully.
> Append to onboarding reproduction logs

- docs/regressions/regressions-rag24-doc-segmented-test.md
- src/main/resources/regression/rag24-doc-segmented-test.yaml
Aligns the metrics with https://trec-rag.github.io/annoucements/umbrela-qrels/
> Aligns the metrics with trec website

- docs/experiments-msmarco-v2.1.md
Logs for those interested
https://gist.github.com/vincent-4/77baadc8b9ba4bcead39f1d494dd8cb0
https://gist.github.com/vincent-4/b56245b1b442be276db806470c579bd3
> (docs): update repro log

- docs/experiments-msmarco-v2.1.md
I'll get @ronakice or @UShivani3 to sign off on this so I can merge, but @b8zhong @vincent-4 please take a look.
> Add ONNX commands for MS MARCO V2.1 baselines

- src/main/java/io/anserini/server/SearchService.java
- src/test/java/io/anserini/server/ControllerTest.java
- src/test/java/io/anserini/server/SearchServiceTest.java
https://app.codecov.io/gh/castorini/anserini/commit/25b8f951b7d770c73fc358fd91e1953e51812fbe
Fixes tests of #2691 
- Refactor validation
- Fix tests
> Add additional test coverage to the HNSW localhost API

- src/main/java/io/anserini/server/SearchService.java
```
[INFO] Running io.anserini.server.ControllerTest
Index file already exists! Skip downloading.
Index folder already exists!
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.document.Document.get(String)" because the return value of "io.anserini.search.SimpleSearcher.doc(String)" is null
at io.anserini.server.SearchService.getDocument(SearchService.java:119)
at io.anserini.server.Controller.getDocument(Controller.java:74)
at io.anserini.server.ControllerTest.testDocumentRetrieval(ControllerTest.java:93)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at …
```
> Fix failure in test 

- docs/experiments-msmarco-passage.md
- docs/start-here.md
System: Macbook Air M1 2020
OS: macOS Ventura 13.7.2
Python: 3.11.11
Maven: 3.9.9
Java: openjdk 21.0.6
Everything worked pretty easily, no problems
> Reproduction Results

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Device: Apple MacBook Pro
OS: macOS Sequoia 15.1.1
Python Version: 3.12.9
Maven Version: 3.9.9
Java Version: 21.0.5
Ran into some issues with Python 3.13 so had to use 3.12 (for Pyserini).
> Complete onboarding

- docs/experiments-msmarco-passage.md
- docs/start-here.md
**Setup:**
- Operating System: macOS (M series chip)
- Python Version: 3.11
- Environment: Standard development setup with no issues encountered during testing.
**Outcome:**
- Everything worked as expected. No issues encountered during the process.
> Add log entry for onboarding

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
+ Did a pass tweaking existing lessons
+ Added a new lesson on dense retrieval
> Refactor onboarding docs

- src/test/java/io/anserini/encoder/ArcticEmbedLEncoderInferenceTest.java
- src/test/java/io/anserini/search/SearchFlatDenseVectorsTest.java
- src/test/java/io/anserini/search/SearchHnswDenseVectorsTest.java
Quick try to see if I can fix #2736
> Refactor tests

- docs/regressions-log.md
- docs/regressions.md
> Document removal of regressions that use the jsonl dense vector format

- src/main/java/io/anserini/util/PrebuiltIndexHandler.java
- src/test/java/io/anserini/index/PrebuiltIndexHandlerTest.java
Adds custom cache specified through environment variables or through java (do we even need the latter)?
Add a test for setting a custom dir. 
This shouldn't be breaking, although if you set the env variable and forget about it, well, that might be confusing, but 🤷 what can we do.
> Add custom cache directory

- src/test/java/io/anserini/server/ControllerTest.java
Change it to beir, MSMARCO isn't needed as said by #2739
> Change ControllerTest from MSMARCO v1 passge to BEIR

- src/test/java/io/anserini/encoder/BgeBaseEn15EncoderInference2Test.java
- src/test/java/io/anserini/encoder/BgeBaseEn15EncoderInferenceTest.java
Trying to fix the "Error: The operation was canceled." GitHub CI issue by breaking multiple tests into two?
> Fix flaky tests

- docs/regressions/regressions-dl19-passage.splade-v3.cached.md
- docs/regressions/regressions-dl20-passage.splade-v3.cached.md
- docs/regressions/regressions-msmarco-v1-passage.splade-v3.cached.md
- src/main/resources/docgen/templates/dl19-passage.splade-v3.cached.template
- src/main/resources/docgen/templates/dl20-passage.splade-v3.cached.template
- src/main/resources/docgen/templates/msmarco-v1-passage.splade-v3.cached.template
Repro msmarco-v1, dl19, and dl20
> Added to repro log

- README.md
- src/main/java/io/anserini/search/topicreader/Topics.java
+ Added more sample commands to README
+ Added more MS MARCO bindings in Topics
> Minor cleanup

- README.md
- docs/release-notes/release-notes-v1.0.0.md
🎉 Release to coincide with SIGIR 2025 paper
> Release notes for v1.0.0

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
**Set up:**
- Environment: Student Linux Environment (ubuntu2204-012.student.cs.uwaterloo.ca)
- Operating System: Ubuntu 22.04
- Python Version: 3.12
- Java Version: 21.0.3
**Result**
- All the results match the markdown
- Followed the guide + existing issues for CPU time limit 
- had to run `ulimit -f unlimited` to clone the repo
> Added to reproduction logs for onboarding

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Env
- OS: Linux
- RAM: 16 GB (10 GB allocated to WSL)
- Python:3.10
- Java: 21.0.6
Status
results match numbers in the guide (except for the size of the  msmarco-passage data)
> updated reproduction log

- docs/experiments-msmarco-v2.md
Fix https://github.com/castorini/anserini/issues/2771
> Update experiments-msmarco-v2.md to use newer command style

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Setup
- Macbook Pro M3
- 16GB RAM
- macOS Sonoma
- Java 21.0.7
> Update Reproduction Logs: start-here.md

- src/main/java/io/anserini/encoder/OnnxEncoder.java
- src/main/java/io/anserini/encoder/dense/ArcticEmbedLEncoder.java
- src/main/java/io/anserini/encoder/dense/BgeBaseEn15Encoder.java
- src/main/java/io/anserini/encoder/dense/CosDprDistilEncoder.java
- src/main/java/io/anserini/encoder/dense/DenseEncoder.java
- src/main/java/io/anserini/encoder/sparse/SparseEncoder.java
- src/main/java/io/anserini/encoder/sparse/SpladeEncoder.java
- src/main/java/io/anserini/encoder/sparse/SpladePlusPlusEnsembleDistilEncoder.java
- src/main/java/io/anserini/encoder/sparse/SpladePlusPlusSelfDistilEncoder.java
- src/main/java/io/anserini/encoder/sparse/SpladeV3Encoder.java
- src/main/java/io/anserini/encoder/sparse/UniCoilEncoder.java
- src/test/java/io/anserini/encoder/sparse/SpladeV3EncoderInferenceTest.java
Addresses #2793 . All ONNX models from Anserini's ```encoder``` folder have been uploaded to HuggingFace.
> Move all ONNX models to HuggingFace

- docs/onnx-conversion.md
- src/main/python/onnx/convert_hf_model_to_onnx.py
- src/main/python/onnx/optimize_onnx_model.py
- src/main/python/onnx/splade_to_onnx.py
Addresses #2819. The first parts of the doc are still viable so I mostly left them alone and added a section at the end for SPLADE.
> Add to ONNX conversion document for SPLADE

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Setup:
- CS student environment from a 2024 MacBook Air with M3 Chip
- macOS 14.3
- 16GB Memory
> Adding Reproduction Logs for Kevin Zhu

- docs/fatjar-regressions/fatjar-regressions-v1.1.0.md
- src/main/java/io/anserini/reproduce/RunRepro.java
Added better handling of cases when scores differ.
Additional minor tweaks.
> Tweak score tolerance in repro: add [OK*]

- docs/fatjar-regressions/fatjar-regressions-v1.1.0.md
> Add to doc for searching shards

- docs/fatjar-regressions/fatjar-regressions-v1.1.0.md
Follow up on #2864. Reduces number of threads used in doc.
> Update number of threads for sharded search in doc

- pom.xml
- src/main/java/io/anserini/rerank/GenerateRerankerRequests.java
Further cleanup related to #2872
> Clean up of pom.xml

- src/main/python/bright/filter_run.py
- src/main/python/bright/generate_yaml.py
- src/main/python/run_regression.py
- src/main/resources/regression/bright-aops.yaml
- src/main/resources/regression/bright-biology.yaml
- src/main/resources/regression/bright-earth-science.yaml
- src/main/resources/regression/bright-economics.yaml
- src/main/resources/regression/bright-leetcode.yaml
- src/main/resources/regression/bright-pony.yaml
- src/main/resources/regression/bright-psychology.yaml
- src/main/resources/regression/bright-robotics.yaml
- src/main/resources/regression/bright-stackoverflow.yaml
- src/main/resources/regression/bright-sustainable-living.yaml
- src/main/resources/regression/bright-theoremqa-questions.yaml
- src/main/resources/regression/bright-theoremqa-theorems.yaml
> Add BRIGHT BM25 regressions

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Everything worked successfully!!
- ***OS:***  macOS Ventura 15.5 (Build 24F74) on MacBook Pro  
- ***Java:*** OpenJDK 21.0.6
> Onboarding for Anserini - Reproduction Logs by @ed-ward-huang

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Completed begin your journey, as well as BM25 and dense retrieval for MS MARCO passage ranking in Anserini.
OS: Ubuntu 24.04.2 LTS
Python 3.12.3
java 21.0.3 2024-04-16 LTS
Apache Maven 3.8.7
- Had to upgrade to java 21
- Had to run `ulimit -f unlimited` to download one of the indexes for dense retrieval
Output is as expected.
> Add reproduction log for 2025-07-19

- docs/prebuilt-indexes.md
- src/test/java/io/anserini/doc/GeneratePrebuiltIndexesDocTest.java
> Update prebuilt-indexes.md 

- src/test/java/io/anserini/repro/RunBrightTest.java
> Add test for io.anserini.reproduce.RunBright

- README.md
> Change README example to SPLADE-v3

- README.md
- docs/regressions/regressions-bright-aops.md
- docs/regressions/regressions-bright-biology.md
- docs/regressions/regressions-bright-earth-science.md
- docs/regressions/regressions-bright-economics.md
- docs/regressions/regressions-bright-leetcode.md
- docs/regressions/regressions-bright-pony.md
- docs/regressions/regressions-bright-psychology.md
- docs/regressions/regressions-bright-robotics.md
- docs/regressions/regressions-bright-stackoverflow.md
- docs/regressions/regressions-bright-sustainable-living.md
- docs/regressions/regressions-bright-theoremqa-questions.md
- docs/regressions/regressions-bright-theoremqa-theorems.md
- src/main/python/bright/generate_doc_templates.py
- src/main/resources/docgen/templates/bright-aops.template
- src/main/resources/docgen/templates/bright-biology.template
- src/main/resources/docgen/templates/bright-earth-science.template
- src/main/resources/docgen/templates/bright-economics.template
- src/main/resources/docgen/templates/bright-leetcode.template
- src/main/resources/docgen/templates/bright-pony.template
- src/main/resources/docgen/templates/bright-psychology.template
- src/main/resources/docgen/templates/bright-robotics.template
- src/main/resources/docgen/templates/bright-stackoverflow.template
- src/main/resources/docgen/templates/bright-sustainable-living.template
- src/main/resources/docgen/templates/bright-theoremqa-questions.template
- src/main/resources/docgen/templates/bright-theoremqa-theorems.template
> Update BRIGHT corpus tarball stats

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
My Setup:
- Device: MacBook Air M3
- OS: macOS 13.5
- JDK: Temurin 11.0.27
- Maven: 3.9.9
I encountered no issues, all steps ran smoothly.
> Add reproduction log entry for 2025-08-24

- docs/fatjar-regressions/fatjar-regressions-v1.2.1.md
- docs/fatjar-regressions/fatjar-regressions-v1.2.2.md
- src/main/resources/reproduce/msmarco-v1-doc.yaml
- src/main/resources/reproduce/msmarco-v1-passage.yaml
- src/main/resources/reproduce/msmarco-v2-doc.yaml
- src/main/resources/reproduce/msmarco-v2-passage.yaml
- src/main/resources/reproduce/msmarco-v2.1-doc-segmented.yaml
Tweaked name of various conditions for consistency.
> Update fatjar regression doc for v1.2.2 and related minor tweaks

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
OS: macOS Sonoma 14.4 (Apple M3 Pro)
Hardware: MacBook Pro, 18GB RAM
Python: 3.13.1
Java: OpenJDK 21.0.8 (Homebrew)
Results:
All results were successfully reproduced.
> Add onboarding reproduction log entries

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Environment
- OS: Windows 11 (x64), Git Bash
- Machine: ASUS VivoBook X1504VA
- CPU: 13th Gen Intel Core i7
- RAM: 16 GB 
Results
- Everything worked
Issues encountered 
-wget is not available by default on Windows; I used curl instead
Suggestions
-Add Windows-friendly snippets alongside Linux commands
commit [`3112afd`](https://github.com/castorini/anserini/commit/3112afd2eff0997b8fe6a3ad7ead20cd8f81ec09)
> Onboarding: add reproduction log entries @shreyaadritabanik

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
Environment:
- OS: Windows 11 (x64), WSL
- Machine: Intel NUC11PHi7
- CPU: 11th Gen Intel Core i7
- RAM: 16 GB
Results:
- Everything worked
> Added to reproduction log

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
**Environment** 
-   OS: Ubuntu 22.04.5 LTS 
-   Python: 3.11.11 (conda) 
-   Java: OpenJDK 21.0.6 (conda-forge) 
-   Maven: 3.9.11 (conda-forge) 
**Results**
-   Everything worked: reproduced BM25 baseline and dense retrieval experiments.
> add Reproduction Log entry for Anserini onboarding
