castorini/anserini

- pom.xml
- src/main/java/io/anserini/DumpIndex/DumpIndex.java
- src/main/java/io/anserini/dumpindex/DumpIndexArgs.java
- src/main/java/io/anserini/dumpindex/README.md
- src/main/java/io/anserini/util/DumpIndex.java
The purpose:
1. Let the user print the index info more easily. This could be used if the user wants to see the stats of the index in order to confirm the correctness of indexing process, e.g. number of docs in the index.
2. Indri has dumpindex util which is convenient. People would be more willing to migrate to Anserini if we have the same util.
The stats include:
- index stats
- term counts
- document dump (find id, find name, print text, print vector)
> Add DumpIndex util to easily print index info

- src/main/java/io/anserini/document/Collection.java
- src/main/java/io/anserini/document/TrecTextRecord.java
- src/main/java/io/anserini/index/IndexWebCollection.java
@lintool 
The code is mixed with IndexWebCollection. I think we'd better separate them some time in the future. 
Tested with disk1-5 and AQUAINT
**NOTE**: For AQUAINT, we only have the uncompressed version. I think the original files are gzipped? In the code I have this support, can you try that? 
Index Stats:
- DISK12
documents:      741687
contentsCount(doc with contents):       741686
total terms (with or without stop word):    311265071 / 222530202
- DISK45 (the CR dir is ignored in the code)
documents:      528030
contentsCount(doc with contents):       528030
total terms (with or without stop word):    251357430 / 174540587
- AQUAINT
documents:      1031455
contentsCount(doc with contents):       1031326
total terms (with or without stop word):    446995583 / 320157232
> add support for indexing trectext collections (disk1-5 + AQUAINT)

- src/test/java/io/anserini/index/IndexerTest.java
I spent some time trying to understand the Lucene API for accessing index structures (e.g., postings lists). What I've learned is encoded in this test case, which should be helpful others that want to manipulate low-level Lucene data structures.
> Added example of how to access Lucene index structures

- pom.xml
- src/main/java/io/anserini/eval/BatchEval.java
- src/main/java/io/anserini/eval/Eval.java
- src/main/java/io/anserini/eval/EvalArgs.java
- src/main/java/io/anserini/eval/QueryJudgments.java
- src/main/java/io/anserini/eval/RankingResults.java
- src/main/java/io/anserini/eval/ResultDoc.java
- src/main/java/io/anserini/eval/metric/AvgPrecision.java
- src/main/java/io/anserini/eval/metric/MetricBase.java
- src/main/java/io/anserini/eval/metric/MetricFactory.java
- src/main/java/io/anserini/eval/metric/NDCG.java
- src/main/java/io/anserini/eval/metric/Precision.java
- src/main/java/io/anserini/eval/metric/RelCount.java
- src/main/java/io/anserini/eval/metric/RelRetCount.java
- src/main/java/io/anserini/eval/metric/RetCount.java
- src/test/java/io/anserini/eval/MetricsTest.java
- src/test/java/io/anserini/eval/RankingResultsTest.java
- add the `eval` module which evaluates the ranking list based on judgments.
- for now `map`, `precision`, `ndcg` are available.
- deal with ties the same way as `trec_eval`: first based on score then based on docno, both in descending order.
- got _exactly_ the same results with `trec_eval`, even for the padding format...see below the `diff`
- got the same results with `gdeval.pl` (`gdeval` prefers `.5f` print format while I use `.4f`)
> add Eval module

- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/index/IndexCollectionArgs.java
- src/main/java/io/anserini/index/generator/JsoupGenerator.java
- src/main/java/io/anserini/index/generator/LuceneDocumentGenerator.java
-storeTransformedDocs: store transformed document text (e.g., HTML cleaning)
-storeRawDocs: store raw document text
> Separate options to store raw docs and to store transformed docs

- README.md
- docs/experiments-core17.md
- src/main/java/io/anserini/collection/TrecCoreCollection.java
- src/main/java/io/anserini/document/TrecCoreDocument.java
- src/main/java/io/anserini/document/nyt/NYTCorpusDocument.java
- src/main/java/io/anserini/document/nyt/NYTCorpusDocumentParser.java
- indexer binding for TREC Core collection
- parsing NytCorpus documents (provided by the organizers and is Apache licensed)
The parsing code is _verbatim_ now and needs to be slightly modified. This is an initial PR, so that we can track back to the original files.
> Indexing Trec Core (#187)

- src/main/java/io/anserini/collection/CW09Collection.java
- src/main/java/io/anserini/collection/CW12Collection.java
- src/main/java/io/anserini/collection/Collection.java
- src/main/java/io/anserini/collection/Gov2Collection.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TrecCoreCollection.java
- src/main/java/io/anserini/collection/TrecwebCollection.java
- src/main/java/io/anserini/collection/TwitterCollection.java
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/main/java/io/anserini/document/SourceDocument.java
- src/main/java/io/anserini/document/TrecCoreDocument.java
- src/main/java/io/anserini/document/TrecDocument.java
- src/main/java/io/anserini/document/TwitterDocument.java
- src/main/java/io/anserini/document/WarcRecord.java
- src/main/java/io/anserini/document/WikipediaArticle.java
- src/main/java/io/anserini/eval/EvalArgs.java
- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/search/query/QaTopicReader.java
- src/main/java/io/anserini/search/query/TopicReader.java
- src/main/java/io/anserini/search/query/TrecTopicReader.java
- src/main/java/io/anserini/search/query/WebxmlTopicReader.java
- src/test/java/io/anserini/document/ClueWeb09WarcRecordTest.java
- src/test/java/io/anserini/document/ClueWeb12WarcRecordTest.java
- src/test/java/io/anserini/document/DocumentTest.java
- src/test/java/io/anserini/document/TrecDocumentTest.java
- src/test/java/io/anserini/document/TrecwebDocumentTest.java
- src/test/java/io/anserini/document/TwitterDocumentTest.java
- src/test/java/io/anserini/document/WikipediaArticleTest.java
- src/test/java/io/anserini/eval/MetricsTest.java
This PR mainly does two things:
1. Refactor `Collection` a bit so that adding new Collection class requires less effort. The primary change is to make a protected variable `dType` which of the type `D` so that we can keep the logic of `next()` in the abstract `Collection` class. The exceptions are CW09, CW12 and WikiAriticle which do not take `BufferReader` as the source of reading the next record. I manually test all types of collections and it works as expected.
```
public abstract class Collection<D extends SourceDocument> {
public abstract class FileSegment implements Iterator<D>, Closeable {
protected Path path;
protected BufferedReader bufferedReader;
protected boolean atEOF = false;
protected final int BUFFER_SIZE = 1 << 16; // 64K
protected D dType;
@Override
public boolean …
```
> Refactor Collection class a bit; Add Document tests

- src/test/java/io/anserini/index/IndexerTest.java
Now after build or test the project, two dirs `test-index1` and `test-index2` are remain undeleted. 
This PR tries to extend `LuceneTestCase` and use the util functions to automatically take care of tmp dir creation and deletion.
> fix simple index test

- src/main/java/io/anserini/collection/CW09Collection.java
- src/main/java/io/anserini/collection/CW12Collection.java
- src/main/java/io/anserini/collection/Collection.java
- src/main/java/io/anserini/collection/Gov2Collection.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TrecCoreCollection.java
- src/main/java/io/anserini/collection/TrecwebCollection.java
- src/main/java/io/anserini/collection/TwitterCollection.java
- src/main/java/io/anserini/collection/WarcCollection.java
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/main/java/io/anserini/collection/WtCollection.java
There is a bug that if a class inherits a child of `Collection` (e.g. TrecCollection) and changes the `FileSegment` of that class, then the implementing class needs to implement its own `createFileSegment` method. Otherwise the FileSegment instance from its father class will be returned and will be actually used when indexing. 
```
@Override
public Collection.FileSegment createFileSegment(Path p) throws IOException {    
return new FileSegment(p);
}
```
> Fix bug in TrecwebCollection; Other formatting fixes.

- docs/experiments-clueweb12.md
I remain pleasantly surprised that this actually works:
```
nohup sh target/appassembler/bin/IndexCollection -collection CW12Collection \
-input /tuna1/collections/web/ClueWeb12/ -generator JsoupGenerator \
-index lucene-index.cw12.pos+docvectors -threads 88 \
-storePositions -storeDocvectors \
>& log.cw12.pos+docvectors &
```
27 hours later on `tuna`, the result is a 2.4TB index capable of supporting RM3.
> Update for CW12 documentation

- docs/experiments-microblog.md
- src/main/java/io/anserini/index/IndexCollection.java
Testing result on Microblog 2013: 
**Timing** 
master: `01:00:07`
this PR: `02:47:12`
**Index Stats**
master: 
```
documents:             203162948
documents (non-empty): 203160281
unique terms:          122988939
total terms:           2099261924
```
this PR:
```
documents:             203145941
documents (non-empty): 203143274
unique terms:          122988939
total terms:           2099082542
```
> Add uniqueDocId option to IndexCollection as per #258

- src/main/java/io/anserini/index/IndexCollection.java
This is useful if we'd like to only add specific documents to the index, e.g. when reproducing my TREC2013 web track. 
Tested on CW12 and disk12 (with and without)
> Add whitelistDocids option to indexing

- docs/experiments-core17.md
- src/main/java/io/anserini/document/TrecCoreDocument.java
- src/main/java/io/anserini/document/nyt/NYTCorpusDocumentParser.java
- src/main/python/run_regression_core17.py
As per #234, the bug arises from two parts, one is when handling empty-body documents, and the other is due to a static variable shared across instances of `NYTCorpusDocumentParser` which should not be. Just two simple tweaks to fix the issue.
>  fixed non-determinism and errors when indexing NYT collection (#234)

- src/main/python/run_regression_clueweb09b.py
- src/main/python/run_regression_clueweb12-b13.py
- src/main/python/run_regression_clueweb12.py
- src/main/python/run_regression_disks12.py
- src/main/python/run_regression_gov2.py
- src/main/python/run_regression_robust04.py
- src/main/python/run_regression_robust05.py
- src/main/python/run_regression_tweets2011.py
- src/main/python/run_regression_tweets2013.py
- src/main/python/run_regression_wt10g.py
By default, this doesn't rebuild index:
```
nohup python src/main/python/run_regression_disks12.py >& log.disks12 &
```
Instead, it uses indexes from `/tuna1/scratch/`
To explicitly rebuild index, do:
```
nohup python src/main/python/run_regression_disks12.py --index >& log.disks12 &
```
> Add --index option to regression scripts to explicitly build index

- README.md
- pom.xml
This patch basically reverts commit 2c76f3c51ed57aaac24589e6b5ec19ad9c528e9c which breaks fatjar generation for pyjnius. 
Maven now by default builds the fatjar, but appassembler needs to be explicitly triggered. So the full Maven command is now back to: mvn clean package appassembler:assemble
> Patch to fix issue #300 - errors building fatjar for pyjnius

- src/main/java/io/anserini/rerank/lib/AxiomReranker.java
- src/main/java/io/anserini/search/SearchArgs.java
Add search option `-axiom.docids` to axiomatic reranking so that the algorithm can opt to read external docids from an input file. This will eliminate the need of searching and sorting all docids if we need deterministic reranking results and thus greatly improve the efficiency.
> Add search option `-axiom.docids` to axiomatic reranking

- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/similarity/F2LogSimilarity.java
The F2Log model at current adopted version Lucene 6.3 is slow and problematic and I plan to submit a PR to Lucene 7.x 
For now, let us just create a temporary solution mainly for TREC 2018. 
After we migrate Lucene 7.x we will be good to use native Lucene's implementation.
The model implemented in this PR is essentially from BM25. BM25 has some final methods which we need to override that's why I cannot directly subclass BM25. 
Please note that I do not include test cases since Lucene's `BaseSimilarityTestCase` is not available outside Lucene repo and I largely believe the implementation is correct.
> Add f2log ranking model

- src/main/java/io/anserini/rerank/lib/AxiomReranker.java
Fix the deterministic axiomatic reranking by building the docids cache using ID_LONG instead of ID_String for tweets collection
> A bug in axiomatic reranking 

- src/test/java/io/anserini/integration/IndexerTest.java
Kinda roundabout: but the way to compute the BM25 score is to issue a query with the exact docid and the term in question, and look at the retrieval score.
> Examples test case to print out BM25 weights for each document vector

- src/main/java/io/anserini/rerank/lib/AxiomReranker.java
Fix the deterministic axiomatic reranking by deterministically deciding the expansion terms; This is accomplished by first looking at the expansion scores and if there are multiple terms with the same reranking score we will sort them by the case-sensitive term string.
> Fix the deterministic axiomatic reranking 

- docs/regression-tuna.md
@lintool I forgot to mention this in your PR.
Deterministic Ax takes too long on CW12 so I didn't include it.
> Remove Ax from cw12 regression test instruction

- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/collection/WashingtonPostCollection.java
- src/test/java/io/anserini/collection/ClueWeb09DocumentTest.java
- src/test/java/io/anserini/collection/ClueWeb12DocumentTest.java
- src/test/java/io/anserini/collection/DocumentTest.java
- src/test/java/io/anserini/collection/JsonDocumentArrayTest.java
- src/test/java/io/anserini/collection/JsonDocumentObjectTest.java
- src/test/java/io/anserini/collection/JsonLineObjectTest.java
- src/test/java/io/anserini/collection/TrecDocumentTest.java
- src/test/java/io/anserini/collection/TrecwebDocumentTest.java
- src/test/java/io/anserini/collection/TweetDocumentTest.java
- src/test/java/io/anserini/collection/WashingtonPostDocumentTest.java
- src/test/java/io/anserini/collection/WikipediaArticleTest.java
There are 3 bugs found:
1) In helper function `createFile()` in `DocumentTest`, the buffered writer is never closed, resulting in `bufferedReader.ready()` is always `false`. Therefore all document unit tests will throw an exception and get caught silently.
2) In #352, I used the iterator in the wrong way in unit tests. Should have used the same way as our `IndexCollection` did...
3) WashingtonPostDocumentTest is broken due to some string manipulation removed from #380.
This PR has fixed these 3 bugs.
The iterator used in document unit tests needs further improvement and refactoring after #381 is addressed.
> Patch for #383: Fix document unit tests

- src/main/java/io/anserini/util/MapCollections.java
This exception handling was added as a workaround to catch the NoSuchElementExceptions thrown per Issue #381. That has been fixed in PR #399. Undoing the workaround.
Verified that there are no longer exceptions.
> Undo exception handling to workaround issue #381

- src/main/java/io/anserini/collection/WashingtonPostCollection.java
- src/main/java/io/anserini/index/generator/WapoGenerator.java
- src/test/java/io/anserini/collection/WashingtonPostDocumentTest.java
Please see #403 for details.
This PR adds the `WapoGenerator` where the actual contents are parsed.
Now the `WashingtonPostCollection` is mainly a Json adaptor and it sends the raw Json object to `WapoGenerator`.
> Refactor WashingtonPost Collection Indexing

- src/main/resources/regression/mb13.yaml
See issue #409 documenting MB13 regression failure. Source can be traced back to
6b19d373634d510e8ac5f5b26b1a3d5c321926e4
In MB13 there are duplicate documents: optimize flag forces segment merge to clean this up,
yielding different index stats.
Rerunning regression now as final confirmation.
> Fixed broken MB13 regression

- src/main/python/paragraph_indexing/README.md
- src/main/python/paragraph_indexing/paraseg.py
- src/main/python/paragraph_indexing/seg_core17.py
- src/main/python/paragraph_indexing/seg_robust04.py
- src/main/python/paragraph_indexing/utils.py
These codes provides paragraph segmentation on Robust04 and Core17 collections, by reading the raw documents stored in the document-level indexing files. Each document will be segmented into paragraphs and dumped in `json` format which meets the input format of [`JsonCollection`](https://github.com/Kytabyte/Anserini/blob/master/src/main/java/io/anserini/collection/JsonCollection.java). As such, one is able to build paragraph-level indexing afterwards. 
I designed a base class for all paragraph segmenter called `_ParaSegmenter` in `paraseg.py` and all concrete segmenters extends this base class.
The base class defines four basic functionalities that a segmenter should have:
1. how to identify the start of the main body (`_setup`)
2. how to identify the start of *a* paragraph …
> #358 paragraph segmentation scripts for Robust04 and Core17 collection in Python

- src/main/java/io/anserini/search/SearchCollection.java
- src/test/java/io/anserini/integration/MultiThreadingSearchTest.java
The bug was that the base ranking model are the same for all searching threads.
The fix being to pass the `IndexReader` to each search thread and let each thread creates its own `IndexSearcher`.
Integration tests were added.
> Fix the multi-threading search bug 

- docs/freebase.md
- src/main/java/io/anserini/kg/FreebaseNode.java
- src/main/java/io/anserini/kg/IndexFreebase.java
- src/test/java/io/anserini/kg/FreebaseNodeTest.java
Complete indexer, two options:
+ node as document or triple as document
+ index everything or only English literals
Details of the four conditions updated in docs.
Demo programs for searching coming up...
> Indexing Freebase update: keep only English literals

- src/main/java/io/anserini/index/IndexCollection.java
@r-clancy I think you missed this minor detail :)
> ConcurrentUpdateSolrClient should be using multiple threads to drain document queue

- README.md
- docs/runbook-ecir2019-axiomatic.md
Moved runbook into main `docs/` directory, following same organization as other documentation.
> Runbook for ECIR 2019 ax

- src/main/python/ccrf/rerank.py
This allows the output files to be named consistently, so that downstream scripts have an easier time processing.
cc/  @tiddler
> Minor tweak so ccrf output file are named consistently

- pom.xml
- src/main/java/io/anserini/index/IndexCollection.java
- Since we're dealing with a single index `CloudSolrClient` is thread-safe (and `ConcurrentUpdateSolrClient` always is), so remove the object pooling.
- When indexing `cw09b` to Solr on himrod, only about 24G of RAM was being used. 31G (so we can still take advantage of compressed pointers) should be more than enough. Will confirm on `tuna` once it's done being hammered.
@lintool
> Minor Improvements to Solr Indexing

- src/main/java/io/anserini/index/IndexCollection.java
Each `ConcurrentUpdateSolrClient` has an internal executor. When creating these clients, each client had their maximum thread count set to the overall thread count for Anserini. As each processing thread has their own `ConcurrentUpdateSolrClient`, this potentially meant `args.threads*args.threads` for the total amount of `ConcurrentUpdateSolrClient`s. Local experiments with `args.threads=40` resulted in exceptions being thrown due to this. This pull request makes the `ConcurrentUpdateSolrClient` maxThreads adjustable, with a default of 1.
Not related, exceptions from Solr document delivery using `ConcurrentUpdateSolrClient` were logged to some unknown log. This pull request redirects those to the `IndexCollection`-log, so that the pattern matches the Lucene code path.
> Solr threads and exceptions

- pom.xml
- src/main/java/io/anserini/index/IndexCollection.java
(Re-)add object pooling for SolrClients... it helped throughput quite a bit for `CloudSolrClient` even though it's thread-safe.
Also, buffer docs for the `ConcurrentUpdateSolrClient` as it's queue is for update requests (i.e., it buffers `add(SolrInputDocument)` calls until the queue size is reached then drains the queue concurrently).
> Buffer Documents for ConcurrentUpdateSolrClient

- src/main/java/io/anserini/index/IndexCollection.java
Dry runs (performing all work, except for creating an index) makes it easier to locate the hot parts in the process chain. E.g. testing with 39GB ClueWeb files and 20 Anserini threads gave the numbers
- lucene dry: 375 seconds
- Solr dry: 447 seconds
- Lucene: 1575 seconds
- Solr: 4688 seconds
This tells us, for this specific experiment, that 
- Generating Solr documents adds 20% base processing time
- Building the Lucene index takes more time than the Anserini analysis
- Building the Solr index takes 4241 seconds and building the Lucene index takes 1200 seconds, which means that Solr takes 3.5 times as long as Lucene (as opposed to only 3 times, when ignoring the dry run numbers) to do the same job
Note: I have not investigated why Solr was so slow for this experiment. It was just a test …
> Dry run option

- src/main/resources/docgen/templates/cw12b13.template
Hi,
I tried to replicate the results on Cluweb12-B13 with the latest version of Anserini.
Most algorithms are OK, but I found that AX-related algorithms have a bit regression:
For example, 
QL+AX
NDCG@20| My Result  | Expected |
| ------------- | ------------- | ------------- |
201-250| 0.09833  | 0.1143  |
251-300| 0.08103  | 0.1001  |
ERR@20 | My Result  | Expected |
| ------------- | ------------- | ------------- |
201-250| 0.09833  | 0.0780  |
251-300| 0.09256  | 0.0896  |
BM25+AX
NDCG@20| My Result  | Expected |
| ------------- | ------------- | ------------- |
201-250| 0.11381  | 0.1287  |
251-300| 0.08010  | 0.0964  |
ERR@20 | My Result  | Expected |
| ------------- | ------------- | ------------- |
201-250| 0.09256  | 0.0780  |
251-300| 0.07969  | 0.0929  |
The others (QL, QL+RM3, …
> add replication note on Cluweb12-B13

- src/main/java/io/anserini/index/generator/WapoGenerator.java
When using `-storeTransformedDocs`, the `contents` field had some malformed text (title wrapped with `Optional[]` and kicker) - the content should be the body text of the document.
> Only store paragraph text in content field

- src/main/java/io/anserini/index/IndexCollection.java
Some fields that were present in Lucene docs, such as `published_date` for WaPo, weren't being indexed since it's a `long` instead of a `String` - this change includes those fields in the Solr index.
> Index numeric values in Solr

- src/main/java/io/anserini/search/SearchCollection.java
- src/test/java/io/anserini/collection/DocumentTest.java
- src/test/java/io/anserini/integration/IndexerTest.java
- src/test/java/io/anserini/integration/MultiThreadingSearchTest.java
Added some changes so that all test cases can pass on Windows.
Fix [#617](https://github.com/castorini/anserini/issues/617) - replaced `:` with `=` in `SearchCollection`'s `outputPath` for filename issues. 
Fix [#619](https://github.com/castorini/anserini/issues/619) - added garbage collection calls to some test cases as a workaround to Windows file deletion issue.
> Tweaks for Windows compatibility

- src/main/java/io/anserini/search/SearchCollection.java
In PR [#620](https://github.com/castorini/anserini/pull/620) I replaced `:` with `=` in `SearchCollection` at the file writer. 
https://github.com/castorini/anserini/blob/70bf6022c06948f642009f657094a54fd52790cf/src/main/java/io/anserini/search/SearchCollection.java#L137
This might cause issues when the following code checks for whether file already exists. 
https://github.com/castorini/anserini/blob/70bf6022c06948f642009f657094a54fd52790cf/src/main/java/io/anserini/search/SearchCollection.java#L323-L326
Submitting a fix to replace the character during construction of similarity tags instead.
> Fix tweaks for Windows compatibility

- docs/solrini.md
- src/main/java/io/anserini/index/IndexCollection.java
https://github.com/castorini/anserini/pull/600 added a script that setup a single-node SolrCloud instance for Solr indexing - this PR removes support for the non-cloud version in favor a simpler code path.
I originally thought it may hurt performance, but initial tests on `core17` and `gov2` show equal or slightly better performance than the old, more complex `ConcurrentUpdateSolrClient` code.
> Force SolrCloud and remove ConcurrentUpdateSolrClient.

- docs/experiments-msmarco.md
- src/main/python/msmarco/retrieve.py
Two main differences:
- previously, we were kinda cheating because we were training on the dev set. Now we've switched over to training on (samples of the) training set.
- previously, we were tuning on MRR; we've switched over to tuning on Recall@1000.
> MS MARCO fair tuning based on sampled training examples

- docs/experiments-msmarco.md
Just to check - I get a different checksum for `collectionandqueries.tar.gz` but end up with the same baseline results.
> Checksum Change

- docs/experiments-msmarco.md
- src/main/python/msmarco/retrieve.py
- src/main/python/msmarco/tune_bm25.py
This PR fixes #632
As it turns out, two bugs cancel each other out. I transposed the variables in two different places, so the result of the tuning remains the same.
Added effectiveness numbers from default and tuned parameters for future reference.
> Bug fig MS MARCO bug: b1 and k transposed

- src/main/python/msmarco/tune_rm3.py
Results by running `nohup python src/main/python/msmarco/tune_rm3.py --base_directory output --index msmarco_data/lucene-index-msmarco --queries msmarco_data/queries.dev.small.tsv --qrels msmarco_data/qrels.dev.small.tsv &> tune_rm3_results.log &`:
Best parameters: run.bm25.k1_0.82.b_0.72.rm3.fbDocs_5.fbTerms_50.originalQueryWeight_0.5.txt: R@1000 = 0.877, MRR@10 = 0.17858029744849255, MAP = 0.1874
@lintool Could you take a look at this PR?
> add tune code of RM3 on MS MARCO dataset

- README.md
Document Expansion by Query Prediction link previously led to Simple Applications of BERT for Ad Hoc Document Retrieval
> Fixing Document Expansion by Query Prediction link

- README.md
- docs/experiments-doc2query.md
- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- docs/regressions-msmarco-doc.md
- docs/regressions-msmarco-passage-doc2query.md
- src/main/resources/docgen/templates/msmarco-doc.template
- src/main/resources/docgen/templates/msmarco-passage-doc2query.template
- src/main/resources/regression/msmarco-doc.yaml
+ Moved Doc2query documentation (on passages) into its own dedicated page.
+ Added documentation and regression on BM25 tuning for the MS MARCO document ranking task.
> Updated MS MARC documentation + regressions (BM25 Tuning for doc)

- src/main/python/compare_runs.py
- src/main/python/msmarco_compare.py
@lintool Could you take a look at this PR?
The input of MSMARCO prediction is in a different format compared to other TREC run file:
<QID> <DOCID> <RANK>
The qrels file format is the same.
> add support of compare-run for MSMARCO predictions

- docs/solrini.md
- pom.xml
- src/main/java/io/anserini/rerank/ScoredDocuments.java
- src/main/java/io/anserini/search/SearchSolrCollection.java
- src/main/resources/solr/anserini-twitter/conf/managed-schema
- src/main/resources/solr/anserini/conf/managed-schema
In this PR:
- Adapted relevant code from `SearchCollection` into `SearchSolrCollection` for Solrini BM25 retrieval
- Updated analyzers in Solr schema to reconcile score differences
- Verified that retrieval results match with Anserini BM25 regressions for `robust04` and `mb11` collections
- Updated solrini documentation
This update extends search functionality per #718, minus the abstraction/refactoring. Solrini retrieval in this setup supports a subset of `SearchCollection` functionalities, and is not yet compatible with rerankers other than the default `ScoreTiesAdjusterReranker`. The main goal here was to replicate Anserini retrieval results in Solr without breaking the current `SearchCollection`.
> Added Solrini search functionality over collections

- src/main/python/openresearch/convert_openresearch_to_anserini_format.py
The filtering steps are:
1. Remove all papers without a year of publication. The corpus will be created from the output from this step.
2. Sort papers by year and use the oldest 80% for training, the middle 10% for dev, and the more recent 10% for test.
3. For training, dev, and test splits remove all self-citations, citations whose publication year is later than that of the citing paper, and cited papers that are not in the corpus.
4. From the output of step 3, remove all papers that do not cite any other paper.
> Matches the same filtering steps from Bhagavatula et al. (2018)

- src/main/java/io/anserini/collection/DocumentCollection.java
- src/main/java/io/anserini/collection/FileSegment.java
Reverting a few lines from #756 - just found out that it breaks Java 8 build even though travis passes for Java 11, and we probably want to keep some backwards compatibility? 
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project anserini: Compilation failure: Compilation failure:
[ERROR] anserini/src/main/java/io/anserini/collection/DocumentCollection.java:[113,24] cannot infer type arguments for java.util.Iterator<E>
[ERROR]   reason: cannot use '<>' with anonymous inner classes
[ERROR] anserini/src/main/java/io/anserini/collection/DocumentCollection.java:[162,49] cannot infer type arguments for java.nio.file.SimpleFileVisitor<T>
[ERROR]   reason: cannot use '<>' with anonymous inner classes
[ERROR] …
```
> Reverted code cleanup changes for inferring class types

- pom.xml
`com.fasterxml.jackson.core:jackson-databind`:
+ [CVE-2019-14379](https://nvd.nist.gov/vuln/detail/CVE-2019-14379)
+ [CVE-2019-14439](https://nvd.nist.gov/vuln/detail/CVE-2019-14439)
> Fixed security vulnerabilities

- docs/runbook-trec2018-anserini.md
Updated search commands
Removed duplicate information
> Updated runbook trec 2018 background linking

- src/main/python/msmarco/retrieve.py
Fixing a call in `retrieve.py` that I missed while previously adapting over to `pyserini`.
> Fix pyserini error in retrieve.py

- docs/experiments-doc2query.md
Successfully reproduce doc2query experiments on MSMARCO and TREC-CAR.
OS:  Ubuntu 18.04.2 LTS
JAVA: openjdk version "11.0.4" 2019-07-1
Python: 3.6.7
> doc2query reproduction test

- docs/regressions-msmarco-passage.md
- src/main/resources/regression/msmarco-passage.yaml
Similarly to #761, will update regressions log once merged with commit id.
> Added msmarco passage regressions for Ax and PRF

- src/main/java/io/anserini/collection/FileSegment.java
- src/main/java/io/anserini/index/IndexCollection.java
This PR modifies `IndexCollection` as followup to #750:
- Moved `segment.close()` call in each indexer thread to a `finally` clause, so that resources will be cleaned up in case of unexpected exception.
- Closes #749.
Also experimented a bit with adding safeguards within `FileSegment` code, but I think ultimately `IndexCollection` (or any future code that iterate over the collections) still should be the place to handle this call - since operations performed on the documents during iteration (but not related to the iterators) might also lead to unexpected exceptions and interruption.
> Updated segment close handling in IndexCollection

- docs/experiments-doc2query.md
Added faster retrieval script mentioned in [docs/experiments-msmarco-passage.md](https://github.com/castorini/anserini/blob/5b29d1654abc5e8a014c2230da990ab2f91fb340/docs/experiments-msmarco-passage.md).
Also, successfully replicated on:
OS: Ubuntu 18.04.3 LTS
JAVA: openjdk 11.0.4 2019-07-16
Python: 3.6.8
> Add alternative faster script implemented in Java and Add Replication Log for doc2query

- src/main/java/io/anserini/rerank/lib/BM25PrfReranker.java
In this PR:
- Added tie-breaking to second retrieval in `BM25PrfReranker`
- Fixes #774 
@lintool before merging this, could you help with sanity checking on a different machine if it's not too much trouble? I re-ran indexing + retrieval twice on `tuna` to check and there were no changes to the regression numbers, but non-determinism issues might be easier to slip by...
> Added score tie-breaking to BM25PrfReranker

- src/main/java/io/anserini/index/generator/WapoGenerator.java
- src/main/java/io/anserini/rerank/lib/NewsBackgroundLinkingReranker.java
- src/main/java/io/anserini/search/SearchArgs.java
Date is saved as an additional field
Date filter can be toggled using command line argument
Without datefilter (BM25 + RM3)
```
target/appassembler/bin/SearchCollection -searchnewsbackground -index lucene-index.core18.pos+docvectors+rawdocs -topicreader NewsBackgroundLinking -topics ~/topics/newsir18-topics.txt -bm25 -rm3 -hits 100 -backgroundlinking.k 100 -runtag bm25_rm3 -output test/bm25-rm3.txt
```
will result in `NDCG@5 = 0.3526`  
With datefilter (BM25 + RM3)
```
target/appassembler/bin/SearchCollection -searchnewsbackground -index lucene-index.core18.pos+docvectors+rawdocs -topicreader NewsBackgroundLinking -topics ~/topics/newsir18-topics.txt -bm25 -rm3 -hits 100 -backgroundlinking.k 100 -backgroundlinking.datefilter -runtag bm25_rm3_df -output outputs/bm25-rm3-df.txt
```
will …
> Add date filter to background linking reranker

- README.md
- docs/known-issues/known-issues-v0.6.0.md
- src/main/java/io/anserini/index/IndexCollection.java
Fixing bug introduced by https://github.com/castorini/anserini/commit/c5ee9af442c500ec43fc28808903cfca2417ac12
> Fix issue with duplicate field for WaPo in Solr.

- docs/known-issues/known-issues-v0.6.0.md
- src/main/java/io/anserini/rerank/lib/ScoreTiesAdjusterReranker.java
Fixes a NPE introduced in https://github.com/castorini/anserini/commit/ca253a4794b5f5bea38749bd40e5f9f4272b8052#diff-63a77306ff399da3f59b9af78f003161R31 that broke `SearchSolr`.
> Catch NPE introduced in recent commit.

- README.md
- docs/regressions-log.md
- docs/regressions.md
+ Updated regression log re: NTCIR
+ Removed comment about Oracle vs. OpenJDK, which doesn't appear to be true anymore.
+ Upgrade to Java 11 isn't "recent" anymore.
> Minor doc updates

- pom.xml
- src/main/java/io/anserini/analysis/vectors/ApproximateNearestNeighborSearch.java
- src/main/java/io/anserini/analysis/vectors/IndexVectors.java
- src/main/java/io/anserini/analysis/vectors/lexlsh/LexicalLshAnalyzer.java
- src/main/java/io/anserini/analysis/vectors/lexlsh/LexicalLshFeaturePositionTokenFilter.java
- src/main/java/io/anserini/analysis/vectors/lexlsh/LexicalLshTruncateTokenFilter.java
- src/test/java/io/anserini/analysis/vectors/FeatureVectorTokenizerTest.java
- src/test/java/io/anserini/analysis/vectors/fw/FakeWordsEncodeAndQuantizeFilterTest.java
- src/test/java/io/anserini/analysis/vectors/fw/FakeWordsEncoderAnalyzerTest.java
- src/test/java/io/anserini/analysis/vectors/lexlsh/LexicalLshAnalyzerTest.java
- src/test/java/io/anserini/analysis/vectors/lexlsh/LexicalLshFeaturePositionTokenFilterTest.java
- src/test/java/io/anserini/analysis/vectors/lexlsh/LexicalLshTruncateTokenFilterTest.java
this PR adds some unit tests for vector analyzers and some missing Anserini license headers.
> Add unit tests to vector analyzers, fixed Anserini headers

- pom.xml
Fatjar is down from 88M to 80M.
Note, `<scope>compile</scope>` isn't needed because `compile` scope is default.
> Trimmed from fatjar dependencies that are only needed for testing

- src/main/java/io/anserini/search/topicreader/NtcirTopicReader.java
- src/main/resources/topics-and-qrels/topics.www1.english.txt
- src/main/resources/topics-and-qrels/topics.www2.english.txt
- src/test/java/io/anserini/search/topicreader/NtcirTopicReaderTest.java
This is the TopicReader for topics in NTCIR format.
Regarding the evaluation tools, NTCIR evaluation tools only accept runs in NTCIR format. As Anserini generates runs in the TREC format, should I convert the NTCIR qrels into TREC format and put them in the `resources` folder, so that users can simply use the TREC eval?
> add topic reader for NTCIR format

- src/main/java/io/anserini/search/SimpleSearcher.java
hi @emmileaf the broader context of this PR is that I'm adjusting the Pyserini bindings on the Java end.
+ Makes BM25 default
+ Makes the ability to switch similarities actually work :)
+ Adds the ability to unset RM3
+ Removes a bunch of bindings to models we don't use
> SimpleSearch refactoring in coordination with Pyserini

- src/main/java/io/anserini/index/IndexCollection.java
Closes #683 
Does something more reasonable now, like:
```
2019-11-22 20:23:42,335 INFO  [main] index.IndexCollection (IndexCollection.java:677) - Starting indexer...
2019-11-22 20:23:42,427 INFO  [main] index.IndexCollection (IndexCollection.java:722) - 1 file found in /tuna1/collections/newswire/WashingtonPost.v2/data
2019-11-22 20:24:42,486 INFO  [main] index.IndexCollection (IndexCollection.java:739) - 60000 documents indexed
2019-11-22 20:25:42,488 INFO  [main] index.IndexCollection (IndexCollection.java:739) - 120000 documents indexed
2019-11-22 20:26:42,487 INFO  [main] index.IndexCollection (IndexCollection.java:739) - 180000 documents indexed
2019-11-22 20:27:42,487 INFO  [main] index.IndexCollection (IndexCollection.java:739) - 240000 documents indexed
2019-11-22 20:28:42,489 …
```
> Improved updating of indexer stats for collections with only one file segment

- src/main/java/io/anserini/util/ExtractDocumentLengths.java
- src/main/java/io/anserini/util/ExtractNorms.java
- src/test/java/io/anserini/util/ExtractDocumentLengthsTest.java
- src/test/java/io/anserini/util/ExtractNormsTest.java
We seem to have a flaky test case that breaks non-deterministically... I've replicated intermittent breakage on Linux, but can't replicate on macOS. Here's some general cleanup... hopefully it'll help.
> Refactored extract doclength/norm util and test cases

- pom.xml
Discovered that we were using a very old artifact - upgraded.
Also fixed ES logging warning:
```
$ sh target/appassembler/bin/SearchElastic -topicreader Trec -es.index robust04 -topics src/main/resources/topics-and-qrels/topics.robust04.txt -output run.es.robust04.bm25.topics.robust04.txt
2019-12-02 15:10:42,323 INFO  [main] search.SearchElastic (SearchElastic.java:183) - Elasticsearch index: robust04
2019-12-02 15:10:42,324 INFO  [main] search.SearchElastic (SearchElastic.java:184) - Elasticsearch hostname: localhost
2019-12-02 15:10:42,324 INFO  [main] search.SearchElastic (SearchElastic.java:185) - Elasticsearch host port: 9200
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See …
```
> Logging upgrade and fixed ES logging warning

- src/main/java/io/anserini/collection/CoreCollection.java
- src/test/java/io/anserini/collection/CoreDocumentTest.java
Addresses CORE issue https://github.com/castorini/anserini/issues/889.
The `CoreCollection` generates a `MultifieldSourceDocument` that is indexed into Lucene for the CORE dataset. Right now we perform `e.getValue().asText()` for all document fields, which for `ArrayNode` JSON types (such as the "topics" field), this [defaults to the empty string](https://fasterxml.github.io/jackson-databind/javadoc/2.10/com/fasterxml/jackson/databind/node/ContainerNode.html#asText--), not the actual text value of the field. This change will convert any array fields into a single string separated by `::`, which can then be indexed by Lucene.
To get the "topics" and "year" fields indexed as "stored" fields in Lucene, we can pass the `-storeTransformedDocs` flag to the indexer, instead of creating a new …
> Convert array fields for CORE dataset collection to string

- pom.xml
Addressing #943:
For Windows, appassembler generated invalid batch files with too long classpaths.
To fix it, we can use wildcards (available from Java 6) along with a flat directory structure.
> Fixed appassembler for Windows

- docs/experiments-msmarco-doc.md
> Add replication log for MSMARCO Document Ranking

- src/main/python/msmarco/convert_collection_to_jsonl.py
- src/main/python/msmarco/filter_queries.py
Line endings + encoding errors in Python prevented the MSMARCO passage experiments from being replicated on Windows so this should fix it. I also re-ran the experiment again on Linux and it still worked.
Will wait for @LuKuuu to also confirm that it works for him on Windows
> Explicit line endings and encoding for MSMARCO passage on Windows

- src/main/java/io/anserini/search/SearchMsmarco.java
Current class does not close the searcher after a run is complete which seems to cause some sort of I/O bottleneck/speed degradation. For instance, if I run consecutive experiments (with the exact same parameters), the latency for retrieving queries will increase linearly with each new experiment.
The searcher is closed properly for the other classes so I'd assume we want the same here
> Close searcher for SearchMsmarco class

- docs/elastirini.md
> Replication log for Elastirini MS MARCO

- docs/elastirini.md
- docs/regressions-core18.md
- docs/regressions-robust04.md
- src/main/resources/docgen/templates/core18.template
- src/main/resources/docgen/templates/robust04.template
I also added a comment about letting the index "catch up"
Will need to rebase with #976 before merging
> Replication logs for Robost04 and Core18

- src/main/java/io/anserini/index/generator/CoreGenerator.java
When we index the CORE hydrology abstracts, Solr reads many of the fields as `Long` values and assigns the the `Long` type to the `datePublished` field. Occasionally there is a `String` that cannot be parsed, breaking the whole indexing pipeline.
Thought it'd be easier to just remove this field entirely since it gives the same value as "year", but occasionally contains month/day. The alternative is to hard-code `datePublished` in the Solr schema.xml file which I'm not a fan of
> Remove datePublished from CoreGenerator to prevent errors on Solr

- src/main/java/io/anserini/search/SearchSolr.java
- src/main/python/run_es_regression.py
- src/main/python/run_solr_regression.py
- src/main/resources/elasticsearch/index-config.core18.json
Ref: Issue #927
Note that the current AP values of Solr with MS MARCO passage and ES with Core18 do not match their expected values. All other cases should work well.
Specifically: 
- Solr with MS MARCO passage produces `[FAILED] 0.187 MAP, expected 0.1956 MAP!`
- ES with Core18 produces `[FAILED] 0.2401 MAP, expected 0.2495 MAP!`
> Add test cases for both Solr/ES with {Core18, Robust04, and MS MARCO passage}

- src/main/java/io/anserini/search/SearchMsmarco.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/IndexerTestBase.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
- Added support for weighted field search with support for multiple threads on MS MARCO Passage
- Fields can be specified with command line arguments
- ex) `-fields contents=1.0f -fields predictions=2.0f` (key is the field name and value is the weight)
- I also added a couple of of extra texts for fielded search and batch search in the `SimpleSearcherTest`
- This is so we can replicate some of the fielded docTTTTTquery results later
> Support field search and batched field search for MS MARCO

- docs/regressions-backgroundlinking18.md
- docs/regressions-backgroundlinking19.md
- src/main/java/io/anserini/rerank/lib/NewsBackgroundLinkingReranker.java
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/topicreader/BackgroundLinkingTopicReader.java
- src/main/resources/regression/backgroundlinking18.yaml
- src/main/resources/regression/backgroundlinking19.yaml
- src/test/java/io/anserini/search/topicreader/BackgroundLinkingTopicReaderTest.java
Lots of inconsistencies in options, naming, etc; we have `searchnewsbackground` and `backgroundlinking` and `NewsBackgroundLinking`. I standardized all names/options around `backgroundlinking`.
> Background linking naming cleanup

- src/main/java/io/anserini/analysis/AnalyzerUtils.java
- src/main/java/io/anserini/ann/ApproximateNearestNeighborEval.java
- src/main/java/io/anserini/ann/ApproximateNearestNeighborSearch.java
- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/main/java/io/anserini/ltr/BaseFeatureExtractor.java
- src/main/java/io/anserini/ltr/DumpTweetsLtrData.java
- src/main/java/io/anserini/rerank/lib/BM25PrfReranker.java
- src/main/java/io/anserini/rerank/lib/Rm3Reranker.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/java/io/anserini/search/query/BagOfWordsQueryGenerator.java
- src/main/java/io/anserini/search/query/QueryGenerator.java
- src/main/java/io/anserini/search/query/SdmQueryGenerator.java
- src/main/java/io/anserini/search/topicreader/BackgroundLinkingTopicReader.java
- src/main/java/io/anserini/util/DumpAnalyzedQueries.java
- src/test/java/io/anserini/IndexerTestBase.java
- src/test/java/io/anserini/analysis/EnglishStemmingAnalyzerTest.java
- src/test/java/io/anserini/analysis/TokenizeOnlyAnalyzerTest.java
- src/test/java/io/anserini/ann/fw/FakeWordsEncoderAnalyzerTest.java
- src/test/java/io/anserini/ann/lexlsh/LexicalLshAnalyzerTest.java
- src/test/java/io/anserini/index/BasicIndexOperationsTest.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
- src/test/java/io/anserini/ltr/BaseFeatureExtractorTest.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
- src/test/java/io/anserini/search/topicreader/CarTopicReaderTest.java
- src/test/java/io/anserini/util/ExtractDocumentLengthsTest.java
- src/test/java/io/anserini/util/ExtractNormsTest.java
Closes #990 
The primary change is that `IndexReaderUtils` now has methods to fetch postings lists given analyzed and unanalyzed forms. However, this necessitated a bunch of changes for proper testing, etc.
> Added methods to get postings lists based on analyzed and unanalyzed forms in IndexReaderUtils

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
Make it possible to define an analyzer in the IndexReaderUtils.getTermCounts function.
> Optional analyzer in getTermCounts

- src/main/java/io/anserini/collection/AclAnthology.java
- src/main/java/io/anserini/collection/BibtexCollection.java
- src/main/java/io/anserini/collection/CarCollection.java
- src/main/java/io/anserini/collection/ClueWeb09Collection.java
- src/main/java/io/anserini/collection/ClueWeb12Collection.java
- src/main/java/io/anserini/collection/CoreCollection.java
- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/collection/NewYorkTimesCollection.java
@edwinzhng @nikhilro I'm going to sneak in this PR before the the next artifact release.
I've made all segment constructors public; there's not reason they shouldn't be (since the segment implementations are static classes, and thus can have existence outside ties to a collection), and in fact some of them are already public. This makes all segment constructors uniformly public.
This also increases testability as a side effect.
> Segment constructors should be public

- src/main/java/io/anserini/util/ExtractDocumentLengths.java
- src/test/java/io/anserini/IndexerWithEmptyDocumentTestBase.java
- src/test/java/io/anserini/integration/EndToEndTest.java
- src/test/java/io/anserini/integration/MultiThreadingSearchTest.java
- src/test/java/io/anserini/search/SearchCollectionTest.java
- src/test/java/io/anserini/util/ExtractDocumentLengthsTest.java
- src/test/java/io/anserini/util/ExtractNormsTest.java
Ref: https://github.com/osirrc/ciff/issues/21
Adds check in ExtractDocumentLengths per above issue.
> ExtractDocumentLengths: prints out sum of doclengths, both lossy and lossless

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/IndexerTestBase.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
Fixes confusion between `contents` and `raw` fields. The `contents` field holds the contents as indexed; the `raw` field holds the raw docs.
These may be different. For example, in the COVID collection, "raw" comprises the metadata record CSV and the raw JSON of the full text. The "contents" field comprises elements that we might have pulled out of the JSON. We search against "contents", _but_ downstream applications might want to use the "raw".
Fixed `SimpleSearcher` so that this confusion is reduced from the Python end.
Note that this is a Pyserini breaking change. We will need to publish new artifact and make adjustments on the Pyserini end.
> SimpleSearcher refactoring, clarifies 'contents' vs. 'raw' field

- README.md
- docs/experiments-covid.md
- src/main/java/io/anserini/collection/CovidCollection.java
- src/main/java/io/anserini/collection/CovidFullTextCollection.java
- src/main/java/io/anserini/collection/CovidParagraphCollection.java
- src/main/java/io/anserini/index/generator/CovidGenerator.java
Resolves #1044 and #1045 
Per the issue, a record is decomposed into (id, content, raw):
* ID, TITLE + ABSTRACT, FULL_TEXT_JSON
* ID.0001, TITLE + ABSTRACT + P1, ""
* ID.0002, TITLE + ABSTRACT + P2, ""
Edits to documentation to resolve `xargs` issues and updates to expected number of documents.
In regards to #1048, the CovidCollection's SourceDocument adds `raw` which is ultimately what goes to `raw` for the document. This is the simplest implementation I think
> Covid Passage Indexing

- src/main/java/io/anserini/collection/AclAnthology.java
- src/main/java/io/anserini/collection/BibtexCollection.java
- src/main/java/io/anserini/collection/CarCollection.java
- src/main/java/io/anserini/collection/ClueWeb09Collection.java
- src/main/java/io/anserini/collection/CoreCollection.java
- src/main/java/io/anserini/collection/CovidCollectionDocument.java
- src/main/java/io/anserini/collection/HtmlCollection.java
- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/collection/MultifieldSourceDocument.java
- src/main/java/io/anserini/collection/NewYorkTimesCollection.java
- src/main/java/io/anserini/collection/SourceDocument.java
- src/main/java/io/anserini/collection/TrecCollection.java
- src/main/java/io/anserini/collection/TweetCollection.java
- src/main/java/io/anserini/collection/WashingtonPostCollection.java
- src/main/java/io/anserini/collection/WikipediaCollection.java
- src/test/java/io/anserini/collection/AclAnthologyTest.java
- src/test/java/io/anserini/collection/BibtexCollectionTest.java
- src/test/java/io/anserini/collection/ClueWeb09CollectionTest.java
- src/test/java/io/anserini/collection/ClueWeb12CollectionTest.java
- src/test/java/io/anserini/collection/CoreCollectionTest.java
- src/test/java/io/anserini/collection/JsonCollectionLineObjectTest.java
- src/test/java/io/anserini/collection/JsonCollectionTest.java
- src/test/java/io/anserini/collection/NewYorkTimesCollectionTest.java
- src/test/java/io/anserini/collection/TrecCollectionTest.java
- src/test/java/io/anserini/collection/TrecwebCollectionTest.java
- src/test/java/io/anserini/collection/TweetCollectionTest.java
- src/test/java/io/anserini/collection/WikipediaCollectionTest.java
Addresses #1048
Made the `SourceDocument` an abstract class so that we can have a separate `raw()` function that returns `content()` by default. I also added the respective tests and updated relevant collections.
> SourceDocument refactor for separate raw field

- src/test/java/io/anserini/integration/BibtexEndToEndTest.java
- src/test/java/io/anserini/integration/EndToEndTest.java
- src/test/java/io/anserini/integration/MultiThreadingSearchTest.java
- src/test/java/io/anserini/integration/TrecEndToEndTest.java
- src/test/java/io/anserini/integration/TrecEndToEndWhitelistTest.java
- src/test/java/io/anserini/integration/TweetEndToEndTest.java
- src/test/resources/sample_topics/bibtex_topics.tsv
Clearly separates different phases of the testing: building the index, checking the built index, and performing retrieval runs. Provides abstract methods for subclasses to override and supply ground truth and custom parameters.
Indexing calls `main` of `IndexCollection`. Since we're doing end-to-end testing, might as well test command-line parsing.
Added initial implementation of `BibtexEndToEndTest`.
> Improved integration testing

- docs/experiments-covid.md
- src/main/java/io/anserini/collection/CovidTrialstreamerCollection.java
- src/main/java/io/anserini/index/generator/CovidGenerator.java
- src/main/resources/solr/schemas/covid.json
* Updated the CovidGenerator according to the SourceDocument refactor and also fixed documentation
* Added support for facet fields in the Trialstreamer data
* Will add tests for all of the Covid related collections and generators in a follow up PR so we know things don't break
> Fix CovidGenerator and add Trialstreamer collection

- docs/regressions-log.md
Detailed explanation of changes in #1092
> Explaining Core18 regression changes

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
`IndexReaderUtils` and `SimpleSearcher` should have the same methods for access documents. Implements `documentByField`, which was previous missing in `SimpleSearcher`. Also aligns documentation so they say the same thing.
> Aligning methods for fetching doc in IndexReaderUtils and SimpleSearcher

- docs/experiments-covid.md
@edwinzhng  @rodrigonogueira4 
Minor concern is that for paragraph index, size went up from 3.4G to 4.7G. The only relevant commit I can see that would impact this is: https://github.com/castorini/anserini/commit/cc3b0a3bd2eb83d8f4802fe2e57e37187586a5be where we us pmc json is available.
Thoughts?
> New indexes CORD-19 04/17 data drop

- docs/experiments-covid.md
Per #1116 - note that the indexes have been renamed.
> Updating CORD-19 to 4/24 data drop

- src/main/java/io/anserini/collection/CovidCollection.java
- src/main/java/io/anserini/collection/CovidCollectionDocument.java
- src/main/java/io/anserini/collection/CovidFullTextCollection.java
- src/main/java/io/anserini/collection/CovidParagraphCollection.java
- src/test/java/io/anserini/collection/CovidCollectionTest.java
- src/test/java/io/anserini/collection/CovidFullTextCollectionTest.java
Fixes #1105
The `raw` field now contains the following for all documents:
```
{
"cord_uid": ID,
"has_full_text": true/false,
"csv_metadata": { ... }
...(rest of fields from full text inline)
}
```
For tests, the reason the `raw` field length decreased is because I load the original full-text JSON string, add the new fields ("cord_uid", "has_full_text", "csv_metadata") and then re-serialize to string which removes a lot of whitespace characters.
> Store CSV and full text in raw field for CORD-19

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
**Environment:** macOS Mojave Version 10.14.6
**Issues:**
No issues after @HangCui0510 updated the READMEs in [PR 1112](https://github.com/castorini/anserini/pull/1112).
> Update replication log for MS MARCO passage & doc

- src/main/java/io/anserini/index/generator/CovidGenerator.java
Closes #1127 (ref #1109)
Small change makes a big difference in the paragraph index.
```bash
$ du -h lucene-index-cord19-*
1.6G	lucene-index-cord19-abstract-2020-04-24
1.6G	lucene-index-cord19-abstract-2020-04-24.old
3.1G	lucene-index-cord19-full-text-2020-04-24
3.1G	lucene-index-cord19-full-text-2020-04-24.old
6.9G	lucene-index-cord19-paragraph-2020-04-24
8.3G	lucene-index-cord19-paragraph-2020-04-24.old
```
> Excludes two outlier documents in CORD-19

- src/main/java/io/anserini/index/IndexReaderUtils.java
Previous use of parser means that a term with a colon is interpreted as a field. See https://github.com/castorini/pyserini/issues/81
> Fix getTermCountsWithAnalyzer when term has a colon in it

- src/main/java/io/anserini/collection/Cord19BaseDocument.java
- src/test/java/io/anserini/collection/Cord19AbstractCollectionTest.java
- src/test/java/io/anserini/collection/Cord19FullTextCollectionTest.java
Before, `csv_metadata` was the string representation of JSON, which meant that when we fetched the `raw` field, we had to parse the JSON, and then parse the `csv_metadata` value again. This way, the value of `csv_metadata` is an actual JSON object.
> CORD-19: changed 'csv_metadata' into JSON

- eval/measure_judged.py
Picking up from [PR 1160](https://github.com/castorini/anserini/pull/1160).
- Moving measure_judged.py to `eval/`
- Formatting the print messages
```
Loading qrels 0
Loading qrels completed
---------------------
judged@5: 0.2
judged@10: 0.15333333333333335
judged@20: 0.15666666666666662
judged@30: 0.14
---------------------
Done
```
> Move measure_judged.py && print formatting

- docs/experiments-covid.md
Added explanation re: indexer changes in TREC-COVID round 1 results.
Closes #1153
> TREC-COVID baselines: added Judged@10 metric and checksums for round 2 runs

- src/main/python/interpolate.py
Interpolate two runs by first normalizing their query-level scores (between 0 and 1) and then doing:
alpha * run1_score + (1 - alpha) * run2_score.
> Adds run interpolation script

- src/main/python/trec-covid/remove_judged_docids.py
Lets user specify runtag from command line.
> remove_judged_docids script for TREC-COVID: added runtag option

- src/main/python/trec-covid/print_run.py
When the queries have more topics than the run, skip missing query id.
For example, the queries file has 35 topics, but the run only has 30 topics. Instead of throwing a key not found error, we should handle it gracefully.
```
--------------------------------------------------
query id: 30 | query: coronavirus remdesivir | question: is remdesivir an effective treatment for COVID-19
rank | doc_id | title
1 | j8n06hzx | Treatment options for COVID-19: the reality and challenges
2 | sqrn6kjy | The epidemiological and clinical features of COVID-19 and lessons from this global infectious public health event
3 | j0i9ozsz | Coronavirus Disease 2019 Treatment: A Review of Early and Emerging Options
4 | nz8qvuw6 | Compounds with Therapeutic Potential against Novel Respiratory 2019 Coronavirus
5 | …
```
> [trec-covid/print_run.py] handling missing query id

- pom.xml
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/java/io/anserini/search/SimpleTweetSearcher.java
- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/util/DumpAnalyzedQueries.java
- src/main/python/verify_simplesearcher.py
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Previously, `SimpleSearcher` had different code paths for searching "normal" documents and searching tweets (which has additional temporal logic). I've untangled into `SimpleSearcher` and `SimpleTweetSearcher` for better maintainability.
Also, I added a `verify_simplesearcher.py` script to confirm that the output of `SimpleSearcher` and `SimpleTweetSearcher` matches _exactly_ the output of `SearchCollection` - i.e., that the different code paths give identical results.
> Untangle SimpleSearcher form SimpleTweetSearcher + verification script

- docs/experiments-cord19.md
Standard process on my end - built "ground truth" indexes, uploaded to Dropbox, sanity-checked results.
> Added latest prebuilt indexes for CORD-19 data drop of 5/12

- src/main/java/io/anserini/index/IndexReaderUtils.java
To make `compute_bm25_term_weight` work from the Python end, we need different method names.
> Rename method to make accessible from Python, for compute_bm25_term_weight

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
+ Seems like it would make sense to have methods that take an unanalyzed form to compute BM25 weights.
+ Overloaded `computeQueryDocumentScore` methods need to be renamed for proper access from the Python end.
> Refactoring of methods for computing {query,term}-document weights

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
> Improved error checking when attempting to fetch doc vector of non-existent document

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
Adds function that returns selection of index statistics in map format (as previously printed in `IndexUtils`)
> Add index statistics function

- src/main/java/io/anserini/index/IndexReaderUtils.java
Deletes stored fields from index statistics, so that we only return quantitative stats.
> Delete stored fields from index stats

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment
OS: macOS 10.15 (Catalina)
Java: 14.0.1
Python: 3.7.6
Issues:
BM25 Baseline on MS Marco Passage Retreival:
Error: return self.object.search(JString(q.encode('utf8')), k)
AttributeError: 'bytes' object has no attribute 'encode’
- Encountered when using pyserini to retrieve the smaller set of queries, had to use java implementation instead.
BM25 Baselines on MS MARCO Doc Retrieval Task
- Within replication doc (for comparison to Microsoft baseline), the command given was: eval/trec_eval.9.0.4/trec_eval -c -mmap -M 100 collections/msmarco-doc/queries-and-qrels/msmarco-docdev-qrels.tsv collections/msmarco-doc/msmarco-docdev-top100.
- I had to modify this to: eval/trec_eval.9.0.4/trec_eval -c -mmap -M 100 collections/msmarco-doc/queries-and-qrels/msmarco-docdev-qrels.tsv …
> Completed replication for msmarco-doc and msmarco-passage

- docs/experiments-cord19.md
- src/main/java/io/anserini/index/generator/Cord19Generator.java
According to the [changelog](https://ai2-semanticscholar-cord-19.s3-us-west-2.amazonaws.com/latest/changelog), the new CORD-19 dataset can have multiple URLs in the "url" field and adds a new "s2_id" field.
Also added a note that fixes #1215.
> CORD-19 Generator Fixes

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: macOS Catalina 10.15.4
Java: openjdk 11.0.7 2020-04-14
Python: 3.7.5
- With default BM25 parameters (k1=0.9, b=0.4)
- With tuned BM25 parameters (k1=3.44, b=0.87)
- With BM25 parameters k1=0.9, b=0.4
- With BM25 parameters k1=0.82, b=0.68
Same issue with pyserini as mentioned in https://github.com/castorini/anserini/pull/1220. Had to fallback to the Java implementation as well.
> Updated replication doc for msmarco-passage and msmarco-doc

- src/main/python/openresearch/retrieve.py
Fixes UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 119: ordinal not in range(128)
> Fixes encoding error when opening OpenResearch's queries file

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment:
OS: MacOS Mojave 10.14.4 
Java: openjdk version "1.8.0_152-release"
Python: 3.6.8
Issues for BM25 Baselines on MS MARCO Passage Retrieval:
- The first command in this [section](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md#retrieving-and-evaluating-the-dev-set) should have a path prefix of `collections/`. I've changed it in my PR
- The second command in the same section above will return an error 
```
tenseisBookpuro:msmarco yangtiancheng$ python ./src/main/python/msmarco/retrieve.py --hits 1000 --threads 1  --index indexes/msmarco-passage/lucene-index-msmarco --qid_queries collections/msmarco-passage/queries.dev.small.tsv  --output runs/run.msmarco-passage.dev.small.tsv
Initializing BM25, setting k1=0.82 and b=0.68
Traceback (most …
```
> Replication for BM25 Baselines on MS MARCO Passage Retrieval and MS MARCO Doc Retrieval Tasks

- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
TREC News topics were not yet accessible via the `TopicReader`.
I copied test cases from `BackgroundLinkingTopicReaderTest` to be complete, but it seems a bit excessive to do same tests again, thoughts?
> Bindings for TREC News topics

- eval/measure_judged.py
As per described in https://github.com/castorini/anserini/issues/1166
* Print percentage as 0.XXXX
* Added `-q` option to print per topic measurement
```
$ python eval/measure_judged.py --qrels src/main/resources/topics-and-qrels/qrels.covid-round12.txt --cutoffs 10 --run runs/anserini.covid-r3.abstract.qq.bm25.txt -q
judged_cut_10   1       0.1000
judged_cut_10   2       0.4000
...
judged_cut_10   40      0.0000
judged_cut_10   all     0.3300
Done
```
> [#1166] eval/measure_judged.py improvments

- src/main/python/trec-covid/utils.py
Modifying `src/main/python/trec-covid/utils.py` so that it works on space & tab-separated Qruns.
> src/main/python/trec-covid/utils.py should work on tab-separated Qruns

- .gitignore
- README.md
+ updated `eval/` submodule
+ updated `.gitignore`
+ simplified pubs; the options here are (1) to keep adding every paper that has to do with Anserini, or (2) to prune down to only the "original" papers. (2) seems easier to maintain in the long run.
> Housekeeping

- src/main/java/io/anserini/collection/Cord19ParagraphCollection.java
- src/main/python/trec-covid/filter_run.py
hey @rodrigonogueira4 remember when we had a discussion about exactly how to index paragraphs?
The old (existing) implement was:
+ docid: title + abstract
+ docid.00001: title + abstract + 1st paragraph
+ docid.00002: title + abstract + 2nd paragraph
+ docid.00003: title + abstract + 3rd paragraph
+ ...
But an equally reasonable alternative would be to *not* repeat the abstract:
+ docid: title + abstract
+ docid.00001: title + 1st paragraph
+ docid.00002: title + 2nd paragraph
+ docid.00003: title + 3rd paragraph
+ ...
I ran an experiment comparing the old and the new approaches, and the tl;dr is that the old approach is more effective:
|    | index | nDCG@10 | Judged@10 | MAP    | Recall@1k | Judged@1k |
|---:|:--------------|--------:|----------:|-------:|----------:|----------:|
|  1 | …
> Experiment on different CORD-19 paragraph indexing conditions

- docs/experiments-cord19.md
- docs/experiments-covid.md
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
+ `generate_round4_baselines.py` for generating the runs.
+ `generate_round3_baselines.py` for generating the r3 runs.
I'm aware of code duplication being an issue, but I wanted to get the scripts written first - we can circle back and refactor later.
@rodrigonogueira4 @ronakice @x65han can you actually run the script and check?
> Add TREC-COVID round 4 baselines

- docs/experiments-covid.md
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
Can I get a replication on both r3 and r4 baselines as a final sanity check?
```
$ python src/main/python/trec-covid/generate_round3_baselines.py
$ python src/main/python/trec-covid/generate_round4_baselines.py
```
@lukuang can you please check the RF run to make sure I got everything correct?
If this checks out, we're ready for Round 4 submission.
> Add TREC-COVID round 4 final submissions + refactor round 3 baselines

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: macOS Catalina 10.15.4
Java: 11.0.7 2020-04-14 LTS 
Python: 3.8.3
No issues encountered when running the experiments, results are identical. 
Fixed a small typo in doc.
default parameters (k1 = 0.9, b = 0.4):
tuned parameters (k1 = 0.82, b = 0.68)
> Add replication log to msmarco-passage and msmarco-doc

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
**Environment**
**OS:** 
macOS Catalina Version 10.15.5
**Java:** 
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
**Python:** 
Python 3.7.4
**Possible Issue**
For MS MARCO Doc Retrieval, when building the index with the following command:
> nohup sh target/appassembler/bin/IndexCollection -collection CleanTrecCollection \
>  -generator DefaultLuceneDocumentGenerator -threads 1 -input collections/msmarco-doc \
>  -index indexes/msmarco-doc/lucene-index.msmarco-doc.pos+docvectors+rawdocs \
>  -storePositions -storeDocvectors -storeRaw >& logs/log.msmarco-doc.pos+docvectors+rawdocs &
I see 
> [1] 31216
in the terminal. Wasn't sure when to expect that the indexing is done, I …
> replicate experiments for msmarco passage and doc

- src/main/java/io/anserini/index/IndexArgs.java
- src/main/java/io/anserini/index/IndexCollection.java
Fix exception related to [#1322](https://github.com/castorini/anserini/pull/1322). The exception is caused by the request size reaching the maximum ES bulk size. Originally, a `bulkRequest` is sent whenever the batch size reaches 1000. We could reduce the batch size, but this may have a big impact on runtime. I think a better way to do it is to not only check if the batch size, but also the request bulk size(in bytes). If either the batch size or the bulk size is reached to a threshold, send the `bulkRequest`. It has been tested on Abstract and Paragraph, and the impact on runtime is minimal. The runtime seems to be better than reducing the batch size only. 
Also, logging of the 10 largest `cord_uid` has been added when the exception is raised, for debugging purposes.
> Fix sendBulkRequest exception

- docs/experiments-covid-doc2query.md
- docs/experiments-covid.md
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
+ evaluation of TREC COVID round 4 baselines with round 4 qrels - both bow and doc2query
+ refactored round 3 baselines: no runs changed, only scripts and results presentation
> Add evaluation of TREC COVID round 4 baselines with round 4 qrels

- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/test/java/io/anserini/index/IndexReaderUtilsTest.java
Currently, [get_document_vector](https://github.com/nsndimt/anserini/blob/6b2bd2cd963a476df600f3bf37f3ba4f7b281d25/src/main/java/io/anserini/index/IndexReaderUtils.java#L364) only return terms and corresponding frequencies. This pull request implements a new function called getPositionList in which returns terms and, for each term,  every position this term occurs in the document.
> expose document level term positions

- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
- src/main/python/trec-covid/generate_round5_baselines.py
Runs remain exactly the same - just refactoring to reduce code duplication.
> Refactor scripts for generating TREC-COVID baselines (rounds 3, 4, 5)

- src/main/java/io/anserini/collection/CommonCrawlNewsEnWarcCollection.java
This commit adds the paper DOI to the codebase. The DOI will come alive with the CIKM 2020 proceedings, and serves as a reference to the paper for any interested parties.
Addresses #1344
> Add URL to CommonCrawlNewsEnWarcCollection.java

- docs/solrini.md
Seems like [`JsoupGenerator`](https://github.com/castorini/anserini/blob/anserini-0.8.1/src/main/java/io/anserini/index/generator/JsoupGenerator.java) was removed in commit [`9a28a0`](https://github.com/castorini/anserini/commit/9a28a098dfd85366be29a6feb385c9e2493f988c) (04/07/2020), but there are some lingering appearances of it:
```
docs/document-matchzoo.md:13: -generator JsoupGenerator -threads 16 -input /path/to/robust04 \
docs/regressions-log.md:25:Previously, Core17 used the `NewYorkTimesCollection` and was indexed with `JsoupGenerator` as the generator, which assumes that the input is HTML (or XML) and removes tags.
docs/runbook-ecir2019-ccrf.md:68: -generator JsoupGenerator -threads 16 -input /path/to/robust04 \
docs/runbook-ecir2019-ccrf.md:73: -generator JsoupGenerator -threads …
```
> JsoupGenerator -> DefaultLuceneDocumentGenerator in doc

- src/test/java/io/anserini/integration/solr/AclAnthologyEndToEndTest.java
- src/test/java/io/anserini/integration/solr/CoreEndToEndTest.java
- src/test/java/io/anserini/integration/solr/SolrEndToEndTest.java
- src/test/java/io/anserini/integration/solr/TrecEndToEndTest.java
As described in https://github.com/castorini/anserini/issues/1367, `EmbeddedSolrServerTestBase` enforces specific PRNG algorithm to be used (or not used) by Java `SecureRandom`. This PR uses `EmbeddedSolrServer` by itself in tests to bypass this check.
> Use standalone EmbeddedSolrServer for Solr integration tests

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: `Ubuntu 18.04.3 LTS`
Java: `openjdk version "11.0.8" 2020-07-14`
Maven: `Apache Maven 3.6.0`
**Passage**: Identical
```
$ python tools/scripts/msmarco/msmarco_eval.py \
collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.dev.small.tsv
MRR @10: 0.18741227770955546
$ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap \
collections/msmarco-passage/qrels.dev.small.trec runs/run.msmarco-passage.dev.small.trec
map                   	all	0.1957
recall_1000           	all	0.8573
```
**Document**: Identical
(inference took 3.5 hours w/o SSD for this task) 
```
2020-09-08 22:31:23,156 INFO  [main] search.SearchCollection (SearchCollection.java:715) - Total run time: 03:34:01
```
```
$ …
```
> Replication for MS-MARCO passage & doc

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment: 
OS: Ubuntu 18.04.4 LTS (VM)
Python 3.8.5
Apache Maven 3.6.0
Results: The results are identical to the those on the experiments page.
Passage with default params
Passage with tuned params
Doc with default params
Doc with tuned params
Issues/concerns:
Retrieval runs for Doc took 10~12 hours, in comparison to the 12 minutes in the guideline, which is unexpected.
Might be due to the limitation of VirtualBox VM.
One unit test failed for Pyserini, but did not seem to affect the results of this duplication.
> MS MARCO Passage and Doc Retrieval Duplication

- docs/solrini.md
https://github.com/castorini/anserini/issues/1010
* Provides instructions about how to configure Solr to read prebuilt Lucene indexes
> [#1010] Add Solr instructions for prebuilt Lucene index

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: `Ubuntu 18.04.5 LTS`
Java: `openjdk version "11.0.8" 2020-07-14`
Maven: `Apache Maven 3.6.0`
```bash
ubuntu:~/anserini$ python3 tools/scripts/msmarco/msmarco_eval.py collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.dev.small.tsv
MRR @10: 0.18741227770955546
ubuntu:~/anserini$ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap \
>  collections/msmarco-passage/qrels.dev.small.trec runs/run.msmarco-passage.dev.small.trec
map                   	all	0.1957
recall_1000           	all	0.8573
```
```bash
ubuntu:~/anserini$ tools/eval/trec_eval.9.0.4/trec_eval -c -mmap -mrecall.1000 src/main/resources/topics-and-qrels/qrels.msmarco-doc.dev.txt runs/run.msmarco-doc.dev.bm25.txt
map …
```
> Add replication results for MS MARCO Doc and Passage

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
```
OS: MacOS Catalina Version 10.15
Java: openjdk version "11.0.5" 2019-10-15
Maven: Apache Maven 3.6.2
```
Passage Retrieval: Identical Results
```
❯ python3 tools/scripts/msmarco/msmarco_eval.py \
collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.dev.small.tsv
MRR @10: 0.18741227770955546
❯ python3 tools/scripts/msmarco/convert_msmarco_to_trec_run.py \
--input runs/run.msmarco-passage.dev.small.tsv \
--output runs/run.msmarco-passage.dev.small.trec
python3 tools/scripts/msmarco/convert_msmarco_to_trec_qrels.py \
--input collections/msmarco-passage/qrels.dev.small.tsv \
--output collections/msmarco-passage/qrels.dev.small.trec
Done!
Done!
❯ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap \ …
```
> Replication of MS MARCO Doc and Passage retrieval by Jerry Huang

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: Mac OS Catalina
Java: openjdk version "12.0.2"
Maven: Apache Maven "3.6.3"
_Replication Results for MS MARCO Passage Retrieval:_
```
$ python tools/scripts/msmarco/msmarco_eval.py \ collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.dev.small.tsv
MRR @10: 0.18741227770955546
$ python tools/scripts/msmarco/convert_msmarco_to_trec_run.py \ --input runs/run.msmarco-passage.dev.small.tsv \ --output runs/run.msmarco-passage.dev.small.trec
Done!
$ python tools/scripts/msmarco/convert_msmarco_to_trec_qrels.py \ --input collections/msmarco-passage/qrels.dev.small.tsv \ --output collections/msmarco-passage/qrels.dev.small.trec
Done!
$ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap \ …
```
> MS MARCO Doc and Passage Retrieval Successful Replication 

- docs/experiments-covid-doc2query.md
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round3_baselines.py
- src/main/python/trec-covid/generate_round4_baselines.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
Updating doc2query baselines after TREC-COVID Round 5 qrels have been posted.
> Updated TREC-COVID doc2query baselines post Round 5

- docs/experiments-covid.md
- src/main/java/io/anserini/search/SearchArgs.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
- src/main/python/trec-covid/index_cord19.py
- src/test/java/io/anserini/integration/TrecEndToEndSegmentTest.java
- src/test/resources/sample_docs/trec/collection3/trec1
- src/test/resources/sample_docs/trec/collection3/trec2
Improved implementation of segment retrieval for MS MARCO per-segment doc expansion, so that we don't need a post-processing script to compute MaxP.
A similar feature already existed as `-strip_segment_id`, used by TREC-COVID in the paragraph condition. I improved and generalized in to `-selectMaxSegment` option. Added test case.
Had to refactor old TREC-COVID scripts/document to use new option.
> More general implementation of segment retrieval (MaxP)

- docs/experiments-covid-doc2query.md
- docs/experiments-covid.md
Adding the suffix `?dl=1` is a Dropbox convention to support direct download without taking you to a landing page.
This makes it possible to check the page with our download scripts:
```
python scripts/check_download_links.py --url https://raw.githubusercontent.com/castorini/anserini/dropbox-links/docs/experiments-covid.md
python scripts/check_download_links.py --url https://raw.githubusercontent.com/castorini/anserini/dropbox-links/docs/experiments-covid-doc2query.md
```
> Changed Dropbox links to support direct download

- docs/regressions-msmarco-passage-docTTTTTquery.md
- src/main/resources/docgen/templates/msmarco-passage-docTTTTTquery.template
After re'org of docTTTTTquery repo, paths have changed.
Also removed sentences that is only applicable for the baseline (i.e., not the expansion version).
> Fixed path to file in docTTTTTquery repo

- docs/experiments-msmarco-passage.md
Replicated experiments, added tuning for MRR/MAP.
> Updated documentation on BM25 tuning for MS MARCO passage

- src/main/java/io/anserini/collection/TweetCollection.java
Plain Text files from Twitter API are by default UFT-8
> UTF-8 in TweetCollection plain text files

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Modifying replication log to track that I was successfully able to replicate the BM25 baseline for MSMARCO Passage and Document Ranking tasks. 
My environment is Ubuntu 19.04 running JDK 11.
I ran into and fixed the following error when running Maven to build the project: 
``` [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project anserini: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1] ```.
I fixed this error by setting the JAVA_HOME environment variable to the root dir for the JDK11 library.
> Replication of BM25 Baseline for MSMARCO Passage and Doc Ranking Tasks

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- OS: Ubuntu 20.04.1 LTS
- Maven: 3.6.3
- Jdk: 11.0.9.1
1. Had a problem in JAVA_HOME when building via maven. Solved by adding "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/" to the ~/.bashrc file
2. Once lose connection in downloading the dataset for Doc experiment. The script is able to restart the downloading process.
3. Cost 15 mins to finish the process of "Performing Retrieval on the Dev Queries" in Doc experiment in a laptop of GTX2060 card and SSD, little longer than 12 mins.
For passage experiment:
For Doc experiment:
> Local replication of Passage and Doc, via anserini

- docs/experiments-doc2query.md
- docs/experiments-msmarco-doc-leaderboard.md
- docs/experiments-msmarco-passage.md
- docs/regressions-msmarco-passage-docTTTTTquery.md
- src/main/resources/docgen/templates/msmarco-passage-docTTTTTquery.template
Used the following commands to find all instances - and fixed.
```
find src docs -type f | xargs grep 'eval/msmarco_eval.py'
find src docs -type f | xargs grep 'scripts/msmarco/ms_marco_doc_eval.py'
find src docs -type f | xargs grep 'scripts/msmarco/msmarco_eval.py'
```
> Updated tools submodule, consistent naming of MS MARCO eval scripts

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- Google Colab (Python3 Google Compute Engine Backend)
- Python 3.6
**Replicated results are exactly the same as the given results**
> Given Results
>My Results
>Given Results
>My Results
> Replicated MS MARCO passage/document ranking results with Anserini

- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
Now the 'fields' option fully defines the set of fields to search.
Closes #1464.
> Stop querying 'contents' by default when searching fields.

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- Google Colab
- Java 11
- Python 3.6
- Maven 3.6.0
- Initially try to build Maven and replicate the experiment on Windows 10. However, the Java 11 JDK installer is not available for download from the link on Oracle's website.
- Initial Maven build failed, then has to reset JAVA HOME as os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64" and the build is successful.
Passage rank
Doc rank
The replicated results are exactly the same as the documentation mentions.
> Relicate MS MARCO passage & document ranking experiment with Anserini

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: Ubuntu 18.04 bionic
Results are the same:
passage:
```
map                   	all	0.1957
recall_1000           	all	0.8573
```
doc:
```
map                   	all	0.2789
recall_1000           	all	0.9326
```
> Arthur replication

- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- Add corresponding Lucene analyzers for Hungarian, Danish, Finnish, Russian, Italian, Dutch, Norwegian, Portuguese, Swedish, Turkish, Thai, Indonesian to address [#565 from pyserini](https://github.com/castorini/pyserini/issues/565)
- Change the support range for `CJKAnalyzer` from Chinese only to Chinese, Japanese and Korean
> add multilingual analyzers to index and search

- docs/experiments-fever.md
- src/main/python/fever/tune_bm25.py
Initial discussion in #1551, ultimately decided that the best fix was to change `'-m recall.100'` to `'-mrecall.100'`.
> Fixed bug in FEVER experiment regarding trec_eval params

- docs/experiments-msmarco-passage.md
- docs/regressions-msmarco-passage-doc2query.md
- docs/regressions-msmarco-passage-docTTTTTquery.md
- docs/regressions-msmarco-passage.md
- src/main/resources/docgen/templates/msmarco-passage-doc2query.template
- src/main/resources/docgen/templates/msmarco-passage-docTTTTTquery.template
- src/main/resources/docgen/templates/msmarco-passage.template
- src/main/resources/regression/msmarco-passage-doc2query.yaml
- src/main/resources/regression/msmarco-passage-docTTTTTquery.yaml
- src/main/resources/regression/msmarco-passage.yaml
Scores didn't change - just better documentation connecting regressions to official leaderboard submissions.
> Improved documentation of MS MARCO passage regressions: BM25, doc2query, and docTTTTTquery

- docs/experiments-msmarco-doc-leaderboard.md
- docs/regressions-msmarco-doc-docTTTTTquery-per-doc.md
- docs/regressions-msmarco-doc-docTTTTTquery-per-passage.md
- docs/regressions-msmarco-doc-per-passage.md
- docs/regressions-msmarco-doc.md
- src/main/resources/docgen/templates/msmarco-doc-docTTTTTquery-per-doc.template
- src/main/resources/docgen/templates/msmarco-doc-docTTTTTquery-per-passage.template
- src/main/resources/docgen/templates/msmarco-doc-per-passage.template
- src/main/resources/docgen/templates/msmarco-doc.template
- src/main/resources/regression/msmarco-doc-docTTTTTquery-per-doc.yaml
- src/main/resources/regression/msmarco-doc-docTTTTTquery-per-passage.yaml
- src/main/resources/regression/msmarco-doc-per-passage.yaml
- src/main/resources/regression/msmarco-doc.yaml
+ Covers {BM25 per doc, BM25 per passage} x {no expansion, docTTTTTquery}
+ Scores didn't change - just better documentation connecting regressions to official leaderboard submissions.
> Improved documentation of MS MARCO doc regressions

- pom.xml
- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleSearcher.java
Anserini uses CJKAnalyzer for analyzing Japanese, but it is not commonly used for Japanese.
This pull request includes installing kuromoji, which is a popular analyzer for Japanese, and changing analyzer to use kuromoji for analyzing Japanese.
I'm sorry but I did not write any unit tests in this commit.
However, using the dataset of NTCIR-15 Data Search Track (Japanese subtask), I have confirmed that the IndexCollection command and the SearchCollection command can be run, referring to [this repository](https://github.com/mpkato/ntcir-datasearch).
> Change analyzer for Japanese

- docs/experiments-msmarco-v2.md
```
$ tools/eval/trec_eval.9.0.4/trec_eval -c -m map -m recall.100 -m recip_rank collections/docv2_dev_qrels.uniq.tsv runs/run.msmarco-doc-v2.dev.txt
map                     all     0.1552
recip_rank              all     0.1572
recall_100              all     0.5956
```
where the `docv2_dev_qrels.uniq.tsv`  is prepared by
```
cat docv2_dev_qrels.tsv | sort | uniq > docv2_dev_qrels.uniq.tsv 
```
> Replicated baseline for MS MARCO V2

- README.md
- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
* AWS EC2 t3a.2xlarge instance
* OS: Ubuntu
* 256 GB SSD
* 32GB RAM
* OpenJDK version: 11.0.11
When running `mvn clean package appassembler:assemble` I encountered the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project anserini: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```
[EDIT] To resolve it, I had to setup my JAVA_HOME env variable accordingly.
> MSMARCO doc/passage reproduction

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Get exactly same result as provided. Screenshots are post
Environment:
OS: macOS Big Sur 11.4
Python: 3.9.5
Java: openjdk 11.0.5 2019-10-15
> Reproduce Anserini: BM25 Baselines for MS MARCO Passage/Document Ranking Experiment

- docs/experiments-msmarco-passage-unicoil.md
Got the same MRR@10 score by using provided collection and queries.
More than that, I actually followed the uniCOIL repo (https://github.com/luyug/COIL/tree/main/uniCOIL) retrained the model with a different seed, and recreated the collection and queries, I got the MRR@10 score of 0.350, pretty close, I'm happy with that.
One question, I notice that uniCOIL retrieval is much slower than bm25, it actually took me more than 1.5 hours on my old laptop. Any insight why this is the case? My guess is because of the small vocab size and super long average posting list?
> UniCOIL reproduced by ArvinZhuang

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment:
OS: macOS 11.2.1 (Big Sur)
Java: 11.0.9.1 (openjdk)
Python: 3.9.1
Problems encountered:
- Initially used Java 8, had to switch to Java 11
> Replicated msmarco-doc and msmarco-passage experiments for initial screening, Matthew Yang

- docs/experiments-msmarco-v2.md
```
$ tools/eval/trec_eval.9.0.4/trec_eval -c -m map -m recall.100,1000 -m recip_rank collections/passv2_dev_qrels.uniq.tsv runs/run.msmarco-passage-v2-augmented.dev.txt
map                     all     0.0863
recip_rank              all     0.0872
recall_100              all     0.4030
recall_1000             all     0.4030
$ tools/eval/trec_eval.9.0.4/trec_eval -c -m map -m recall.100,1000 -m recip_rank collections/passv2_dev2_qrels.uniq.tsv runs/run.msmarco-passage-v2-augmented.dev2.txt
map                     all     0.0904
recip_rank              all     0.0917
recall_100              all     0.4159
recall_1000             all     0.4159
```
for both self-built index and the index `/store/scratch/jimmylin/anserini/indexes/msmarco-passage-v2-augmented`
> reproduce index and search for augmented ms-psg v2

- docs/experiments-msmarco-v2.md
* added `azcopy` usage (feel free to delete it if it is unnecessary)
* `trec_eval` results reproduced. 
* added index time for each case
* **document (segmented) index size has a little discrepancy**, corrected it.
(all the numbers are extracted from the logs by running a script below, the script is just copy and pastes from experiments-msmarco-v2.md)
```sh
(cd indexes && rm -rf msmarco-*)
(cd runs && rm -rf run.msmarco-*)
du -h   collections/msmarco_v2_passage.tar
md5sum  collections/msmarco_v2_passage.tar
sh target/appassembler/bin/IndexCollection -collection MsMarcoPassageV2Collection \
-generator DefaultLuceneDocumentGenerator -threads 18 \
-input collections/msmarco_v2_passage \
-index indexes/msmarco-passage-v2 \
-storePositions -storeDocvectors -storeRaw
sh …
```
> Checking experiments-msmarco-v2.md and reproducing results.

- src/main/java/io/anserini/search/SimpleImpactSearcher.java
- src/main/java/io/anserini/search/SimpleSearcher.java
Creates less noise and doesn't interfere with tqdm on the Python end.
> Reduce logging frequency in batch search for SimpleSearcher and SimpleImpactSearcher

- pom.xml
Closes: https://github.com/castorini/pyserini/issues/901
Issue has to do with multiple copies of META-INF/services/org.apache.lucene.codecs.Codec clobbering each other.
> Fix issue with Lucene not being load the right codec in fatjar

- src/main/java/io/anserini/collection/CommonCrawlWetCollection.java
- src/main/java/io/anserini/collection/DocumentCollection.java
- src/main/java/io/anserini/collection/FeverSentenceCollection.java
- src/main/java/io/anserini/collection/WarcBaseDocument.java
- src/main/java/io/anserini/ltr/FeatureExtractorUtils.java
- src/main/java/io/anserini/ltr/QueryFieldContext.java
- src/main/java/io/anserini/search/SimpleNearestNeighborSearcher.java
- src/main/java/io/anserini/search/topicreader/BackgroundLinkingTopicReader.java
- src/main/java/io/anserini/search/topicreader/Topics.java
hey @stephaniewhoo can you take a look? some of this is your code, I think.
> Map<String, Object> json = new HashMap();
Just suppressing may not be the cleanest collection... is there a more appropriate specialized type than `Object`?
---
Otherwise, fixed a bunch of minor build warnings.
> Cleanup build warnings

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- Reproduced anserini passage ranking and document ranking experiments for the [screening exercise](https://github.com/lintool/guide/blob/master/ura.md)
Environment:
```bash
$ java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
$ mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/homebrew/Cellar/maven/3.8.4/libexec
Java version: 11.0.9.1, vendor: Azul Systems, Inc., runtime: /Users/kevinwang/opt/anaconda3/envs/pyserini
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```
Issues encountered:
- Downloading MS MARCO document dataset took a very …
> Reproduce passage ranking and document ranking experiments

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Reproduced results from MS MARCO passage and doc ranking exercises as part of initial [screening exercise](https://github.com/lintool/guide/blob/master/ura.md)
Was able to reproduce the expected values, below the issues I encountered:
- For the MS MARCO passage ranking, using the provided alternative mirror was much faster (approximately 30 min compared to 2h+ suggested completion time through msmarco.blob.core.windows.net) to download the MS MARCO passages.
- Minor issues: since I was working on a Windows machine, there were small differences in the commands such as using backslashes for file paths, and gzip rather than gunzip for decompression.
Environment Setup:
Windows 10 Pro Version 20H2
Java: openjdk 11.0.9.1
Python: 3.8.4
> Reproduction of MS MARCO passage and doc ranking

- docs/regressions-mrtydi-v1.1-sw.md
- docs/regressions-mrtydi-v1.1-te.md
- src/main/resources/regression/mrtydi-v1.1-sw.yaml
- src/main/resources/regression/mrtydi-v1.1-te.yaml
Note that we do not have language-specific tokenizers for sw and te, so we use whitespace, which is exactly the same as `-pretokenized`. Using `-language xx` is conceptually cleaner, but doesn't change results.
> Change sw and te tokenizers for Mr.TyDi

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Reproduced expected results as described in the passage ranking and document ranking docs.
Environment:
Ubuntu 18.04.5 LTS
Java: `openjdk 11.0.13 2021-10-19`
Python: version 3.9.7
Issues I ran into:
* Downloading the documents from the alternative mirror seemed faster but kept getting this error:
```
Read error at byte 3324919808/8501799926 (Success). Retrying.
```
at which point the download would restart and I would get the same error again eventually.
Downloading from the original source worked fine but was slower.
* Not really an issue, but since I am on linux I had to use `python3` instead of `python` when running the python scripts.
* Ran into `no space left on device` error while indexing documents (had about 28G free before indexing). Solved by freeing up space on device.
> Reproduce MS-MARCO passage and document ranking experiments

- src/main/resources/regression/msmarco-passage-docTTTTTquery.yaml
Closes #1730 - since the only changes to the corpus involve whitespace, the results are exactly the same.
I only had to update the corpus path.
> Add new MS MARCO (V1) passage docTTTTTquery expansion

- src/main/python/run_regression.py
Interesting bug. `args.dry_run` is not in scope within the function `run_search`, but on Python 3.6 this works... whereas _not_ on Python 3.8.
> Fix bug in run_regression re: scoping of variables

- docs/experiments-msmarco-passage.md
Reproduced on ubuntu 20.04 using WSL2 on Windows 10, no issues
> Reproduction of MS-MARCO passage and document ranking experiments

- README.md
- docs/regressions-dl19-doc-segmented-unicoil.md
- docs/regressions-dl19-passage-unicoil.md
- docs/regressions-dl20-doc-segmented-unicoil.md
- docs/regressions-dl20-passage-unicoil.md
- docs/regressions-msmarco-doc-segmented-unicoil.md
- docs/regressions-msmarco-passage-unicoil.md
- docs/regressions.md
- src/main/resources/docgen/templates/dl19-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/dl19-passage-unicoil.template
- src/main/resources/docgen/templates/dl20-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/dl20-passage-unicoil.template
- src/main/resources/docgen/templates/msmarco-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/msmarco-passage-unicoil.template
- src/main/resources/regression/dl19-doc-segmented-unicoil.yaml
- src/main/resources/regression/dl19-passage-unicoil.yaml
- src/main/resources/regression/dl20-doc-segmented-unicoil.yaml
- src/main/resources/regression/dl20-passage-unicoil.yaml
- src/main/resources/regression/msmarco-doc-segmented-unicoil.yaml
+ Add missing regressions for uniCOIL passage on DL19, DL20
+ Add brand new regressions for uniCOIL segmented doc on dev, DL19, and DL20
> Add regressions for uniCOIL for MS MARCO V1

- docs/regressions-msmarco-doc-segmented-unicoil.md
- docs/regressions-msmarco-passage-unicoil.md
- src/main/resources/docgen/templates/msmarco-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/msmarco-passage-unicoil.template
Related issue: #1762 
Replicating the MS MARCO-based experiments, indexing with the [MS MARCO segmented document corpus](https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-doc-segmented-unicoil.md) takes about 72 minutes with 20,545,677 documents.
System information: Apple M1 chip, 16GB RAM, Java 17.0.2
No issues in replication, and obtained the same values.
> uniCOIL Regression experiment reproduction (MS MARCO)

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Reproduced the anserini passage and document ranking experiments for the [initial screening exercise](https://github.com/lintool/guide/blob/master/ura.md). No issues encountered, was able to reproduce everything successfully.
Environment:
```
$ java --version
java 11.0.13 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
$ mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec
Java version: 11.0.13, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.1", arch: "x86_64", family: …
```
> Update replication log for MS-MARCO passage and document ranking experiments

- docs/regressions-beir-v1.0.0-nq-splade-distil-cocodenser-medium.md
- src/main/resources/regression/beir-v1.0.0-nq-splade-distil-cocodenser-medium.yaml
This patch fixes the typo of the ndcg@10 criteria for beir_v1.0.0-nq regression.
> fix typo: reset ndcg@10 criteria of splade-distil-cocodenser

- src/main/resources/regression/beir-v1.0.0-hotpotqa-bm25-flat.yaml
fix typo:
document (non-empty) in regression beir-v1.0.0-hotpotqa-bm25-flat.yaml
> fix typo: beir-v1.0.0-hotpotqa-bm25-flat.yaml

- docs/regressions-beir-v1.0.0-arguana-flat.md
- docs/regressions-beir-v1.0.0-climate-fever-flat.md
- docs/regressions-beir-v1.0.0-dbpedia-entity-flat.md
- docs/regressions-beir-v1.0.0-fever-flat.md
- docs/regressions-beir-v1.0.0-fiqa-flat.md
- docs/regressions-beir-v1.0.0-hotpotqa-flat.md
- docs/regressions-beir-v1.0.0-nfcorpus-flat.md
- docs/regressions-beir-v1.0.0-nq-flat.md
- docs/regressions-beir-v1.0.0-quora-flat.md
- docs/regressions-beir-v1.0.0-scidocs-flat.md
- docs/regressions-beir-v1.0.0-scifact-flat.md
- docs/regressions-beir-v1.0.0-trec-covid-flat.md
- docs/regressions-beir-v1.0.0-webis-touche2020-flat.md
- src/main/java/io/anserini/collection/BeirFlatCollection.java
- src/main/resources/regression/beir-v1.0.0-arguana-flat.yaml
- src/main/resources/regression/beir-v1.0.0-climate-fever-flat.yaml
- src/main/resources/regression/beir-v1.0.0-dbpedia-entity-flat.yaml
- src/main/resources/regression/beir-v1.0.0-fever-flat.yaml
- src/main/resources/regression/beir-v1.0.0-fiqa-flat.yaml
- src/main/resources/regression/beir-v1.0.0-hotpotqa-flat.yaml
- src/main/resources/regression/beir-v1.0.0-nfcorpus-flat.yaml
- src/main/resources/regression/beir-v1.0.0-nq-flat.yaml
- src/main/resources/regression/beir-v1.0.0-quora-flat.yaml
- src/main/resources/regression/beir-v1.0.0-scidocs-flat.yaml
- src/main/resources/regression/beir-v1.0.0-scifact-flat.yaml
- src/main/resources/regression/beir-v1.0.0-trec-covid-flat.yaml
- src/main/resources/regression/beir-v1.0.0-webis-touche2020-flat.yaml
- src/test/java/io/anserini/collection/BeirFlatCollectionCompressedTest.java
- src/test/java/io/anserini/collection/BeirFlatCollectionTest.java
To reduce confusion, I'm renaming `BeirCollection` to `BeirFlatCollection`. I'll then implement `BeirMultiFieldCollection` (separate PR) that will separately index the BEIR fields.
> Rename BeirCollection -> BeirFlatCollection

- README.md
> Update README.md with note about test failures on Windows

- docs/regressions-dl19-passage-wp.md
- docs/regressions-dl20-passage-wp.md
- docs/regressions-msmarco-passage-wp.md
- src/main/resources/regression/dl19-passage-wp.yaml
- src/main/resources/regression/dl20-passage-wp.yaml
- src/main/resources/regression/msmarco-passage-wp.yaml
Otherwise, if we run the "base" and "wp" versions concurrently, they clash with each other.
> Rename msmarco-passage -> msmarco-passage-wp in YAML for wp-based regressions

- src/main/python/beir/gather_beir_results.py
```
% python src/main/python/beir/gather_beir_results.py                
nDCG@10                  flat    multi   SPLADE
------  ------  ------
trec-covid               0.5947  0.6559  0.7109
bioasq                   0.5225  0.4646  0.5035
nfcorpus                 0.3218  0.3254  0.3454
nq                       0.3055  0.3285  0.5442
hotpotqa                 0.6330  0.6027  0.6860
fiqa                     0.2361  0.2361  0.3514
signal1m                 0.3304  0.3304  0.2957
trec-news                0.3952  0.3977  0.3936
robust04                 0.4070  0.4070  0.4581
arguana                  0.3970  0.4142  0.5210
webis-touche2020         0.4422  0.3673  0.2435
cqadupstack-android      0.3801  0.3709  0.3954
cqadupstack-english      0.3453  0.3321  0.4026
cqadupstack-gaming       0.4822 …
```
> Add script to programmatically gather BEIR results

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- Windows 10 Pro version - 21H1
- Python version - 3.8.13
- Java version - 18.0.1
- Maven version - 3.8.5
Please let me know if there are any other environment specifications you would like to know.
The following command for cloning the Pyserini repo did not work:
```powershell
git clone git@github.com:castorini/anserini.git --recurse-submodules
```
The following command was used instead:
```powershell
git clone https://github.com/castorini/anserini.git --recurse-submodules
```
The make command caused some trouble. The GitHub discussion post where I describe the problem and solution is linked [here](https://github.com/castorini/pyserini/discussions/1121).
There were no issues in reproducing the results.
> Updated reproduction log for MS MARCO doc and passage ranking exercises

- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
> Add Multi-threaded Batch Document

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment
- open jdk 11.0.15
- Apache Maven 3.6.3
- Ubuntu 20.04.4 (UWaterloo CS student linux servers)
- Python 3.7.6
No issues encountered
> Appended to reproduction logs of passage and document ranking

- README.md
- docs/regressions-dl19-doc-segmented-unicoil-noexp.md
- docs/regressions-dl19-doc-segmented-unicoil.md
- docs/regressions-dl19-passage-unicoil-noexp.md
- docs/regressions-dl19-passage-unicoil.md
- docs/regressions-dl20-doc-segmented-unicoil-noexp.md
- docs/regressions-dl20-doc-segmented-unicoil.md
- docs/regressions-dl20-passage-unicoil-noexp.md
- docs/regressions-dl20-passage-unicoil.md
- docs/regressions-msmarco-doc-segmented-unicoil-noexp.md
- docs/regressions-msmarco-doc-segmented-unicoil.md
- docs/regressions-msmarco-passage-unicoil-noexp.md
- docs/regressions-msmarco-passage-unicoil.md
- src/main/resources/docgen/templates/dl19-doc-segmented-unicoil-noexp.template
- src/main/resources/docgen/templates/dl19-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/dl19-passage-unicoil-noexp.template
- src/main/resources/docgen/templates/dl19-passage-unicoil.template
- src/main/resources/docgen/templates/dl20-doc-segmented-unicoil-noexp.template
- src/main/resources/docgen/templates/dl20-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/dl20-passage-unicoil-noexp.template
- src/main/resources/docgen/templates/dl20-passage-unicoil.template
- src/main/resources/docgen/templates/msmarco-doc-segmented-unicoil-noexp.template
- src/main/resources/docgen/templates/msmarco-doc-segmented-unicoil.template
- src/main/resources/docgen/templates/msmarco-passage-unicoil-noexp.template
- src/main/resources/docgen/templates/msmarco-passage-unicoil.template
Minor fixes: broken links, clarified parameter options, etc.
> Clean up MS MARCO V1 passage/doc repro guide

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
The reproduction was done on Ubuntu 18.04, 32gb RAM and 1Tb HDD. The process went smoothly, only notable difference was in the indexing time which took a little longer than README suggested. I suspect this is because of my HDD drive.
> Reproduction Log Update For Anserini

- src/main/python/run_regression.py
`SearchCollection` automatically adjusts tie-breaking behavior if it detects a Lucene 8 index - updating run_regression script accordingly.
> Update Lucene8 option in run_regression.py

- src/main/java/io/anserini/rerank/RerankerContext.java
- src/main/java/io/anserini/rerank/lib/Rm3Reranker.java
- src/main/java/io/anserini/rerank/lib/RocchioReranker.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
Right now, it's a pretty stupid implementation: uses the reranker context to store the feedback terms.
To get the feedback terms, we actually need to run the query - bindings in `SimpleSearcher`.
> Add ability to extract feedback terms

- docs/regressions-backgroundlinking18.md
- docs/regressions-backgroundlinking19.md
- docs/regressions-backgroundlinking20.md
- src/main/java/io/anserini/rerank/lib/BM25PrfReranker.java
- src/main/java/io/anserini/rerank/lib/Rm3Reranker.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/resources/regression/backgroundlinking18.yaml
- src/main/resources/regression/backgroundlinking19.yaml
- src/main/resources/regression/backgroundlinking20.yaml
- src/test/java/io/anserini/search/SimpleSearcherTest.java
batch_search for RM3 doesn't appear to work, as reported in https://github.com/castorini/pyserini/issues/831
I tracked down the issue to the fact that analyzers have state, and so concurrent calls to analyze the query causes issues.
Solution is to analyze the query just once.
I also fixed the thread safety issue with BM25prf. The issue is that we swap in a different similarity in the searcher,
so interleaved execution confuses the reranker wrt what similarity we're actually using.
> Fix batch_search for RM3, made BM25prf thread-safe

- src/main/java/io/anserini/collection/JsonCollection.java
- src/main/java/io/anserini/index/SimpleIndexer.java
- src/main/java/io/anserini/index/generator/DefaultLuceneDocumentGenerator.java
- src/test/java/io/anserini/collection/JsonCollectionLineObjectTest.java
- src/test/java/io/anserini/index/SimpleIndexerTest.java
Goal is to enable indexing from the Python end without first having to write out a file.
Initial impl, which is quite simple, uses only a single thread. This will be too painful for indexing even moderate size collections.
> Add SimpleIndexer

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Reproduced the anserini passage and document ranking experiments for the [initial screening exercise](https://github.com/lintool/guide/blob/master/ura.md).
Hardware:
Dev Environment:
JAVA 11.0.2, Maven 3.8.4, Python 3.8.8.
No issues encountered and the experiment was successfully reproduced.
> Updated Replication Log for Anserini Passage and Doc

- src/main/java/io/anserini/analysis/AnalyzerMap.java
- src/main/java/io/anserini/index/SimpleIndexer.java
- src/test/java/io/anserini/index/SimpleIndexerTest.java
A couple of notes:
- AnalyzerMap.java helps avoid a lengthy if/else in SimpleIndexer as we have currently in IndexCollection when selecting language-specific analyzers
- `storeDocvectors`, `storePositions` etc are usually passed through IndexCollection.Args to the generator. Rather than update all generators with new constructors able to use SimpleIndexer.Args to collect this argument, I currently allow SimpleIndexer to reuse `IndexCollection.Args`. 
- A downside of this decision is that when SimpleIndexer is initialized from Args, `-collection` and `-threads` must be passed (because they are marked as required in IndexCollection.Args). However, they are not used by Simplelndexer.
See #2060
> update SimpleIndexer to use IndexCollection.Args

- src/main/java/io/anserini/index/SimpleIndexer.java
- src/test/java/io/anserini/index/SimpleIndexerTest.java
Implementation: `addDocuments` method takes a batch of documents, consumed by a threadpool.
> Add batch indexing to SimpleIndexer.java

- pom.xml
Upgrade the tokenizer version to solve `HuggingFaceTokenizerEndToEndTest` fail
Tested env:
- Ubuntu GLIBC 2.27
- CentOS 7
- (M1) MacOS 12.6
Related issues:
https://github.com/castorini/anserini/pull/2072#issue-1613565914
> upgrade djl tokenizer to 0.21.0

- src/main/resources/regression/dl19-passage-splade-pp-ed-onnx.yaml
- src/main/resources/regression/dl19-passage-splade-pp-sd-onnx.yaml
- src/main/resources/regression/dl20-passage-splade-pp-ed-onnx.yaml
- src/main/resources/regression/dl20-passage-splade-pp-sd-onnx.yaml
- src/main/resources/regression/msmarco-passage-splade-pp-ed-onnx.yaml
- src/main/resources/regression/msmarco-passage-splade-pp-sd-onnx.yaml
Building on @ArthurChen189 's recent PR.
Some initial ONNX regressions so we can start playing around with it...
These work:
```bash
nohup python src/main/python/run_regression.py --index --verify --search --regression msmarco-passage-splade-pp-ed-onnx >& logs/log.msmarco-passage-splade-pp-ed-onnx &
nohup python src/main/python/run_regression.py --index --verify --search --regression msmarco-passage-splade-pp-sd-onnx >& logs/log.msmarco-passage-splade-pp-sd-onnx &
```
As well as:
```bash
nohup python src/main/python/run_regression.py --search-pool 1 --verify --search --regression dl19-passage-splade-pp-ed-onnx >& logs/log.dl19-passage-splade-pp-ed-onnx &
nohup python src/main/python/run_regression.py --search-pool 1 --verify --search --regression dl20-passage-splade-pp-ed-onnx >& …
```
> Add initial ONNX regressions

- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/topicreader/TopicReader.java
Command: `python src/main/python/run_regression.py --index --verify --search --regression msmarco-doc`
Error:
```
2023-04-10 20:08:13,771 ERROR [pool-2-thread-1] search.SearchCollection$SearcherThread (SearchCollection.java:937) - pool-2-thread-1: Unexpected Exception: 
java.lang.NullPointerException: null
at java.io.Reader.<init>(Reader.java:167) ~[?:?]
at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:?]
at io.anserini.search.SearchCollection$SearcherThread.run(SearchCollection.java:915) [anserini-0.21.1-SNAPSHOT.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
2023-04-10 20:08:14,743 INFO …
```
> minor fixup

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- Java: OpenJDK v19.0.0
- Maven: v3.9.1
- Device: M1 Macbook Air (macOS Monterey v12.0.1)
I was able to successfully reproduce the results but my initial build failed due to some failing tests (pasted below). I was able to build by skipping the tests and ran into no further issues. 
```
[ERROR] Failures: 
[ERROR]   AclAnthologyTest The test or suite printed 13940 bytes to stdout and stderr, even though the limit was set to 8192 bytes. Increase the limit with @Limit, ignore it completely with @SuppressSysoutChecks or run with -Dtests.verbose=true
[ERROR]   JsonVectorCollectionDocumentObjectTest The test or suite printed 28311 bytes to stdout and stderr, even though the limit was set to 8192 bytes. Increase the limit with @Limit, ignore it completely with @SuppressSysoutChecks or run with …
```
> Reproduce Passage and Document Ranking Results for MS-MARCO

- pom.xml
Bumping to version 1.12.1 since 1.11.0 is not compatible with M1 Macs, [as described here](https://github.com/microsoft/onnxruntime/issues/11054)
> Bump Onnx to v1.12.1

- src/main/java/io/anserini/search/SimpleSearcher.java
- src/test/java/io/anserini/IndexerWithoutDocvectorsTestBase.java
- src/test/java/io/anserini/search/SimpleSearcherTest.java
- src/test/java/io/anserini/search/SimpleSearcherWithoutDocvectorsTest.java
This allows us to perform relevance feedback without storing docvectors.
> Expose in SimpleSearcher ability to parse docs on-the-fly

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
**Environment**
Java: 20
Maven: 3.9.1
OS name: macOS Monterey ver. 12.6.3, 16GB RAM, processor: 2,6 GHz 6-Core Intel Core i7
**Result**
Both ran with the same output as the instruction, here are MPR outputs of certain config:
For `k1: 0.82` and `b: 0.68` (Optimized for recall@100)
For `k1: 3.8` and `b: 0.87` (Optimized for MRR@100/MAP)
> Reproduce Passage MS MARCO Passage and Document Ranking

- src/main/java/io/anserini/analysis/HuggingFaceTokenizerAnalyzer.java
- src/main/java/io/anserini/eval/RelevanceJudgments.java
- src/main/java/io/anserini/search/SimpleImpactSearcher.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/java/io/anserini/search/query/QueryEncoder.java
- src/main/java/io/anserini/search/query/SpladePlusPlusEnsembleDistilQueryEncoder.java
- src/main/java/io/anserini/search/query/SpladePlusPlusSelfDistilQueryEncoder.java
- src/main/java/io/anserini/search/query/UniCoilQueryEncoder.java
- src/main/java/io/anserini/search/topicreader/TopicReader.java
- src/test/java/io/anserini/search/SimpleImpactSearcherTest.java
Added support for Pyserini usage of ONNX on-the-fly query encoder
[Related PR](https://github.com/castorini/pyserini/pull/1516)
> add pyserini onnx encoder support

- docs/regressions-msmarco-passage-splade-pp-ed-onnx.md
- docs/regressions-msmarco-passage-splade-pp-sd-onnx.md
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/msmarco-passage-splade-pp-sd-onnx.template
Correctly reproduced the results using onnx.
Environment
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)
Python 3.8.13
> Reproduction of onnx results

- docs/regressions-dl19-passage-splade-pp-ed-onnx.md
- docs/regressions-dl19-passage-splade-pp-sd-onnx.md
- docs/regressions-dl20-passage-splade-pp-ed-onnx.md
- docs/regressions-dl20-passage-splade-pp-sd-onnx.md
- src/main/resources/docgen/templates/dl19-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/dl19-passage-splade-pp-sd-onnx.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-ed-onnx.template
- src/main/resources/docgen/templates/dl20-passage-splade-pp-sd-onnx.template
Correctly reproduced the results using onnx.
Environment
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21)
OpenJDK 64-Bit Server VM JBR-11.0.13.7-1751.21-jcef (build 11.0.13+7-b1751.21, mixed mode)
Python 3.8.13
Example:
2023-06-01 12:37:50,482 INFO  [python] ========== Verifying Results: msmarco-passage-splade-pp-sd ==========
2023-06-01 12:37:50,757 INFO  [python]    [OK] expected: 0.5139 actual: 0.5139 - metric: AP@1000  model: splade-pp-sd topics: dl20
2023-06-01 12:37:50,946 INFO  [python]    [OK] expected: 0.7282 actual: 0.7282 - metric: nDCG@10  model: splade-pp-sd topics: dl20
2023-06-01 12:37:51,154 INFO  [python]    [OK] expected: 0.7512 actual: 0.7512 - metric: R@100    model: splade-pp-sd topics: dl20
2023-06-01 …
> Reproduce splade-pp-onnx with TREC DL 2019 and 2020

- src/main/java/io/anserini/util/DumpAnalyzedQueries.java
Allows the query dump tool to use analyzers beyond the simple English/Porter combination.
> Add all current analyzers to DumpAnalyzedQueries

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment Details: 
+ MacBook Pro Apple M2, 16GB RAM, Ventura 13.3 
+ Apache Maven 3.9.2
+ Java version: 20.0.1
+ Python 3.10.9
> Reproducing experiment results for MS-MARCO passage and document ranking

- docs/approximate-nearestneighbor.md
- src/main/java/io/anserini/analysis/lexlsh/LexicalLshAnalyzer.java
- src/main/java/io/anserini/index/IndexInvertedDenseVectors.java
- src/main/java/io/anserini/index/generator/InvertedDenseVectorDocumentGenerator.java
- src/main/java/io/anserini/search/EvaluateInvertedDenseVectors.java
- src/main/java/io/anserini/search/SearchInvertedDenseVectors.java
- src/main/java/io/anserini/search/query/InvertedDenseVectorQueryGenerator.java
- src/test/java/io/anserini/index/IndexInvertedDenseVectorsTest.java
- src/test/java/io/anserini/search/SearchInvertedDenseVectorsTest.java
- src/test/resources/sample_docs/json_vector/dense_collection1/doc1.json
- src/test/resources/sample_docs/json_vector/dense_collection1/doc2.json
this extends `IndexInvertedDenseVectors` and `SearchInvertedDenseVectors`, InvertedDenseVectorsDocumentGenerator and `InvertedDenseVectorsQueryGenerator` to allow users to index MSMarco using LSH or FW analyzers.
Indexing command example:
```bash
./target/appassembler/bin/IndexInvertedDenseVectors -collection JsonDenseVectorCollection -generator InvertedDenseVectorsDocumentGenerator -threads 1 -index /path/to/fw-msmarco-passage/ -input /path/to/vector-cos-dpr-msmarco-passage -encoding fw 
```
Search command example:
```bash
./target/appassembler/bin/SearchInvertedDenseVectors  -index /path/to/index-cos-dpr-msmarco-passage/ \
-topics /path/to/vector-cos-dpr-msmarco-passage-dev-query/encoded-query.jsonl \
-topicreader JsonIntVector \
-querygenerator InvertedDenseVectorsQueryGenerator \ …
```
> make it possible to index/search MSMarco with fw/lexlsh ann

- src/test/java/io/anserini/search/EvaluateInvertedDenseVectorsTest.java
`EvaluateInvertedDenseVectorsTest` should run `EvaluateInvertedDenseVectors` runner with the `-index` param, not the `-path` one.
> EvaluateInvertedDenseVectorsTest should use -index, not -path

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- docs/start-here.md
Adding reproduction logs for:
- start-here.md
- experiments-msmarco-passage.md
- experiments-msmarco-doc.md
Environment:
- Results were reproduced on `orca`
- Apache Maven: 3.9.2 
- Java version: 11.0.13
- Python: 3.8.16
Everything works as expected, all results were reproduced.
> Add repro logs for onboarding path

- src/main/java/io/anserini/search/SimpleImpactSearcher.java
- src/main/java/io/anserini/search/query/QueryEncoder.java
- src/main/java/io/anserini/search/query/SpladePlusPlusEnsembleDistilQueryEncoder.java
- src/main/java/io/anserini/search/query/SpladePlusPlusSelfDistilQueryEncoder.java
- src/main/java/io/anserini/search/query/UniCoilQueryEncoder.java
- src/test/java/io/anserini/search/SimpleImpactSearcherPrebuiltLucene8Test.java
- src/test/java/io/anserini/search/SimpleImpactSearcherPrebuiltLucene9Test.java
- src/test/java/io/anserini/search/SimpleImpactSearcherTest.java
> Add ability to parse raw text into docvectors on-the-fly for impact indexes #2122

- docs/experiments-msmarco-passage.md
- docs/start-here.md
**OS**: macOS Ventura Version 13.5
**Hardware**: M2 MacBook Pro (2023), 16 GB RAM
**Java**: 20.0.2
**Maven**: 3.9.4
**Python**: 3.11.4
**Result**: I was able to replicate the Indexing, Retrieval & Evaluation steps on my machine with the above settings. Outputs are the same as listed in the document. I also repeat the steps for two other queries (one with MRR@10=0.33 and the other with MRR@10=0.00) and their MRR@10 scores agree with the ranking lists.
**Additional Comment**: There might be a typo in the start-here.md file. Given the context, it seems 1048585 is the query id rather than the document id.
> Add an entry in the Passage Ranking Experiment Reproduction Log for ugrad onboarding

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Fixed minor typo: 'except' --> 'expect' ('accept' also would have worked)
Using MacBook Pro 2019 running macOS Ventura 13.4.1
Everything worked mostly fine.
For the 'python' terminal commands, I had to replace 'python' with 'python3' because I hadn't installed Anaconda
> Results reproduced by @lucedes27

- docs/experiments-msmarco-passage.md
- docs/start-here.md
**OS & Hardware**: Student Environment (Ubuntu2204)
**Result**: I was able to replicate the MS MARCO Tour (i.e. download & extra the data, data munging and analyze qrels files) on my machine with the above settings. Outputs are the same as listed in the "start-here" document. 
**Hiccups**: On student env we need to install our own jdk, else it won't build
**Fix**(what I did):
1. Download openjdk version 11 or higher in tar.gz
2. SCP it to the student env and extract at your place
3. Update JAVA_HOME in .bashrc
> Add Entries to Reproduction Log for Anserini BM25 Baselines for MS MARCO Passage Ranking

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Adding reproduction logs:
```
- start-here.md
- experiments-msmarco-passage.md
```
Environment:
```
Machine:  macOS Big Sur 11.7.8 (Memory: 16 GB 1600 MHz DDR3, Processor: 2.6 GHz Quad-Core Intel Core i7)
Apache Maven: 3.9.4
Java version: 11.0.2
Python: 3.8.17
```
Every result has been successfully reproducible.
> Add to onboarding reproduction logs by Sumon Kanti Dey

- docs/experiments-forum2018.md
Hi @lukuang can you take a look? I've updated to documentation per #2195
> Update 'Neural Hype' documentation

- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
Follow up to #2196 - for whatever reason - most likely carelessness on my part - there are more effectiveness differences that I didn't capture - on the doc2query runs.
Running from scratch again to confirm:
```
python src/main/python/trec-covid/download_indexes.py --date 2020-07-16 &
python src/main/python/trec-covid/download_indexes.py --date 2020-06-19 &
python src/main/python/trec-covid/download_indexes.py --date 2020-05-19 &
python src/main/python/trec-covid/download_indexes.py --date 2020-05-01 &
python src/main/python/trec-covid/download_indexes.py --date 2020-04-10 &
nohup python src/main/python/trec-covid/generate_round5_baselines.py >& logs/log.trec-covid.round5 &
nohup python src/main/python/trec-covid/generate_round4_baselines.py >& logs/log.trec-covid.round4 &
nohup python …
```
> Fix TREC-COVID regressions (take 2)

- src/main/java/io/anserini/encoder/SparseEncoder.java
- src/main/java/io/anserini/encoder/SpladePlusPlusEnsembleDistilEncoder.java
- src/main/java/io/anserini/encoder/SpladePlusPlusSelfDistilEncoder.java
- src/main/java/io/anserini/encoder/UniCoilEncoder.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleImpactSearcher.java
- src/test/java/io/anserini/encoder/SpladeEncoderTokenizationTest.java
- src/test/java/io/anserini/encoder/SpladePlusPlusEncoderInferenceTest.java
- src/test/java/io/anserini/encoder/SpladePlusPlusEnsembleDistilEncoderInferenceTest.java
- src/test/java/io/anserini/encoder/SpladePlusPlusSelfDistilEncoderInferenceTest.java
- src/test/java/io/anserini/encoder/UniCoilEncoderInferenceTest.java
- src/test/java/io/anserini/encoder/UniCoilEncoderTokenizationTest.java
+ `QueryEncoder` -> just `Encoder`, because in theory they can encode documents.
+ move encoders into their own package; not limited to searching.
+ `SparseEncoder`, because we'll implement _dense_ encoders soon.
> Refactor ONNX encoders

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Everything went smoothly. Did `python3` instead of `python` for the commands
Build: MacBook Pro, 2021
OS: macOS Sonoma 14.0
RAM: 16 GB
> Onboarding Dourian Anserini

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Started onboarding module and reproduced BM25 successfully. Added my entry to reproduction logs in `start-here.md` and `experiments-msmarco-passage.md`.
- Macbook Air 2019
- MacOS Ventra 13.3.1
- Apache Maven 3.9.4
- Python 3.9.13
- openjdk 15.0.2
- Used `python3` instead of `python` for commands.
> Add to onboarding reproduction logs

- README.md
- docs/regressions.md
- docs/regressions/regressions-dl19-passage-cos-dpr-distil.md
- docs/regressions/regressions-dl20-passage-cos-dpr-distil.md
- src/main/python/regressions-batch03.txt
- src/main/python/run_regression.py
- src/main/resources/docgen/templates/dl19-passage-cos-dpr-distil.template
- src/main/resources/docgen/templates/dl20-passage-cos-dpr-distil.template
- src/main/resources/regression/dl19-passage-cos-dpr-distil.yaml
- src/main/resources/regression/dl20-passage-cos-dpr-distil.yaml
Current scores:
```
% python src/main/python/run_regression.py --search --regression dl19-passage-cos-dpr-distil
2023-09-23 13:27:10,105 INFO  [python] ========== Ranking ==========
2023-09-23 13:27:10,216 INFO  [python] target/appassembler/bin/SearchHnswDenseVectors -index indexes/lucene-hnsw.msmarco-passage-cos-dpr-distil/ -topics tools/topics-and-qrels/topics.dl19-passage.cos-dpr-distil.jsonl.gz -topicreader JsonIntVector -output runs/run.msmarco-passage-cos-dpr-distil.dl19.cos-dpr-distil -querygenerator VectorQueryGenerator -topicfield vector -threads 16 -hits 1000 -efSearch 1000
2023-09-23 13:27:11,202 INFO  [main] search.SearchHnswDenseVectors (SearchHnswDenseVectors.java:305) - ============ Initializing Searcher ============
2023-09-23 13:27:11,205 INFO  [main] …
```
> Add cos-dpr-distill regressions for TREC DL 19/20

- src/main/python/analyze_regression_logs.py
After we run regressions, script does a simple analysis like the following:
```
$ python src/main/python/analyze_regression_logs.py
Found log files for 366 regression runs.
Start time: 2023-09-29 13:35:46,220
End time:   2023-10-05 02:06:34,648
Duration: 5 days, 12:30:48.428000 ~132.5h
```
> Add simple Python script to compute duration from regression runs

- src/main/java/io/anserini/eval/Qrels.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
WIP, for [pyserini 2CR](https://github.com/castorini/pyserini/pull/1674)
[anserini-tools PR](https://github.com/castorini/anserini-tools/pull/57)
> Add AToMiC dense validation qrels + topics

- docs/experiments-msmarco-passage.md
- src/main/python/analyze_reproductions.py
Simple script to analyze reproduction logs:
```
% python src/main/python/analyze_reproductions.py
Analyzing docs/start-here.md
+ count: 19
+ start: 2023-07-21
+ end:   2023-11-01
+ total: 103 days
+ ratel: 5.42
Analyzing docs/experiments-msmarco-passage.md
+ count: 108
+ start: 2019-08-12
+ end:   2023-11-03
+ total: 1544 days
+ ratel: 14.30
```
> Add simple script to analyze reproductions

- README.md
- docs/regressions/regressions-ciral-v1.0-ha.md
- docs/regressions/regressions-ciral-v1.0-so.md
- docs/regressions/regressions-ciral-v1.0-sw.md
- docs/regressions/regressions-ciral-v1.0-yo.md
- src/main/resources/docgen/templates/ciral-v1.0-ha.template
- src/main/resources/docgen/templates/ciral-v1.0-so.template
- src/main/resources/docgen/templates/ciral-v1.0-sw.template
- src/main/resources/docgen/templates/ciral-v1.0-yo.template
This PR modifies CIRAL's monolingual regressions to mention dev in the documentation. 
Also modifies FIRE's regression documentation in Anserini's README.
> Modify CIRAL's regression documentation to mention dev set

- docs/regressions/regressions-msmarco-passage-splade-pp-sd-onnx.md
- src/main/resources/regression/msmarco-passage-splade-pp-sd-onnx.yaml
Just spotted one inconsistent regression test. Scores are updated using the results of a new run on ORCA.
> Fix splade-pp-sd-onnx regression tests

- docs/regressions/regressions-dl19-passage-cos-dpr-distil-onnx.md
- docs/regressions/regressions-dl19-passage-cos-dpr-distil.md
- docs/regressions/regressions-dl19-passage-openai-ada2.md
- docs/regressions/regressions-dl20-passage-cos-dpr-distil-onnx.md
- docs/regressions/regressions-dl20-passage-cos-dpr-distil.md
- docs/regressions/regressions-dl20-passage-openai-ada2.md
- docs/regressions/regressions-msmarco-passage-cos-dpr-distil-onnx.md
- docs/regressions/regressions-msmarco-passage-cos-dpr-distil.md
- docs/regressions/regressions-msmarco-passage-openai-ada2.md
- src/main/resources/docgen/templates/dl19-passage-cos-dpr-distil-onnx.template
- src/main/resources/docgen/templates/dl19-passage-cos-dpr-distil.template
- src/main/resources/docgen/templates/dl19-passage-openai-ada2.template
- src/main/resources/docgen/templates/dl20-passage-cos-dpr-distil-onnx.template
- src/main/resources/docgen/templates/dl20-passage-cos-dpr-distil.template
- src/main/resources/docgen/templates/dl20-passage-openai-ada2.template
- src/main/resources/docgen/templates/msmarco-passage-cos-dpr-distil-onnx.template
- src/main/resources/docgen/templates/msmarco-passage-cos-dpr-distil.template
- src/main/resources/docgen/templates/msmarco-passage-openai-ada2.template
- src/main/resources/regression/dl19-passage-cos-dpr-distil-onnx.yaml
- src/main/resources/regression/dl20-passage-cos-dpr-distil-onnx.yaml
Also aligns ONNX and non-ONNX versions of cosDPR-distil scores; cf. https://github.com/castorini/anserini/pull/2231
> Tweak regression docs and ONNX cosDPR-distil scores

- src/main/python/run_regression.py
For ONNX runs, increase tolerance a bit because we observe some minor differences across OSes.
> Loosen regression tests tolerance for ONNX runs

- src/main/java/io/anserini/eval/Qrels.java
- src/test/java/io/anserini/eval/RelevanceJudgmentsTest.java
Follow up to [castorini/anserini/pull/2258](https://github.com/castorini/anserini/pull/2258) as branch was deleted. 
Including bindings for dev qrels.
> Follow up: add bindings for CIRAL's dev qrels

- src/main/java/io/anserini/index/IndexHnswDenseVectors.java
Also, bumped up default memory buffer. Should help with indexing speed.
> Skip intermediate merging for HNSW indexing if we're going to optimize at the end

- pom.xml
This commit upgrades to Jacoco 0.8.11 (from 0.8.7). Recent Jacoco versions have added support for Java 20+ versions. 
The motivation for this change is to allow to run and test with more recent Java versions, specifically Java 20 and Java 21.
This allows to enable Lucene's faster SIMD-ized implementations of the vector distance computations.
> Upgrade to Jacoco 0.8.11

- docs/regressions/regressions-dl19-passage-openai-ada2.md
- docs/regressions/regressions-dl20-passage-openai-ada2.md
- docs/regressions/regressions-msmarco-passage-openai-ada2.md
- src/main/resources/regression/dl19-passage-openai-ada2.yaml
- src/main/resources/regression/dl20-passage-openai-ada2.yaml
- src/main/resources/regression/msmarco-passage-openai-ada2.yaml
default of 2047 seems to be too aggressive for `hops`, getting OOM errors.
> Dial down -maxThreadMemoryBeforeFlush for indexing OpenAI Ada2 embeddings

- src/main/java/io/anserini/index/IndexInfo.java
- src/main/java/io/anserini/search/HnswDenseSearcher.java
- src/main/python/e2e_sparse_dense_lucene/reproduction.py
- src/main/resources/e2e_sparse_dense_lucene/pre-encoded.yaml
- src/test/java/io/anserini/index/PrebuiltIndexTest.java
Link to #2307 
Usage:
`python src/main/python/e2e_sparse_dense_lucene/reproduction.py`
> Reproduce e2e sparse+dense Lucene

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Everything worked fine; however, it should be noted that issue #1466 was encountered, even on WSL 2.
Added some minor explanation and typo fixes, in addition to updating the reproduction logs.
---
WSL 2 running Ubuntu 22.04.3 LTS on a Windows 10 machine
- Python 3.10.12
- Java 11.0.21
- Maven 3.6.3
- i7-9700 CPU
- 16 GB RAM
- NVIDIA GeForce RTX 2070 SUPER
> Added reproduction log and minor typos

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Everything worked fine.
- Ubuntu 20.04.5 LTS
- Python 3.8.10
- openjdk 11.0.21
- Apache Maven 3.6.3
- Intel Xeon Platinum 8352V CPU
- RTX 4090(24GB) * 1
- 90GB RAM
PS: 
- I have to disable tests (`-Dmaven.test.skip=true`) to avoid error building Anserini, which is most likely caused by my internet connection. 
- Sorry for the trouble in #2323 . That is because I mistakenly added the log to the older version.
> Add reproduction logs

- docs/elastirini.md
- docs/experiments-covid.md
- docs/experiments-doc2query.md
- docs/experiments-fever.md
- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage-openai-ada2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-v2.md
- docs/solrini.md
Replaces all instances of `tools/eval/trec_eval.9.0.4/trec_eval` with `target/appassembler/bin/trec_eval` in within the experiment docs
> Update experiment docs to use trec_eval 9.0.8

- pom.xml
Upgrade `onnxruntime` version to fix #2354 
- updated `splade-pp-ed-optimized.onnx` on remote end
- updated `onnxruntime` to support `opset 19`
> Upgrade onnx version

- src/main/java/io/anserini/search/SimpleSearcher.java
Quickly adding some of ciral's languages to Simplesearcher for 2cr.
> Add languages to Simplesearcher

- docs/regressions/regressions-dl19-passage-cohere-embed-english-v3-hnsw-int8.md
- docs/regressions/regressions-dl19-passage-cohere-embed-english-v3-hnsw.md
- docs/regressions/regressions-dl20-passage-cohere-embed-english-v3-hnsw-int8.md
- docs/regressions/regressions-dl20-passage-cohere-embed-english-v3-hnsw.md
- docs/regressions/regressions-msmarco-passage-cohere-embed-english-v3-hnsw-int8.md
- src/main/python/msmarco/extract_avg_hnsw_regression_scores_from_log.py
- src/main/resources/regression/dl19-passage-cohere-embed-english-v3-hnsw-int8.yaml
- src/main/resources/regression/dl19-passage-cohere-embed-english-v3-hnsw.yaml
- src/main/resources/regression/dl20-passage-cohere-embed-english-v3-hnsw-int8.yaml
- src/main/resources/regression/dl20-passage-cohere-embed-english-v3-hnsw.yaml
- src/main/resources/regression/msmarco-passage-cohere-embed-english-v3-hnsw-int8.yaml
- src/main/resources/regression/msmarco-passage-cohere-embed-english-v3-hnsw.yaml
I ran four trials on different machines and averaged the scores - to better reflect the variance across multiple trials.
> Tweak scores for Cohere regressions

- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SearchHnswDenseVectors.java
- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/SearchHnswDenseVectorsTest.java
- src/test/java/io/anserini/search/topicreader/TopicsTest.java
For something like:
```
java -cp anserini-0.24.1-fatjar.jar io.anserini.search.SearchCollection \
-index msmarco-v1-passage \
-topics MSMARCO_PASSAGE_DEV_SUBSET \
-output run.msmarco-passage.bm25.txt \
-threads 16 \
-bm25
```
We can refer to `msmarco-passage-dev` instead of the full Enum `MSMARCO_PASSAGE_DEV_SUBSET`.
> Add support for readable lowercase topics

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Anserini had issues while compiling. For some reason the javadoc executeable was missing in my jdk (was not installed via tha official tar compressed file). Fixed by reinstalling jdk properly.
The specs are:
Ubuntu 20.04 (8GB + 128 GB SSD) dual booted with windows having 1TB HDD
Python 3.8 (Used virtualenv for Python 3.10)
java 11.0.21
Apache Maven 3.6.3
> Onboarding Reproduction Logs

- .gitignore
- docs/experiments-msmarco-passage.md
- docs/start-here.md
Hardware:
CPU: Apple M2 Pro
RAM: 32GB
Environment:
- Operating System: macOS 14.2.1
- Python Version: Python 3.10.10
- Java Version: openjdk 11.0.11
- Maven Version: Apache Maven 3.9.6
The setup was successfully reproduced. Working in vscode auto-generated a .vscode/settings.json, which should be added to the .gitignore for future VSCode users.
> Update Reproduction Log

- src/main/java/io/anserini/search/ScoredDocs.java
- src/main/python/fine_tuning/run_batch.py
- src/main/python/fine_tuning/search.py
- src/main/python/trec-covid/covid_baseline_tools.py
- src/main/python/trec-covid/generate_round1_baselines.py
- src/main/python/trec-covid/generate_round2_baselines.py
- src/main/python/trec-covid/generate_round4_doc2query_baselines.py
- src/main/python/trec-covid/generate_round5_doc2query_baselines.py
Renamed `SearchCollection` parameters a while ago but never fixed in Python scripts for TREC-COVID regressions and fine-tuning experiments.
> Fix TREC-COVID regressions and fine-tuning experiments

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Configuration:
Processor Speed (Max): 1800 MHz
Memory (RAM): 16 GB
Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (GenuineIntel)
Operating System: Microsoft Windows 10 Pro (64-bit)
Number of Cores: 4
Number of Logical Processors: 8
Initially, I tried to solve the problems associated with the repo Anserini using PowerShell and converting the scripts to PowerShell format for Windows. However, I encountered a few issues while running on Windows. For instance, installing Maven and trec_eval on Windows resulted in errors. Consequently, I resorted to virtualization on my computer using WSL (Ubuntu 22.04.4). One issue I encountered while using Ubuntu was that when I extracted any compressed files from the Ubuntu terminal, later on, when I attempted to read or write to that file, it denied …
> Update Reproduction Logs

- pom.xml
Fixed indentation.
I must admit that futzing with Maven POMs remains alchemy to me... really not sure if I've done things correctly. Here's the main issue I tried to fix (successfully?):
Shading seems to run twice. First:
```
[INFO] --- shade:3.5.3:shade (default) @ anserini ---
[INFO] Including org.apache.lucene:lucene-core:jar:9.9.1 in the shaded jar.
[INFO] Including org.apache.lucene:lucene-codecs:jar:9.9.1 in the shaded jar.
...
```
And runs again:
```
[INFO] --- shade:3.5.3:shade (shade-jar-with-dependencies) @ anserini ---
[INFO] Including org.apache.lucene:lucene-core:jar:9.9.1 in the shaded jar.
[INFO] Including org.apache.lucene:lucene-codecs:jar:9.9.1 in the shaded jar.
[INFO] Including org.apache.lucene:lucene-backward-codecs:jar:9.9.1 in the shaded jar.
...
```
I traced it …
> Refactor and clean-up POM

- README.md
- docs/fatjar-regressions/fatjar-regressions-v0.35.1.md
- docs/fatjar-regressions/fatjar-regressions-v0.36.1-SNAPSHOT.md
Copied the existing v0.36.0 docs to v0.36.1-SNAPSHOT in anticipation of documenting new features, e.g., @16BitNarwhal and @wu-ming233 are working on.
> Add v0.36.1-SNAPSHOT docs; fixed typos in existing docs

- src/main/java/io/anserini/reproduce/RunRepro.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/resources/reproduce/msmarco-v2.1-doc.yaml
Proposed fix to https://github.com/castorini/anserini/issues/2480#issuecomment-2085063194
The issue is that '#' may get interpreted as a comment; WSL and Mac might also different on how interpolation, escaping, etc. is handled with `ProcessBuilder`. This works on my Mac.
> Fix MS MARCO V2.1 repo experiments on segmented doc collection

- docs/fatjar-regressions/fatjar-regressions-v0.36.1-SNAPSHOT.md
- docs/reproduce/msmarco-v1-passage.html
- src/main/java/io/anserini/reproduce/RunBeir.java
- src/main/java/io/anserini/reproduce/RunMsMarco.java
- src/main/java/io/anserini/reproduce/RunRepro.java
- src/main/resources/reproduce/beir.yaml
- src/main/resources/reproduce/msmarco-v1-passage.yaml
- src/main/resources/reproduce/msmarco-v2.1.yaml
- src/test/java/io/anserini/doc/GenerateReproductionDocsTest.java
Aligned regression documentation output format with the repro scripts. The unified format is:
```
run.collection-name.condition-name.topic-name.txt
```
where `collection-name` in {"msmarco-v2.1-doc", "msmarco-v1-passage", "beir"}, `condition-name` is specified in the yaml files under `src/main/resources/reproduce`, and `topic-name` is specified by the corpus.
Additionally, the repro scripts now run the same amount of cases as in the documentation.
> Aligned doc output format with repro scripts

- docs/experiments-msmarco-passage.md
- docs/start-here.md
**Environment Details:**
-**Operating System:** Ubuntu 22.04.4 LTS
-**Java Version:** Upgraded to JDK 21 from JDK 11 to resolve compatibility issues that were initially causing build failures.
**Experience:**
The process followed the outlined steps without significant issues, except for an initial JDK version mismatch. Once the JDK was updated to version 21, all scripts executed flawlessly, and the expected results were successfully reproduced. The step-by-step guidance provided was clear and easy to follow.
**Suggestions for Improvement:**
Considering the JDK version mismatch issue I encountered, it could be beneficial to include a specific note about verifying JDK version requirements in the setup documentation, similar to the approach taken in the Pyserini documentation.
> Add Reproduction Results for Anserini Repo Steps

- src/main/java/io/anserini/server/SearchService.java
- src/test/java/io/anserini/server/ControllerTest.java
Fixed the params `k1` and `b` to match the fatjar regressions https://github.com/castorini/anserini/blob/master/docs/fatjar-regressions/fatjar-regressions-v0.36.1-SNAPSHOT.md
> Fix default params in webapp

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Setup:
I did this on Google Collab with the following specifications:
OpenJDK 21.0.2
Python 3.10.12
On Google Colab, the intial version was JDK 11 and so I had to upgrade that after which the everything ran smoothly. One problem with doing this on Google Colab was that sometimes the session had to be restarted at which point I lost all the work I had done. To fix this, I had to create a back up on my Google Drive.
> Added to Reproduction Logs

- src/main/frontend/pages/components/SearchBar.tsx
- src/main/java/io/anserini/server/Controller.java
Renamed `/api/collection/` to `/api/index/`
following issue #2502
> Rename collection to index in route

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Operating System: Ubuntu 22.04.4 LTS
I performed the onboarding through terminal, and it went very smoothly for the most part. There was only one thing I had to do outside of the guide, which was make 'python' an alias for 'python3' to get the commands to work. Initially, I just ran the commands with 'python3' instead of 'python', but eventually when I got to the unit testing, it ended up failing. The tests passed once I added the alias.
> Add to Reproduction Log

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Successfully reproduced the result on my local Macbook Pro M3. Encountered several issues:
- Had to modify run.sh to change the -Xms to 2GB and -Xmx to 6GB in order for the program to not abort while building the index, hypothetically maybe due to the fact that the new M3 Mac only has 8GB memory, and JVM was being lazy on Garbage collection and excessively allocating memory, thinking it had 64GB instead of 8GB, which may cause excessive swapping to disk and killed the program.
- Java 21 did not seem to be available on student environment, because administrator access was needed to install the package, I had to go back to my local computer to go through this guide.
> Successfully Reproduced Experiments for Onboarding - Sean Song

- bin/run.sh
- docs/experiments-msmarco-passage.md
- docs/start-here.md
- Details on my setup:
- OS: Ubuntu 22.04.2 LTS
- System: VivoBook_ASUSLaptop X513EQN_K513
- RAM: 16G
- Openjdk: 21.0.3
- Apache Maven: 3.9.7
- Python: 3.10.12
- Indication of success:
- For building "anserini" I used the following option because the tests need to download so many files which can not be handled due to my weak network connection.
`mvn clean package -DskipTests`
- For building the inverted index I had to change `-Xmx 64G` to `-Xmx16G` in the following line in bin\run.sh file:
```java` -cp `ls target/*-fatjar.jar` -Xms512M -Xmx16G --add-modules jdk.incubator.vector $@```
Then everything worked successfully!
> Add Reproduction Logs - Hosna Oyarhoseini

- src/main/java/io/anserini/analysis/CompositeAnalyzer.java
- src/main/java/io/anserini/analysis/HuggingFaceTokenizerAnalyzer.java
Another take for #2535
After digging through source code:
https://github.com/deepjavalibrary/djl/blob/master/extensions/tokenizers/src/main/java/ai/djl/huggingface/tokenizers/HuggingFaceTokenizer.java
I was able to override the tokenize arbitrarily long sequences.
> Fix tokenizer length issue with DJL upgrade

- docs/experiments-msmarco-passage.md
- docs/start-here.md
I reproduced results on macOS using MacBook terminal. Everything worked successfully, except for using `curl` instead of `wget` for downloading the dataset.
Setup details:
- Operating System: macOS
- Environment: MacBook terminal
- Configuration: Since wget command did not work for me, I used `curl -o collections/msmarco-passage/collectionandqueries.tar.gz https://msmarco.z22.web.core.windows.net/msmarcoranking/collectionandqueries.tar.gz` instead of `wget`.
All steps completed without any issues.
Here is my device's information:
- macOS version 12.7.5 (21H1222)
- MacBook Air (Retina, 13-inch, 2018)
- Processor 1.6 GHz Dual-Core Intel Core i5
- Memory 8 GB 2133 MHz LPDDR3
- Graphics Intel UHD Graphics 617 1536 MB
> Add reproduction log

- src/main/python/run_regression.py
Latest runs of regression had a few errors, tweaked tolerance levels to compensate.
> Tweak score tolerance for regressions

- docs/onnx-conversion.md
- src/main/python/onnx/convert_hf_model_to_onnx.py
Steps in guide reproduced and got the same results
System Details:
Macbook Pro M1
8 GB RAM
MacOS Sonoma 14.4.1
> ONNX reproduction logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Completed start-here and the ms-macro-passage indexing, retrieval, and evaluation 
Environment 
CS Student Linux Server
Ubuntu 22.04.4 LTS
Python 3.10.12 (Default on Linux Server)
java 21.0.4
Apache Maven 3.9.5
Issues while setting up
- The linux server by default comes w/ Java 11 which is out of date for building (ran into this issue and had to change `$PATH`)
- Also had to run `ulimit -t unlimited` to give unlimited CPU time
It could be worth [re-opening this issue](https://github.com/castorini/pyserini/issues/1611) and adding to the documentation how to update java + maven
> Completed Onboarding

- src/main/java/io/anserini/index/IndexCollection.java
I noticed the setSimilarity options were set up as if they were a block of if else statements --- without the else if. If you tried to set BM25Accurate, it would be overridden by BM25.
> Fixes missing else to setSimilarity options

- pom.xml
Removed junit5 dependencies which caused the juni4 tests not recognized when building.
> removed junit5 dependencies causing test error

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Run on Windows 11 WSL 2 with Ubuntu 22.04.
Hardware: 5600x 32GB ram with 3060ti 8GB of VRAM.
> Reproduction logs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
windows OS with conda environment. a bit of adjustment needed for indexing and retrieval (xms to 512mb and xmx to 4gb eventhough my machine runs on 24gb of ram, also 4 threads in the command instead of 9). I encountered more errors on Windows than on Linux, but most of them can be easily fixed with a quick online search. Other than these, everything worked just fine.
> Add to onboarding reproduction logs (#2614)

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Completed the onboarding on MacOS (MacBook Pro M1)
After completing the build for Anserini (with these instructions: https://github.com/castorini/anserini?tab=readme-ov-file#-installation), running the bin/run.sh commands led to the following exception:
Error: A JNI error has occurred, please check your installation and try again
The workaround was to get the fatjar with the following command:
wget https://repo1.maven.org/maven2/io/anserini/anserini/0.38.0/anserini-0.38.0-fatjar.jar
Then, I ran modified bin/run.sh commands with this specific fatjar and was able to proceed with the onboarding.
> Added to Reproduction Logs (Anserini) - Raghav Vasudeva

- docs/experiments-msmarco-passage.md
- docs/start-here.md
- pom.xml
Hi all,
I am using a Mac Pro with M2 chip
jdk-21.0.5
mvn 3.9.9
python 3.9.6
some problems I encountered:
1. tests error during maven build project
2. Exception in thread "main" java.lang.SecurityException
Solution to problems
1. use `mvn clean package -DskipTests` instead
2. Add in pom.xml, maven-shade-plugin's configuration
`<filters>`
`                  <filter>`
`                      <artifact>*:*</artifact>`
`                     <excludes>`
`                          <exclude>META-INF/*.SF</exclude>`
`                         <exclude>META-INF/*.DSA</exclude>`
`                        <exclude>META-INF/*.RSA</exclude>`
`                      </excludes>`
`                  </filter>`
`</filters>`
> Successful Reproduction of Anserini

- docs/experiments-20newsgroups.md
I wanted to reproduce this (indexing works as expected when I directly used the fatjar), but I ran into the following using the commands in the guide.
Similar to this issue: https://github.com/castorini/anserini/issues/1107, but I don't have the `JAVA_HOME` error.
The `mvn clean appassembler:assemble` command fails with the following error:
```
Failed to execute goal org.codehaus.mojo:appassembler-maven-plugin:2.1.0:assemble on project anserini: The parameters ‘programs’ for goal org.codehaus.mojo:appassembler-maven-plugin:2.1.0:assemble are missing or invalid
```
To index train and test together:
```bash
sh target/appassembler/bin/IndexCollection \
-collection TwentyNewsgroupsCollection \
-input collections/20newsgroups/20news-bydate \
-index indexes/lucene-index.20newsgroups.all \ …
```
> Reproducibility - experiments-20newsgroups.md

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Macbook Air M3 (macOS 14.6)
Python 3.13.1
Java openJDK 23.0.1
Maven 3.9.9
All the results were reproduced without any problem. However during the build time using Maven I encountered errors on 5 test cases on these classes: 
- JsonVectorCollectionDocumentObjectTest, BM25StatTest, BigramFeaturesTest, LmDirTest, ExtractTopDfTermsTest
and the errors were like this:
- [ERROR]   JsonVectorCollectionDocumentObjectTest The test or suite printed 16688 bytes to stdout and stderr, even though the limit was set to 8192 bytes. Increase the limit with @limit, ignore it completely with @SuppressSysoutChecks or run with -Dtests.verbose=true
Basically the errors indicate that the tests are failing because the amount of output printed to stdout and stderr during the test execution exceeded the allowed …
> Reproducing Results of BM25 Baselines for MS MARCO

- pom.xml
- src/test/java/io/anserini/collection/ParquetDenseVectorCollectionTest.java
Pruned with https://github.com/strategicblue/parquet-floor, as well as added tests.
> Prune Parquet Dependencies

- docs/regressions-log.md
Update docs to make sure we have good record-keeping.
> Update regression docs

- docs/experiments-msmarco-passage.md
- docs/start-here.md
Environment: Google IDX Project (RAM ≤ 8GB)
Successfully onboarded Anserini. Everything worked except `mvn clean package`, which had to be run differently to avoid resource overhead:
$ mvn clean package -DskipTests -Dmaven.test.skip=true -Dgpg.skip=true
Note: The `-Dgpg.skip=true` flag was added to resolve an issue with GitHub Codespace and can be ignored.
> Complete onboarding for Anserini

- docs/regressions-log.md
- src/main/python/regressions-batch03.txt
Before, running the cached and onnx versions of the regressions was causing conflicts because they were both trying to write to the same index location. Instead, spread them out.
Also, add docs for lexlsh/fw regressions.
> Move regression order to avoid conflicts

- src/main/java/io/anserini/index/IndexInfo.java
- src/main/java/io/anserini/search/FlatDenseSearcher.java
- src/main/java/io/anserini/search/HnswDenseSearcher.java
- src/test/java/io/anserini/search/SearchFlatDenseVectorsTest.java
- src/test/java/io/anserini/search/SearchHnswDenseVectorsTest.java
I tried various refactors, etc. which all kinda grew too much in complexity.
Using the direct class names would be nice (which I tried),
but unfortunately it would break things in the following ways.
- If we only fix the naming, then we're done.
- If we change IndexInfo to use direct class names, {Class}.class, then we'd have to change how it is used at various places. Since these entries are the fallback if no encoder is specified (in the API), it would mean we have diverging ways of representing this information vs. command-line arguments. 
- If we support both, well, it would get messy. There would be different behaviour from the CLI and the fallback values overall, having IndexInfo match what the searchers and their CLI arguments (e,g, HnswDenseSearcher) expect is the least confusing …
> Adjust IndexInfo naming to align with CLI arguments

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
- OS: macOS (M2 Pro)
- RAM: 32GB
- Disk: 512GB
- Python Version: 3.10.13
- Java 21 installation
- `brew install openjdk@21`
- `export JAVA_HOME=/opt/homebrew/opt/openjdk@21/`
- `export JVM_PATH=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home/lib/server/libjvm.dylib`
- Successfully reproduced all results after updating Java version from 17 to 21
> Add to reproduction logs

- docs/experiments-beir-fusion.md
While I was checking fusion numbers I found a small typo that said it was going to run normalize fusion, but actually performed interpolation.
> Fix small typo on fusion experiments

- src/test/java/io/anserini/index/PrebuiltIndexTest.java
Fixes #2800 by closing the URL connection after each URL is tested so it doesn't reach the rate limit.
> Fix PrebuiltIndexTest by closing connections

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
This pull request adds reproduction log entries to the following documentation files:
- `start-here.md`
- `experiments-msmarco-passage.md`
- `experiments-msmarco-passage2.md`
System Environment:
- **OS:** macOS 14.4.1
- **Python:** 3.9.13
- **Java:** OpenJDK 23.0.2 (via Homebrew)
- **Commit reproduced:** [`c07454b`](https://github.com/castorini/anserini/commit/c07454b7c64422789834314d97348907c8c66842)
Results:
All experiments were successfully reproduced as described. No errors encountered.
> Anserini reproduction confirmation

- src/main/java/io/anserini/search/topicreader/Topics.java
- src/test/java/io/anserini/search/topicreader/TopicReaderTest.java
Add topic bindings for BEIR SPLADEv3. The commands added for #2835 and #2816 should be able to run now.
> Add topic bindings for BEIR SPLADEv3

- pom.xml
I'm looking at this: https://github.com/castorini/anserini/actions/runs/15882221286/job/44785316021
The stacktrace is here:
```
Error:  io.anserini.analysis.AutoCompositeAnalyzerTest.case1  Time elapsed: 0.093 s  <<< ERROR!
java.lang.RuntimeException: request error: Bad URL: failed to parse URL: RelativeUrlWithoutBase: relative URL without a base
at ai.djl.huggingface.tokenizers.jni.TokenizersLibrary.createTokenizer(Native Method)
at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:120)
at io.anserini.analysis.CompositeAnalyzer.makeTokenizer(CompositeAnalyzer.java:57)
at io.anserini.analysis.CompositeAnalyzer.<init>(CompositeAnalyzer.java:62)
at io.anserini.analysis.AutoCompositeAnalyzer.getAnalyzer(AutoCompositeAnalyzer.java:93)
at …
```
> Upgrade djl artifacts

- src/main/python/run_regression.py
- src/main/resources/regression/bright-aops.yaml
- src/main/resources/regression/bright-biology.yaml
- src/main/resources/regression/bright-earth-science.yaml
- src/main/resources/regression/bright-economics.yaml
- src/main/resources/regression/bright-leetcode.yaml
- src/main/resources/regression/bright-pony.yaml
- src/main/resources/regression/bright-psychology.yaml
- src/main/resources/regression/bright-robotics.yaml
- src/main/resources/regression/bright-stackoverflow.yaml
- src/main/resources/regression/bright-sustainable-living.yaml
- src/main/resources/regression/bright-theoremqa-questions.yaml
- src/main/resources/regression/bright-theoremqa-theorems.yaml
As of https://github.com/castorini/anserini/pull/2886, the exclusion command from regression yamls is no longer needed, so this PR removes them.
> Remove exclude feature for BRIGHT from regression yamls

- docs/prebuilt-indexes.md
- src/main/java/io/anserini/index/IndexReaderUtils.java
- src/test/java/io/anserini/doc/GeneratePrebuiltIndexesDocTest.java
Addresses #2907.
Small change to IndexReaderUtils so it downloads the index if it's not present locally. Easy way to download index by name. Also parallels Pyserini's `prebuilt-indexes.md`'s instructions to get index stats.
> Add auto-generation of doc page about prebuilt indexes

- src/main/java/io/anserini/index/AbstractIndexer.java
- src/main/java/io/anserini/index/IndexCollection.java
- src/main/java/io/anserini/index/SimpleIndexer.java
- src/main/java/io/anserini/search/FlatDenseSearcher.java
- src/main/java/io/anserini/search/HnswDenseSearcher.java
- src/main/java/io/anserini/search/InvertedDenseSearcher.java
- src/main/java/io/anserini/search/SearchCollection.java
- src/main/java/io/anserini/search/SimpleImpactSearcher.java
- src/main/java/io/anserini/search/SimpleSearcher.java
- src/main/java/io/anserini/util/BenchmarkCollectionReader.java
The goal of this work is to resolve this [issue](https://github.com/castorini/anserini/issues/2579)
In this work, all instances of __ThreadPoolExecutor__ have been replaced with __newWorkStealingPool__  in the codebase with the benefit of maximizing CPU utilization. In addition, `executor.invokeAll(tasks)` has been used in place of different instances of `executor.awaitTermination(), executor.shutdown() and executor.shutdownNow()` necessary for ensuring complete execution of multiple tasks before moving unto other code executions in a file.
I have also added a `monitor` in `BenchmarkCollectionReader, AbstractIndexer, and IndexCollection` class to maintain the existing INFO logs in the process of refactor.
Finally, I have also left in `processSegments(executor, segmentpaths)` for backward …
> Replace ThreadPoolExecutor with newWorkStealingPool

- src/main/java/io/anserini/index/IndexInfo.java
Hi @lilyjge - I found a mismatch vs. Pyserini: https://github.com/castorini/pyserini/blob/master/pyserini/prebuilt_index_info.py
This PR aligns the file names and MD5 checksums.
```
"msmarco-v2-doc": {
"description": "Lucene index of the MS MARCO V2 document corpus.",
"filename": "lucene-inverted.msmarco-v2-doc.20220808.4d6d2a.tar.gz",
"readme": "lucene-inverted.msmarco-v2-doc.20220808.4d6d2a.README.md",
"urls": [
"https://rgw.cs.uwaterloo.ca/pyserini/indexes/lucene/lucene-inverted.msmarco-v2-doc.20220808.4d6d2a.tar.gz",
],
"md5": "11017a76d2927294977c360a174ba1be",
"size compressed (bytes)": 63431305265,
"total_terms": 14165667143,
"documents": 11959635,
"unique_terms": 44860768,
"downloaded": False
},
"msmarco-v2-doc-segmented": {
"description": "Lucene index of the MS MARCO V2 …
```
> Fix tarball names and MD5 checksums for MS MARCO v2 {doc, segmented doc}

- docs/experiments-msmarco-passage.md
- docs/experiments-msmarco-passage2.md
- docs/start-here.md
- **OS**: macOS 15.5 (Apple Silicon M2)
- **Hardware**: MacBook Pro, 16GB RAM
- **Java**: 21.0.1
- **Python**: 3.11.9
- **Environment**: Standard terminal(zsh)
**Successfully reproduced BM25 baseline:**
- MRR@10: 0.1875
- MAP: 0.1957
- Recall@1000: 0.8573
**Successfully reproduced dense retrieval with BGE-base-en-v1.5.hnsw:**
- MRR@10: 0.3521
**Confirmed dense retrieval outperforms BM25** 
(0.3521 vs 0.1875 MRR@10, ~87% improvement)
> Add onboarding reproduction log entries

- pom.xml
- src/main/java/io/anserini/index/generator/TweetGenerator.java
This PR is addresses issue #2937 . I ran a JMH microbenchmark on deletes.contains() line as it runs for each tweet processed.
Speed Comparison:
```
A: Set Size = 10,000 IDs, Hit Ratio = 10%
-[Java HashSet] Lookup Perf: 50,000 lookups in 2.103 ms (23.78 Mops/s)
-[FastUtil] Lookup Perf: 50,000 lookups in 2.243 ms (22.29 Mops/s)
-[HPPC] Lookup Perf: 50,000 lookups in 2.475 ms (20.20 Mops/s)
B: Set Size = 50,000 IDs, Hit Ratio = 15%
-[Java HashSet] Lookup Perf: 50,000 lookups in 55.943 ms (0.894 Mops/s)
-[FastUtil] Lookup Perf: 50,000 lookups in 39.959 ms (1.251 Mops/s)
-[HPPC] Lookup Perf: 50,000 lookups in 34.732 ms (1.440 Mops/s)
```
Not included here, but in a JVM benchmark, Java HashSet had a much high memory consumption and is inconsistent. 
Size comparison:
| Name …
> Replace fastutil with HPPC

- pom.xml
Thanks to @JJGreen0 #2939 and @suraj-subrahmanyan #2945 - we've eliminated the fastutil dependency!
Fatjar size drops from 176mb to 155mb, yay!
> Remove fastutil dependency
